[package]
name = "vtk-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Raw FFI bindings to the Visualization Toolkit (VTK)"
links = "rvtk_shim"
build = "build.rs"

[lib]
name = "vtk_sys"
path = "src/lib.rs"
doctest = false

[build-dependencies]
cmake = "0.1"
