// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkAnnotationLayers.h"
#include "vtkAnnotation.h"
#include "vtkDataObject.h"
#include "vtkInformation.h"
#include "vtkInformationVector.h"
#include "vtkObjectBase.h"
#include "vtkSelection.h"
#include <string>

extern "C" void* vtkAnnotationLayers__rvtk_new() { return static_cast<void*>(vtkAnnotationLayers::New()); }

extern "C" int32_t vtkAnnotationLayers__IsTypeOf__0(const char* type_) {
  return vtkAnnotationLayers::IsTypeOf(type_);
}

extern "C" int32_t vtkAnnotationLayers__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAnnotationLayers*>(self)->IsA(type_);
}

extern "C" void* vtkAnnotationLayers__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkAnnotationLayers::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkAnnotationLayers__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkAnnotationLayers::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkAnnotationLayers__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAnnotationLayers*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkAnnotationLayers__GetDataObjectType__0(void* self) {
  (void)self;
  return static_cast<vtkAnnotationLayers*>(self)->GetDataObjectType();
}

extern "C" void vtkAnnotationLayers__SetCurrentAnnotation__0(void* self, void* ann) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->SetCurrentAnnotation(static_cast<vtkAnnotation*>(ann));
}

extern "C" void* vtkAnnotationLayers__GetCurrentAnnotation__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkAnnotationLayers*>(self)->GetCurrentAnnotation());
}

extern "C" void vtkAnnotationLayers__SetCurrentSelection__0(void* self, void* sel) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->SetCurrentSelection(static_cast<vtkSelection*>(sel));
}

extern "C" void* vtkAnnotationLayers__GetCurrentSelection__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkAnnotationLayers*>(self)->GetCurrentSelection());
}

extern "C" uint32_t vtkAnnotationLayers__GetNumberOfAnnotations__0(void* self) {
  (void)self;
  return static_cast<vtkAnnotationLayers*>(self)->GetNumberOfAnnotations();
}

extern "C" void* vtkAnnotationLayers__GetAnnotation__0(void* self, uint32_t idx) {
  (void)self;
  return static_cast<void*>(static_cast<vtkAnnotationLayers*>(self)->GetAnnotation(idx));
}

extern "C" void vtkAnnotationLayers__AddAnnotation__0(void* self, void* ann) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->AddAnnotation(static_cast<vtkAnnotation*>(ann));
}

extern "C" void vtkAnnotationLayers__RemoveAnnotation__0(void* self, void* ann) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->RemoveAnnotation(static_cast<vtkAnnotation*>(ann));
}

extern "C" void vtkAnnotationLayers__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->Initialize();
}

extern "C" void vtkAnnotationLayers__ShallowCopy__0(void* self, void* other) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->ShallowCopy(static_cast<vtkDataObject*>(other));
}

extern "C" void vtkAnnotationLayers__DeepCopy__0(void* self, void* other) {
  (void)self;
  static_cast<vtkAnnotationLayers*>(self)->DeepCopy(static_cast<vtkDataObject*>(other));
}

extern "C" void* vtkAnnotationLayers__GetData__0(void* info) {
  return static_cast<void*>(vtkAnnotationLayers::GetData(static_cast<vtkInformation*>(info)));
}

extern "C" void* vtkAnnotationLayers__GetData__1(void* v, int32_t i) {
  return static_cast<void*>(vtkAnnotationLayers::GetData(static_cast<vtkInformationVector*>(v), i));
}

extern "C" unsigned long vtkAnnotationLayers__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkAnnotationLayers*>(self)->GetMTime();
}

