// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkCachedStreamingDemandDrivenPipeline.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkCachedStreamingDemandDrivenPipeline__rvtk_new() { return static_cast<void*>(vtkCachedStreamingDemandDrivenPipeline::New()); }

extern "C" int32_t vtkCachedStreamingDemandDrivenPipeline__IsTypeOf__0(const char* type_) {
  return vtkCachedStreamingDemandDrivenPipeline::IsTypeOf(type_);
}

extern "C" int32_t vtkCachedStreamingDemandDrivenPipeline__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCachedStreamingDemandDrivenPipeline*>(self)->IsA(type_);
}

extern "C" void* vtkCachedStreamingDemandDrivenPipeline__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkCachedStreamingDemandDrivenPipeline::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkCachedStreamingDemandDrivenPipeline__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkCachedStreamingDemandDrivenPipeline::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkCachedStreamingDemandDrivenPipeline__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCachedStreamingDemandDrivenPipeline*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkCachedStreamingDemandDrivenPipeline__SetCacheSize__0(void* self, int32_t size) {
  (void)self;
  static_cast<vtkCachedStreamingDemandDrivenPipeline*>(self)->SetCacheSize(size);
}

extern "C" int32_t vtkCachedStreamingDemandDrivenPipeline__GetCacheSize__0(void* self) {
  (void)self;
  return static_cast<vtkCachedStreamingDemandDrivenPipeline*>(self)->GetCacheSize();
}

