// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGridSynchronizedTemplates3D.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkGridSynchronizedTemplates3D__rvtk_new() { return static_cast<void*>(vtkGridSynchronizedTemplates3D::New()); }

extern "C" int32_t vtkGridSynchronizedTemplates3D__IsTypeOf__0(const char* type_) {
  return vtkGridSynchronizedTemplates3D::IsTypeOf(type_);
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->IsA(type_);
}

extern "C" void* vtkGridSynchronizedTemplates3D__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGridSynchronizedTemplates3D::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGridSynchronizedTemplates3D__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGridSynchronizedTemplates3D::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGridSynchronizedTemplates3D__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" unsigned long vtkGridSynchronizedTemplates3D__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetMTime();
}

extern "C" void vtkGridSynchronizedTemplates3D__SetComputeNormals__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetComputeNormals(_arg);
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetComputeNormals__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetComputeNormals();
}

extern "C" void vtkGridSynchronizedTemplates3D__ComputeNormalsOn__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->ComputeNormalsOn();
}

extern "C" void vtkGridSynchronizedTemplates3D__ComputeNormalsOff__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->ComputeNormalsOff();
}

extern "C" void vtkGridSynchronizedTemplates3D__SetComputeGradients__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetComputeGradients(_arg);
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetComputeGradients__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetComputeGradients();
}

extern "C" void vtkGridSynchronizedTemplates3D__ComputeGradientsOn__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->ComputeGradientsOn();
}

extern "C" void vtkGridSynchronizedTemplates3D__ComputeGradientsOff__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->ComputeGradientsOff();
}

extern "C" void vtkGridSynchronizedTemplates3D__SetComputeScalars__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetComputeScalars(_arg);
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetComputeScalars__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetComputeScalars();
}

extern "C" void vtkGridSynchronizedTemplates3D__ComputeScalarsOn__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->ComputeScalarsOn();
}

extern "C" void vtkGridSynchronizedTemplates3D__ComputeScalarsOff__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->ComputeScalarsOff();
}

extern "C" void vtkGridSynchronizedTemplates3D__SetGenerateTriangles__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetGenerateTriangles(_arg);
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetGenerateTriangles__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetGenerateTriangles();
}

extern "C" void vtkGridSynchronizedTemplates3D__GenerateTrianglesOn__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->GenerateTrianglesOn();
}

extern "C" void vtkGridSynchronizedTemplates3D__GenerateTrianglesOff__0(void* self) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->GenerateTrianglesOff();
}

extern "C" void vtkGridSynchronizedTemplates3D__SetValue__0(void* self, int32_t i, double value) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetValue(i, value);
}

extern "C" double vtkGridSynchronizedTemplates3D__GetValue__0(void* self, int32_t i) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetValue(i);
}

extern "C" void vtkGridSynchronizedTemplates3D__SetNumberOfContours__0(void* self, int32_t number) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetNumberOfContours(number);
}

extern "C" int64_t vtkGridSynchronizedTemplates3D__GetNumberOfContours__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetNumberOfContours();
}

extern "C" void vtkGridSynchronizedTemplates3D__GenerateValues__0(void* self, int32_t numContours, double* range) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->GenerateValues(numContours, range);
}

extern "C" void vtkGridSynchronizedTemplates3D__GenerateValues__1(void* self, int32_t numContours, double rangeStart, double rangeEnd) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->GenerateValues(numContours, rangeStart, rangeEnd);
}

extern "C" void vtkGridSynchronizedTemplates3D__SetInputMemoryLimit__0(void* self, long limit) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetInputMemoryLimit(limit);
}

extern "C" void vtkGridSynchronizedTemplates3D__SetOutputPointsPrecision__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGridSynchronizedTemplates3D*>(self)->SetOutputPointsPrecision(_arg);
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetOutputPointsPrecisionMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetOutputPointsPrecisionMinValue();
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetOutputPointsPrecisionMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetOutputPointsPrecisionMaxValue();
}

extern "C" int32_t vtkGridSynchronizedTemplates3D__GetOutputPointsPrecision__0(void* self) {
  (void)self;
  return static_cast<vtkGridSynchronizedTemplates3D*>(self)->GetOutputPointsPrecision();
}

