// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkPolyData.h"
#include "vtkAbstractCellLinks.h"
#include "vtkCell.h"
#include "vtkCellArray.h"
#include "vtkDataArray.h"
#include "vtkDataObject.h"
#include "vtkDataSet.h"
#include "vtkGenericCell.h"
#include "vtkIdList.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkInformation.h"
#include "vtkInformationVector.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkPolyData__rvtk_new() { return static_cast<void*>(vtkPolyData::New()); }

extern "C" void* vtkPolyData__ExtendedNew__0() {
  return static_cast<void*>(vtkPolyData::ExtendedNew());
}

extern "C" int32_t vtkPolyData__IsTypeOf__0(const char* type_) {
  return vtkPolyData::IsTypeOf(type_);
}

extern "C" int32_t vtkPolyData__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->IsA(type_);
}

extern "C" void* vtkPolyData__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkPolyData::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkPolyData__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkPolyData::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkPolyData__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkPolyData__GetDataObjectType__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetDataObjectType();
}

extern "C" void vtkPolyData__CopyStructure__0(void* self, void* ds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->CopyStructure(static_cast<vtkDataSet*>(ds));
}

extern "C" int64_t vtkPolyData__GetNumberOfCells__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfCells();
}

extern "C" void* vtkPolyData__GetCell__0(void* self, int64_t cellId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyData*>(self)->GetCell(cellId));
}

extern "C" void vtkPolyData__GetCell__1(void* self, int64_t cellId, void* cell) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetCell(cellId, static_cast<vtkGenericCell*>(cell));
}

extern "C" int32_t vtkPolyData__GetCellType__0(void* self, int64_t cellId) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetCellType(cellId);
}

extern "C" int64_t vtkPolyData__GetCellSize__0(void* self, int64_t cellId) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetCellSize(cellId);
}

extern "C" void vtkPolyData__GetCellBounds__0(void* self, int64_t cellId, double* bounds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetCellBounds(cellId, bounds);
}

extern "C" void vtkPolyData__GetCellNeighbors__0(void* self, int64_t cellId, void* ptIds, void* cellIds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetCellNeighbors(cellId, static_cast<vtkIdList*>(ptIds), static_cast<vtkIdList*>(cellIds));
}

extern "C" void vtkPolyData__CopyCells__0(void* self, void* pd, void* idList, void* locator) {
  (void)self;
  static_cast<vtkPolyData*>(self)->CopyCells(static_cast<vtkPolyData*>(pd), static_cast<vtkIdList*>(idList), static_cast<vtkIncrementalPointLocator*>(locator));
}

extern "C" void vtkPolyData__GetCellPoints__0(void* self, int64_t cellId, void* ptIds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetCellPoints(cellId, static_cast<vtkIdList*>(ptIds));
}

extern "C" void vtkPolyData__GetPointCells__0(void* self, int64_t ptId, void* cellIds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetPointCells(ptId, static_cast<vtkIdList*>(cellIds));
}

extern "C" void vtkPolyData__ComputeCellsBounds__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ComputeCellsBounds();
}

extern "C" void vtkPolyData__GetCellsBounds__0(void* self, double* bounds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetCellsBounds(bounds);
}

extern "C" void vtkPolyData__Squeeze__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->Squeeze();
}

extern "C" int32_t vtkPolyData__GetMaxCellSize__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetMaxCellSize();
}

extern "C" int32_t vtkPolyData__GetMaxSpatialDimension__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetMaxSpatialDimension();
}

extern "C" int32_t vtkPolyData__GetMinSpatialDimension__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetMinSpatialDimension();
}

extern "C" int64_t vtkPolyData__GetCellIdRelativeToCellArray__0(void* self, int64_t cellId) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetCellIdRelativeToCellArray(cellId);
}

extern "C" void vtkPolyData__SetVerts__0(void* self, void* v) {
  (void)self;
  static_cast<vtkPolyData*>(self)->SetVerts(static_cast<vtkCellArray*>(v));
}

extern "C" void* vtkPolyData__GetVerts__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyData*>(self)->GetVerts());
}

extern "C" void vtkPolyData__SetLines__0(void* self, void* l) {
  (void)self;
  static_cast<vtkPolyData*>(self)->SetLines(static_cast<vtkCellArray*>(l));
}

extern "C" void* vtkPolyData__GetLines__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyData*>(self)->GetLines());
}

extern "C" void vtkPolyData__SetPolys__0(void* self, void* p) {
  (void)self;
  static_cast<vtkPolyData*>(self)->SetPolys(static_cast<vtkCellArray*>(p));
}

extern "C" void* vtkPolyData__GetPolys__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyData*>(self)->GetPolys());
}

extern "C" void vtkPolyData__SetStrips__0(void* self, void* s) {
  (void)self;
  static_cast<vtkPolyData*>(self)->SetStrips(static_cast<vtkCellArray*>(s));
}

extern "C" void* vtkPolyData__GetStrips__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyData*>(self)->GetStrips());
}

extern "C" int64_t vtkPolyData__GetNumberOfVerts__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfVerts();
}

extern "C" int64_t vtkPolyData__GetNumberOfLines__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfLines();
}

extern "C" int64_t vtkPolyData__GetNumberOfPolys__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfPolys();
}

extern "C" int64_t vtkPolyData__GetNumberOfStrips__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfStrips();
}

extern "C" bool vtkPolyData__AllocateEstimate__0(void* self, int64_t numCells, int64_t maxCellSize) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->AllocateEstimate(numCells, maxCellSize);
}

extern "C" bool vtkPolyData__AllocateEstimate__1(void* self, int64_t numVerts, int64_t maxVertSize, int64_t numLines, int64_t maxLineSize, int64_t numPolys, int64_t maxPolySize, int64_t numStrips, int64_t maxStripSize) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->AllocateEstimate(numVerts, maxVertSize, numLines, maxLineSize, numPolys, maxPolySize, numStrips, maxStripSize);
}

extern "C" bool vtkPolyData__AllocateExact__0(void* self, int64_t numCells, int64_t connectivitySize) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->AllocateExact(numCells, connectivitySize);
}

extern "C" bool vtkPolyData__AllocateExact__1(void* self, int64_t numVerts, int64_t vertConnSize, int64_t numLines, int64_t lineConnSize, int64_t numPolys, int64_t polyConnSize, int64_t numStrips, int64_t stripConnSize) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->AllocateExact(numVerts, vertConnSize, numLines, lineConnSize, numPolys, polyConnSize, numStrips, stripConnSize);
}

extern "C" bool vtkPolyData__AllocateCopy__0(void* self, void* pd) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->AllocateCopy(static_cast<vtkPolyData*>(pd));
}

extern "C" bool vtkPolyData__AllocateProportional__0(void* self, void* pd, double ratio) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->AllocateProportional(static_cast<vtkPolyData*>(pd), ratio);
}

extern "C" void vtkPolyData__Allocate__0(void* self, int64_t numCells, int32_t extSize) {
  (void)self;
  static_cast<vtkPolyData*>(self)->Allocate(numCells, extSize);
}

extern "C" void vtkPolyData__Allocate__1(void* self, void* inPolyData, int64_t numCells, int32_t extSize) {
  (void)self;
  static_cast<vtkPolyData*>(self)->Allocate(static_cast<vtkPolyData*>(inPolyData), numCells, extSize);
}

extern "C" int64_t vtkPolyData__InsertNextCell__0(void* self, int32_t type_, int32_t npts, const int64_t* pts) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->InsertNextCell(type_, npts, pts);
}

extern "C" int64_t vtkPolyData__InsertNextCell__1(void* self, int32_t type_, void* pts) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->InsertNextCell(type_, static_cast<vtkIdList*>(pts));
}

extern "C" void vtkPolyData__Reset__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->Reset();
}

extern "C" void vtkPolyData__BuildCells__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->BuildCells();
}

extern "C" bool vtkPolyData__NeedToBuildCells__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->NeedToBuildCells();
}

extern "C" void vtkPolyData__BuildLinks__0(void* self, int32_t initialSize) {
  (void)self;
  static_cast<vtkPolyData*>(self)->BuildLinks(initialSize);
}

extern "C" void vtkPolyData__SetLinks__0(void* self, void* _arg) {
  (void)self;
  static_cast<vtkPolyData*>(self)->SetLinks(static_cast<vtkAbstractCellLinks*>(_arg));
}

extern "C" void* vtkPolyData__GetLinks__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyData*>(self)->GetLinks());
}

extern "C" void vtkPolyData__DeleteCells__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->DeleteCells();
}

extern "C" void vtkPolyData__DeleteLinks__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->DeleteLinks();
}

extern "C" void vtkPolyData__GetCellEdgeNeighbors__0(void* self, int64_t cellId, int64_t p1, int64_t p2, void* cellIds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->GetCellEdgeNeighbors(cellId, p1, p2, static_cast<vtkIdList*>(cellIds));
}

extern "C" int32_t vtkPolyData__IsTriangle__0(void* self, int32_t v1, int32_t v2, int32_t v3) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->IsTriangle(v1, v2, v3);
}

extern "C" int32_t vtkPolyData__IsEdge__0(void* self, int64_t p1, int64_t p2) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->IsEdge(p1, p2);
}

extern "C" int32_t vtkPolyData__IsPointUsedByCell__0(void* self, int64_t ptId, int64_t cellId) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->IsPointUsedByCell(ptId, cellId);
}

extern "C" void vtkPolyData__ReplaceCell__0(void* self, int64_t cellId, void* ids) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ReplaceCell(cellId, static_cast<vtkIdList*>(ids));
}

extern "C" void vtkPolyData__ReplaceCell__1(void* self, int64_t cellId, int32_t npts, const int64_t* pts) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ReplaceCell(cellId, npts, pts);
}

extern "C" void vtkPolyData__ReplaceCellPoint__0(void* self, int64_t cellId, int64_t oldPtId, int64_t newPtId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ReplaceCellPoint(cellId, oldPtId, newPtId);
}

extern "C" void vtkPolyData__ReplaceCellPoint__1(void* self, int64_t cellId, int64_t oldPtId, int64_t newPtId, void* cellPointIds) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ReplaceCellPoint(cellId, oldPtId, newPtId, static_cast<vtkIdList*>(cellPointIds));
}

extern "C" void vtkPolyData__ReverseCell__0(void* self, int64_t cellId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ReverseCell(cellId);
}

extern "C" void vtkPolyData__DeletePoint__0(void* self, int64_t ptId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->DeletePoint(ptId);
}

extern "C" void vtkPolyData__DeleteCell__0(void* self, int64_t cellId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->DeleteCell(cellId);
}

extern "C" void vtkPolyData__RemoveDeletedCells__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->RemoveDeletedCells();
}

extern "C" int64_t vtkPolyData__InsertNextLinkedPoint__0(void* self, int32_t numLinks) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->InsertNextLinkedPoint(numLinks);
}

extern "C" int64_t vtkPolyData__InsertNextLinkedPoint__1(void* self, double* x, int32_t numLinks) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->InsertNextLinkedPoint(x, numLinks);
}

extern "C" int64_t vtkPolyData__InsertNextLinkedCell__0(void* self, int32_t type_, int32_t npts, const int64_t* pts) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->InsertNextLinkedCell(type_, npts, pts);
}

extern "C" void vtkPolyData__ReplaceLinkedCell__0(void* self, int64_t cellId, int32_t npts, const int64_t* pts) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ReplaceLinkedCell(cellId, npts, pts);
}

extern "C" void vtkPolyData__RemoveCellReference__0(void* self, int64_t cellId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->RemoveCellReference(cellId);
}

extern "C" void vtkPolyData__AddCellReference__0(void* self, int64_t cellId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->AddCellReference(cellId);
}

extern "C" void vtkPolyData__RemoveReferenceToCell__0(void* self, int64_t ptId, int64_t cellId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->RemoveReferenceToCell(ptId, cellId);
}

extern "C" void vtkPolyData__AddReferenceToCell__0(void* self, int64_t ptId, int64_t cellId) {
  (void)self;
  static_cast<vtkPolyData*>(self)->AddReferenceToCell(ptId, cellId);
}

extern "C" void vtkPolyData__ResizeCellList__0(void* self, int64_t ptId, int32_t size) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ResizeCellList(ptId, size);
}

extern "C" void vtkPolyData__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->Initialize();
}

extern "C" int32_t vtkPolyData__GetPiece__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetPiece();
}

extern "C" int32_t vtkPolyData__GetNumberOfPieces__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetNumberOfPieces();
}

extern "C" int32_t vtkPolyData__GetGhostLevel__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetGhostLevel();
}

extern "C" unsigned long vtkPolyData__GetActualMemorySize__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetActualMemorySize();
}

extern "C" void vtkPolyData__ShallowCopy__0(void* self, void* src) {
  (void)self;
  static_cast<vtkPolyData*>(self)->ShallowCopy(static_cast<vtkDataObject*>(src));
}

extern "C" void vtkPolyData__DeepCopy__0(void* self, void* src) {
  (void)self;
  static_cast<vtkPolyData*>(self)->DeepCopy(static_cast<vtkDataObject*>(src));
}

extern "C" void vtkPolyData__RemoveGhostCells__0(void* self) {
  (void)self;
  static_cast<vtkPolyData*>(self)->RemoveGhostCells();
}

extern "C" void* vtkPolyData__GetData__0(void* info) {
  return static_cast<void*>(vtkPolyData::GetData(static_cast<vtkInformation*>(info)));
}

extern "C" void* vtkPolyData__GetData__1(void* v, int32_t i) {
  return static_cast<void*>(vtkPolyData::GetData(static_cast<vtkInformationVector*>(v), i));
}

extern "C" int32_t vtkPolyData__GetScalarFieldCriticalIndex__0(void* self, int64_t pointId, void* scalarField) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetScalarFieldCriticalIndex(pointId, static_cast<vtkDataArray*>(scalarField));
}

extern "C" int32_t vtkPolyData__GetScalarFieldCriticalIndex__1(void* self, int64_t pointId, int32_t fieldId) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetScalarFieldCriticalIndex(pointId, fieldId);
}

extern "C" int32_t vtkPolyData__GetScalarFieldCriticalIndex__2(void* self, int64_t pointId, const char* fieldName) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetScalarFieldCriticalIndex(pointId, fieldName);
}

extern "C" unsigned long vtkPolyData__GetMeshMTime__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetMeshMTime();
}

extern "C" unsigned long vtkPolyData__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkPolyData*>(self)->GetMTime();
}

