// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkQuadricDecimation.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkQuadricDecimation__rvtk_new() { return static_cast<void*>(vtkQuadricDecimation::New()); }

extern "C" int32_t vtkQuadricDecimation__IsTypeOf__0(const char* type_) {
  return vtkQuadricDecimation::IsTypeOf(type_);
}

extern "C" int32_t vtkQuadricDecimation__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->IsA(type_);
}

extern "C" void* vtkQuadricDecimation__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkQuadricDecimation::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkQuadricDecimation__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkQuadricDecimation::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkQuadricDecimation__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkQuadricDecimation__SetTargetReduction__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetTargetReduction(_arg);
}

extern "C" double vtkQuadricDecimation__GetTargetReductionMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTargetReductionMinValue();
}

extern "C" double vtkQuadricDecimation__GetTargetReductionMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTargetReductionMaxValue();
}

extern "C" double vtkQuadricDecimation__GetTargetReduction__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTargetReduction();
}

extern "C" void vtkQuadricDecimation__SetAttributeErrorMetric__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetAttributeErrorMetric(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetAttributeErrorMetric__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetAttributeErrorMetric();
}

extern "C" void vtkQuadricDecimation__AttributeErrorMetricOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->AttributeErrorMetricOn();
}

extern "C" void vtkQuadricDecimation__AttributeErrorMetricOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->AttributeErrorMetricOff();
}

extern "C" void vtkQuadricDecimation__SetVolumePreservation__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetVolumePreservation(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetVolumePreservation__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetVolumePreservation();
}

extern "C" void vtkQuadricDecimation__VolumePreservationOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->VolumePreservationOn();
}

extern "C" void vtkQuadricDecimation__VolumePreservationOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->VolumePreservationOff();
}

extern "C" void vtkQuadricDecimation__SetMaximumError__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetMaximumError(_arg);
}

extern "C" double vtkQuadricDecimation__GetMaximumError__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetMaximumError();
}

extern "C" void vtkQuadricDecimation__SetRegularize__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetRegularize(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetRegularize__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetRegularize();
}

extern "C" void vtkQuadricDecimation__RegularizeOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->RegularizeOn();
}

extern "C" void vtkQuadricDecimation__RegularizeOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->RegularizeOff();
}

extern "C" void vtkQuadricDecimation__SetRegularization__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetRegularization(_arg);
}

extern "C" double vtkQuadricDecimation__GetRegularization__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetRegularization();
}

extern "C" void vtkQuadricDecimation__SetWeighBoundaryConstraintsByLength__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetWeighBoundaryConstraintsByLength(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetWeighBoundaryConstraintsByLength__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetWeighBoundaryConstraintsByLength();
}

extern "C" void vtkQuadricDecimation__WeighBoundaryConstraintsByLengthOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->WeighBoundaryConstraintsByLengthOn();
}

extern "C" void vtkQuadricDecimation__WeighBoundaryConstraintsByLengthOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->WeighBoundaryConstraintsByLengthOff();
}

extern "C" void vtkQuadricDecimation__SetBoundaryWeightFactor__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetBoundaryWeightFactor(_arg);
}

extern "C" double vtkQuadricDecimation__GetBoundaryWeightFactor__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetBoundaryWeightFactor();
}

extern "C" bool vtkQuadricDecimation__GetMapPointData__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetMapPointData();
}

extern "C" void vtkQuadricDecimation__SetMapPointData__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetMapPointData(_arg);
}

extern "C" void vtkQuadricDecimation__MapPointDataOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->MapPointDataOn();
}

extern "C" void vtkQuadricDecimation__MapPointDataOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->MapPointDataOff();
}

extern "C" void vtkQuadricDecimation__SetScalarsAttribute__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetScalarsAttribute(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetScalarsAttribute__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetScalarsAttribute();
}

extern "C" void vtkQuadricDecimation__ScalarsAttributeOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->ScalarsAttributeOn();
}

extern "C" void vtkQuadricDecimation__ScalarsAttributeOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->ScalarsAttributeOff();
}

extern "C" void vtkQuadricDecimation__SetVectorsAttribute__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetVectorsAttribute(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetVectorsAttribute__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetVectorsAttribute();
}

extern "C" void vtkQuadricDecimation__VectorsAttributeOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->VectorsAttributeOn();
}

extern "C" void vtkQuadricDecimation__VectorsAttributeOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->VectorsAttributeOff();
}

extern "C" void vtkQuadricDecimation__SetNormalsAttribute__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetNormalsAttribute(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetNormalsAttribute__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetNormalsAttribute();
}

extern "C" void vtkQuadricDecimation__NormalsAttributeOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->NormalsAttributeOn();
}

extern "C" void vtkQuadricDecimation__NormalsAttributeOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->NormalsAttributeOff();
}

extern "C" void vtkQuadricDecimation__SetTCoordsAttribute__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetTCoordsAttribute(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetTCoordsAttribute__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTCoordsAttribute();
}

extern "C" void vtkQuadricDecimation__TCoordsAttributeOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->TCoordsAttributeOn();
}

extern "C" void vtkQuadricDecimation__TCoordsAttributeOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->TCoordsAttributeOff();
}

extern "C" void vtkQuadricDecimation__SetTensorsAttribute__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetTensorsAttribute(_arg);
}

extern "C" int32_t vtkQuadricDecimation__GetTensorsAttribute__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTensorsAttribute();
}

extern "C" void vtkQuadricDecimation__TensorsAttributeOn__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->TensorsAttributeOn();
}

extern "C" void vtkQuadricDecimation__TensorsAttributeOff__0(void* self) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->TensorsAttributeOff();
}

extern "C" void vtkQuadricDecimation__SetScalarsWeight__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetScalarsWeight(_arg);
}

extern "C" void vtkQuadricDecimation__SetVectorsWeight__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetVectorsWeight(_arg);
}

extern "C" void vtkQuadricDecimation__SetNormalsWeight__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetNormalsWeight(_arg);
}

extern "C" void vtkQuadricDecimation__SetTCoordsWeight__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetTCoordsWeight(_arg);
}

extern "C" void vtkQuadricDecimation__SetTensorsWeight__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkQuadricDecimation*>(self)->SetTensorsWeight(_arg);
}

extern "C" double vtkQuadricDecimation__GetScalarsWeight__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetScalarsWeight();
}

extern "C" double vtkQuadricDecimation__GetVectorsWeight__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetVectorsWeight();
}

extern "C" double vtkQuadricDecimation__GetNormalsWeight__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetNormalsWeight();
}

extern "C" double vtkQuadricDecimation__GetTCoordsWeight__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTCoordsWeight();
}

extern "C" double vtkQuadricDecimation__GetTensorsWeight__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetTensorsWeight();
}

extern "C" double vtkQuadricDecimation__GetActualReduction__0(void* self) {
  (void)self;
  return static_cast<vtkQuadricDecimation*>(self)->GetActualReduction();
}

