// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkStructuredCellArray.h"
#include "vtkAbstractCellArray.h"
#include "vtkIdList.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkStructuredCellArray__rvtk_new() { return static_cast<void*>(vtkStructuredCellArray::New()); }

extern "C" int32_t vtkStructuredCellArray__IsTypeOf__0(const char* type_) {
  return vtkStructuredCellArray::IsTypeOf(type_);
}

extern "C" int32_t vtkStructuredCellArray__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->IsA(type_);
}

extern "C" void* vtkStructuredCellArray__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkStructuredCellArray::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkStructuredCellArray__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkStructuredCellArray::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkStructuredCellArray__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkStructuredCellArray__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkStructuredCellArray*>(self)->Initialize();
}

extern "C" int64_t vtkStructuredCellArray__GetNumberOfCells__0(void* self) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetNumberOfCells();
}

extern "C" int64_t vtkStructuredCellArray__GetNumberOfOffsets__0(void* self) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetNumberOfOffsets();
}

extern "C" int64_t vtkStructuredCellArray__GetOffset__0(void* self, int64_t cellId) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetOffset(cellId);
}

extern "C" int64_t vtkStructuredCellArray__GetNumberOfConnectivityIds__0(void* self) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetNumberOfConnectivityIds();
}

extern "C" void vtkStructuredCellArray__SetData__0(void* self, int32_t* extent, bool usePixelVoxelOrientation) {
  (void)self;
  static_cast<vtkStructuredCellArray*>(self)->SetData(extent, usePixelVoxelOrientation);
}

extern "C" bool vtkStructuredCellArray__IsStorageShareable__0(void* self) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->IsStorageShareable();
}

extern "C" int64_t vtkStructuredCellArray__IsHomogeneous__0(void* self) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->IsHomogeneous();
}

extern "C" void vtkStructuredCellArray__GetCellAtId__0(void* self, int64_t cellId, void* ptIds) {
  (void)self;
  static_cast<vtkStructuredCellArray*>(self)->GetCellAtId(cellId, static_cast<vtkIdList*>(ptIds));
}

extern "C" void vtkStructuredCellArray__GetCellAtId__1(void* self, int32_t* ijk, void* ptIds) {
  (void)self;
  static_cast<vtkStructuredCellArray*>(self)->GetCellAtId(ijk, static_cast<vtkIdList*>(ptIds));
}

extern "C" int64_t vtkStructuredCellArray__GetCellSize__0(void* self, int64_t cellId) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetCellSize(cellId);
}

extern "C" int32_t vtkStructuredCellArray__GetMaxCellSize__0(void* self) {
  (void)self;
  return static_cast<vtkStructuredCellArray*>(self)->GetMaxCellSize();
}

extern "C" void vtkStructuredCellArray__DeepCopy__0(void* self, void* ca) {
  (void)self;
  static_cast<vtkStructuredCellArray*>(self)->DeepCopy(static_cast<vtkAbstractCellArray*>(ca));
}

extern "C" void vtkStructuredCellArray__ShallowCopy__0(void* self, void* ca) {
  (void)self;
  static_cast<vtkStructuredCellArray*>(self)->ShallowCopy(static_cast<vtkAbstractCellArray*>(ca));
}

