// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkTableBasedClipDataSet.h"
#include "vtkImplicitFunction.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkObjectBase.h"
#include "vtkUnstructuredGrid.h"
#include <string>

extern "C" void* vtkTableBasedClipDataSet__rvtk_new() { return static_cast<void*>(vtkTableBasedClipDataSet::New()); }

extern "C" int32_t vtkTableBasedClipDataSet__IsTypeOf__0(const char* type_) {
  return vtkTableBasedClipDataSet::IsTypeOf(type_);
}

extern "C" int32_t vtkTableBasedClipDataSet__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->IsA(type_);
}

extern "C" void* vtkTableBasedClipDataSet__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkTableBasedClipDataSet::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkTableBasedClipDataSet__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkTableBasedClipDataSet::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkTableBasedClipDataSet__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" unsigned long vtkTableBasedClipDataSet__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetMTime();
}

extern "C" void vtkTableBasedClipDataSet__SetInsideOut__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetInsideOut(_arg);
}

extern "C" int32_t vtkTableBasedClipDataSet__GetInsideOut__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetInsideOut();
}

extern "C" void vtkTableBasedClipDataSet__InsideOutOn__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->InsideOutOn();
}

extern "C" void vtkTableBasedClipDataSet__InsideOutOff__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->InsideOutOff();
}

extern "C" void vtkTableBasedClipDataSet__SetValue__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetValue(_arg);
}

extern "C" double vtkTableBasedClipDataSet__GetValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetValue();
}

extern "C" void vtkTableBasedClipDataSet__SetUseValueAsOffset__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetUseValueAsOffset(_arg);
}

extern "C" bool vtkTableBasedClipDataSet__GetUseValueAsOffset__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetUseValueAsOffset();
}

extern "C" void vtkTableBasedClipDataSet__UseValueAsOffsetOn__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->UseValueAsOffsetOn();
}

extern "C" void vtkTableBasedClipDataSet__UseValueAsOffsetOff__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->UseValueAsOffsetOff();
}

extern "C" void vtkTableBasedClipDataSet__SetClipFunction__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetClipFunction(static_cast<vtkImplicitFunction*>(arg0));
}

extern "C" void* vtkTableBasedClipDataSet__GetClipFunction__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTableBasedClipDataSet*>(self)->GetClipFunction());
}

extern "C" void vtkTableBasedClipDataSet__SetGenerateClipScalars__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetGenerateClipScalars(_arg);
}

extern "C" int32_t vtkTableBasedClipDataSet__GetGenerateClipScalars__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetGenerateClipScalars();
}

extern "C" void vtkTableBasedClipDataSet__GenerateClipScalarsOn__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->GenerateClipScalarsOn();
}

extern "C" void vtkTableBasedClipDataSet__GenerateClipScalarsOff__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->GenerateClipScalarsOff();
}

extern "C" void vtkTableBasedClipDataSet__SetGenerateClipPointTypes__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetGenerateClipPointTypes(_arg);
}

extern "C" bool vtkTableBasedClipDataSet__GetGenerateClipPointTypes__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetGenerateClipPointTypes();
}

extern "C" void vtkTableBasedClipDataSet__GenerateClipPointTypesOn__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->GenerateClipPointTypesOn();
}

extern "C" void vtkTableBasedClipDataSet__GenerateClipPointTypesOff__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->GenerateClipPointTypesOff();
}

extern "C" const char* vtkTableBasedClipDataSet__GetPointTypesArrayName__0() {
  return vtkTableBasedClipDataSet::GetPointTypesArrayName();
}

extern "C" void vtkTableBasedClipDataSet__SetMergeTolerance__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetMergeTolerance(_arg);
}

extern "C" double vtkTableBasedClipDataSet__GetMergeToleranceMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetMergeToleranceMinValue();
}

extern "C" double vtkTableBasedClipDataSet__GetMergeToleranceMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetMergeToleranceMaxValue();
}

extern "C" double vtkTableBasedClipDataSet__GetMergeTolerance__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetMergeTolerance();
}

extern "C" void vtkTableBasedClipDataSet__SetGenerateClippedOutput__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetGenerateClippedOutput(_arg);
}

extern "C" int32_t vtkTableBasedClipDataSet__GetGenerateClippedOutput__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetGenerateClippedOutput();
}

extern "C" void vtkTableBasedClipDataSet__GenerateClippedOutputOn__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->GenerateClippedOutputOn();
}

extern "C" void vtkTableBasedClipDataSet__GenerateClippedOutputOff__0(void* self) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->GenerateClippedOutputOff();
}

extern "C" void* vtkTableBasedClipDataSet__GetClippedOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTableBasedClipDataSet*>(self)->GetClippedOutput());
}

extern "C" void vtkTableBasedClipDataSet__SetOutputPointsPrecision__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetOutputPointsPrecision(_arg);
}

extern "C" int32_t vtkTableBasedClipDataSet__GetOutputPointsPrecisionMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetOutputPointsPrecisionMinValue();
}

extern "C" int32_t vtkTableBasedClipDataSet__GetOutputPointsPrecisionMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetOutputPointsPrecisionMaxValue();
}

extern "C" int32_t vtkTableBasedClipDataSet__GetOutputPointsPrecision__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetOutputPointsPrecision();
}

extern "C" void vtkTableBasedClipDataSet__SetBatchSize__0(void* self, uint32_t _arg) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetBatchSize(_arg);
}

extern "C" uint32_t vtkTableBasedClipDataSet__GetBatchSizeMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetBatchSizeMinValue();
}

extern "C" uint32_t vtkTableBasedClipDataSet__GetBatchSizeMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetBatchSizeMaxValue();
}

extern "C" uint32_t vtkTableBasedClipDataSet__GetBatchSize__0(void* self) {
  (void)self;
  return static_cast<vtkTableBasedClipDataSet*>(self)->GetBatchSize();
}

extern "C" void vtkTableBasedClipDataSet__SetLocator__0(void* self, void* locator) {
  (void)self;
  static_cast<vtkTableBasedClipDataSet*>(self)->SetLocator(static_cast<vtkIncrementalPointLocator*>(locator));
}

extern "C" void* vtkTableBasedClipDataSet__GetLocator__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTableBasedClipDataSet*>(self)->GetLocator());
}

