// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkUnstructuredGridGeometryFilter.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkUnstructuredGridGeometryFilter__rvtk_new() { return static_cast<void*>(vtkUnstructuredGridGeometryFilter::New()); }

extern "C" int32_t vtkUnstructuredGridGeometryFilter__IsTypeOf__0(const char* type_) {
  return vtkUnstructuredGridGeometryFilter::IsTypeOf(type_);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->IsA(type_);
}

extern "C" void* vtkUnstructuredGridGeometryFilter__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkUnstructuredGridGeometryFilter::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkUnstructuredGridGeometryFilter::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetPointClipping__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetPointClipping(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetPointClipping__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointClipping();
}

extern "C" void vtkUnstructuredGridGeometryFilter__PointClippingOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->PointClippingOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__PointClippingOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->PointClippingOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetCellClipping__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetCellClipping(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetCellClipping__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellClipping();
}

extern "C" void vtkUnstructuredGridGeometryFilter__CellClippingOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->CellClippingOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__CellClippingOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->CellClippingOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetExtentClipping__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetExtentClipping(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetExtentClipping__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetExtentClipping();
}

extern "C" void vtkUnstructuredGridGeometryFilter__ExtentClippingOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->ExtentClippingOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__ExtentClippingOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->ExtentClippingOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetDuplicateGhostCellClipping__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetDuplicateGhostCellClipping(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetDuplicateGhostCellClipping__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetDuplicateGhostCellClipping();
}

extern "C" void vtkUnstructuredGridGeometryFilter__DuplicateGhostCellClippingOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->DuplicateGhostCellClippingOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__DuplicateGhostCellClippingOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->DuplicateGhostCellClippingOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetPointMinimum__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetPointMinimum(_arg);
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetPointMinimumMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointMinimumMinValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetPointMinimumMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointMinimumMaxValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetPointMinimum__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointMinimum();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetPointMaximum__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetPointMaximum(_arg);
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetPointMaximumMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointMaximumMinValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetPointMaximumMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointMaximumMaxValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetPointMaximum__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPointMaximum();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetCellMinimum__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetCellMinimum(_arg);
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetCellMinimumMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellMinimumMinValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetCellMinimumMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellMinimumMaxValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetCellMinimum__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellMinimum();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetCellMaximum__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetCellMaximum(_arg);
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetCellMaximumMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellMaximumMinValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetCellMaximumMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellMaximumMaxValue();
}

extern "C" int64_t vtkUnstructuredGridGeometryFilter__GetCellMaximum__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetCellMaximum();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetExtent__0(void* self, double xMin, double xMax, double yMin, double yMax, double zMin, double zMax) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetExtent(xMin, xMax, yMin, yMax, zMin, zMax);
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetExtent__1(void* self, double* extent) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetExtent(extent);
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetMerging__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetMerging(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetMerging__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetMerging();
}

extern "C" void vtkUnstructuredGridGeometryFilter__MergingOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->MergingOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__MergingOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->MergingOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetPassThroughCellIds__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetPassThroughCellIds(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetPassThroughCellIds__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPassThroughCellIds();
}

extern "C" void vtkUnstructuredGridGeometryFilter__PassThroughCellIdsOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->PassThroughCellIdsOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__PassThroughCellIdsOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->PassThroughCellIdsOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetPassThroughPointIds__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetPassThroughPointIds(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetPassThroughPointIds__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetPassThroughPointIds();
}

extern "C" void vtkUnstructuredGridGeometryFilter__PassThroughPointIdsOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->PassThroughPointIdsOn();
}

extern "C" void vtkUnstructuredGridGeometryFilter__PassThroughPointIdsOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->PassThroughPointIdsOff();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetMatchBoundariesIgnoringCellOrder__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetMatchBoundariesIgnoringCellOrder(_arg);
}

extern "C" int32_t vtkUnstructuredGridGeometryFilter__GetMatchBoundariesIgnoringCellOrder__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetMatchBoundariesIgnoringCellOrder();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetOriginalCellIdsName__0(void* self, const char* _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetOriginalCellIdsName(_arg);
}

extern "C" const char* vtkUnstructuredGridGeometryFilter__GetOriginalCellIdsName__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetOriginalCellIdsName();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetOriginalPointIdsName__0(void* self, const char* _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetOriginalPointIdsName(_arg);
}

extern "C" const char* vtkUnstructuredGridGeometryFilter__GetOriginalPointIdsName__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetOriginalPointIdsName();
}

extern "C" void vtkUnstructuredGridGeometryFilter__SetLocator__0(void* self, void* locator) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->SetLocator(static_cast<vtkIncrementalPointLocator*>(locator));
}

extern "C" void* vtkUnstructuredGridGeometryFilter__GetLocator__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetLocator());
}

extern "C" void vtkUnstructuredGridGeometryFilter__CreateDefaultLocator__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridGeometryFilter*>(self)->CreateDefaultLocator();
}

extern "C" unsigned long vtkUnstructuredGridGeometryFilter__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridGeometryFilter*>(self)->GetMTime();
}

