// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkUniformGridAMRAlgorithm.h"
#include "vtkDataObject.h"
#include "vtkObjectBase.h"
#include "vtkUniformGridAMR.h"
#include <string>

extern "C" void* vtkUniformGridAMRAlgorithm__rvtk_new() { return static_cast<void*>(vtkUniformGridAMRAlgorithm::New()); }

extern "C" int32_t vtkUniformGridAMRAlgorithm__IsTypeOf__0(const char* type_) {
  return vtkUniformGridAMRAlgorithm::IsTypeOf(type_);
}

extern "C" int32_t vtkUniformGridAMRAlgorithm__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUniformGridAMRAlgorithm*>(self)->IsA(type_);
}

extern "C" void* vtkUniformGridAMRAlgorithm__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkUniformGridAMRAlgorithm::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkUniformGridAMRAlgorithm__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkUniformGridAMRAlgorithm::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkUniformGridAMRAlgorithm__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUniformGridAMRAlgorithm*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkUniformGridAMRAlgorithm__GetOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkUniformGridAMRAlgorithm*>(self)->GetOutput());
}

extern "C" void* vtkUniformGridAMRAlgorithm__GetOutput__1(void* self, int32_t arg0) {
  (void)self;
  return static_cast<void*>(static_cast<vtkUniformGridAMRAlgorithm*>(self)->GetOutput(arg0));
}

extern "C" void vtkUniformGridAMRAlgorithm__SetInputData__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkUniformGridAMRAlgorithm*>(self)->SetInputData(static_cast<vtkDataObject*>(arg0));
}

extern "C" void vtkUniformGridAMRAlgorithm__SetInputData__1(void* self, int32_t arg0, void* arg1) {
  (void)self;
  static_cast<vtkUniformGridAMRAlgorithm*>(self)->SetInputData(arg0, static_cast<vtkDataObject*>(arg1));
}

