// Generated by vtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkUniformHyperTreeGridSource.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkUniformHyperTreeGridSource__rvtk_new() { return static_cast<void*>(vtkUniformHyperTreeGridSource::New()); }

extern "C" int32_t vtkUniformHyperTreeGridSource__IsTypeOf__0(const char* type_) {
  return vtkUniformHyperTreeGridSource::IsTypeOf(type_);
}

extern "C" int32_t vtkUniformHyperTreeGridSource__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUniformHyperTreeGridSource*>(self)->IsA(type_);
}

extern "C" void* vtkUniformHyperTreeGridSource__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkUniformHyperTreeGridSource::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkUniformHyperTreeGridSource__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkUniformHyperTreeGridSource::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkUniformHyperTreeGridSource__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUniformHyperTreeGridSource*>(self)->GetNumberOfGenerationsFromBase(type_);
}

