// Generated by rvtk-gen. Do not edit.
// Crash-safety checks for the `vtkCommonTransforms` VTK module.

use vtk::*;

#[inline(never)]
fn section_0() {
    check!("vtkAbstractTransform::is_type_of", || { assert_eq!(vtkAbstractTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkCylindricalTransform::is_type_of", || { assert_eq!(vtkCylindricalTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkGeneralTransform::is_type_of", || { assert_eq!(vtkGeneralTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkHomogeneousTransform::is_type_of", || { assert_eq!(vtkHomogeneousTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkIdentityTransform::is_type_of", || { assert_eq!(vtkIdentityTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkLandmarkTransform::is_type_of", || { assert_eq!(vtkLandmarkTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkLinearTransform::is_type_of", || { assert_eq!(vtkLinearTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkMatrixToHomogeneousTransform::is_type_of", || { assert_eq!(vtkMatrixToHomogeneousTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkMatrixToLinearTransform::is_type_of", || { assert_eq!(vtkMatrixToLinearTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkPerspectiveTransform::is_type_of", || { assert_eq!(vtkPerspectiveTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkSphericalTransform::is_type_of", || { assert_eq!(vtkSphericalTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkThinPlateSplineTransform::is_type_of", || { assert_eq!(vtkThinPlateSplineTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkTransform::is_type_of", || { assert_eq!(vtkTransform::is_type_of("vtkObjectBase"), 1); });
    check!("vtkTransform2D::is_type_of", || { assert_eq!(vtkTransform2D::is_type_of("vtkObjectBase"), 1); });
    check!("vtkTransformCollection::is_type_of", || { assert_eq!(vtkTransformCollection::is_type_of("vtkObjectBase"), 1); });
    check!("vtkWarpTransform::is_type_of", || { assert_eq!(vtkWarpTransform::is_type_of("vtkObjectBase"), 1); });
}

#[inline(never)]
fn section_1() {
    check!("vtkCylindricalTransform::new", || {
        let Some(a) = vtkCylindricalTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkCylindricalTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkCylindricalTransform") == 1 || a.get_class_name().ends_with("vtkCylindricalTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkGeneralTransform::new", || {
        let Some(a) = vtkGeneralTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkGeneralTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkGeneralTransform") == 1 || a.get_class_name().ends_with("vtkGeneralTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkIdentityTransform::new", || {
        let Some(a) = vtkIdentityTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkIdentityTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkIdentityTransform") == 1 || a.get_class_name().ends_with("vtkIdentityTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkLandmarkTransform::new", || {
        let Some(a) = vtkLandmarkTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkLandmarkTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkLandmarkTransform") == 1 || a.get_class_name().ends_with("vtkLandmarkTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkMatrixToHomogeneousTransform::new", || {
        let Some(a) = vtkMatrixToHomogeneousTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkMatrixToHomogeneousTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkMatrixToHomogeneousTransform") == 1 || a.get_class_name().ends_with("vtkMatrixToHomogeneousTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkMatrixToLinearTransform::new", || {
        let Some(a) = vtkMatrixToLinearTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkMatrixToLinearTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkMatrixToLinearTransform") == 1 || a.get_class_name().ends_with("vtkMatrixToLinearTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkPerspectiveTransform::new", || {
        let Some(a) = vtkPerspectiveTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkPerspectiveTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkPerspectiveTransform") == 1 || a.get_class_name().ends_with("vtkPerspectiveTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkSphericalTransform::new", || {
        let Some(a) = vtkSphericalTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkSphericalTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkSphericalTransform") == 1 || a.get_class_name().ends_with("vtkSphericalTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkThinPlateSplineTransform::new", || {
        let Some(a) = vtkThinPlateSplineTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkThinPlateSplineTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkThinPlateSplineTransform") == 1 || a.get_class_name().ends_with("vtkThinPlateSplineTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkTransform::new", || {
        let Some(a) = vtkTransform::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkTransform");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkTransform") == 1 || a.get_class_name().ends_with("vtkTransform"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkTransform2D::new", || {
        let Some(a) = vtkTransform2D::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkTransform2D");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkTransform2D") == 1 || a.get_class_name().ends_with("vtkTransform2D"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkTransformCollection::new", || {
        let Some(a) = vtkTransformCollection::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkTransformCollection");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkTransformCollection") == 1 || a.get_class_name().ends_with("vtkTransformCollection"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkGeneralTransform", || {
        let Some(a) = vtkGeneralTransform::try_new() else { return; };
        check!("vtkGeneralTransform::get_number_of_concatenated_transforms", || { let _ = a.get_number_of_concatenated_transforms(); });
        check!("vtkGeneralTransform::get_input", || { let _ = a.get_input(); });
        check!("vtkGeneralTransform::get_inverse_flag", || { let _ = a.get_inverse_flag(); });
        check!("vtkGeneralTransform::get_m_time", || { let _ = a.get_m_time(); });
    });
    check!("vtkLandmarkTransform", || {
        let Some(a) = vtkLandmarkTransform::try_new() else { return; };
        check!("vtkLandmarkTransform::get_source_landmarks", || { let _ = a.get_source_landmarks(); });
        check!("vtkLandmarkTransform::get_target_landmarks", || { let _ = a.get_target_landmarks(); });
        check!("vtkLandmarkTransform::get_mode", || { let _ = a.get_mode(); });
        check!("vtkLandmarkTransform::get_mode_as_string", || { let _ = a.get_mode_as_string(); });
        check!("vtkLandmarkTransform::get_m_time", || { let _ = a.get_m_time(); });
    });
    check!("vtkMatrixToHomogeneousTransform", || {
        let Some(a) = vtkMatrixToHomogeneousTransform::try_new() else { return; };
        check!("vtkMatrixToHomogeneousTransform::get_input", || { let _ = a.get_input(); });
        check!("vtkMatrixToHomogeneousTransform::get_m_time", || { let _ = a.get_m_time(); });
    });
    check!("vtkMatrixToLinearTransform", || {
        let Some(a) = vtkMatrixToLinearTransform::try_new() else { return; };
        check!("vtkMatrixToLinearTransform::get_input", || { let _ = a.get_input(); });
        check!("vtkMatrixToLinearTransform::get_m_time", || { let _ = a.get_m_time(); });
    });
}

#[inline(never)]
fn section_2() {
    check!("vtkPerspectiveTransform", || {
        let Some(a) = vtkPerspectiveTransform::try_new() else { return; };
        check!("vtkPerspectiveTransform::get_number_of_concatenated_transforms", || { let _ = a.get_number_of_concatenated_transforms(); });
        check!("vtkPerspectiveTransform::get_input", || { let _ = a.get_input(); });
        check!("vtkPerspectiveTransform::get_inverse_flag", || { let _ = a.get_inverse_flag(); });
        check!("vtkPerspectiveTransform::get_m_time", || { let _ = a.get_m_time(); });
    });
    check!("vtkThinPlateSplineTransform", || {
        let Some(a) = vtkThinPlateSplineTransform::try_new() else { return; };
        check!("vtkThinPlateSplineTransform::get_sigma", || { let _ = a.get_sigma(); });
        check!("vtkThinPlateSplineTransform::get_basis", || { let _ = a.get_basis(); });
        check!("vtkThinPlateSplineTransform::get_basis_as_string", || { let _ = a.get_basis_as_string(); });
        check!("vtkThinPlateSplineTransform::get_source_landmarks", || { let _ = a.get_source_landmarks(); });
        check!("vtkThinPlateSplineTransform::get_target_landmarks", || { let _ = a.get_target_landmarks(); });
        check!("vtkThinPlateSplineTransform::get_m_time", || { let _ = a.get_m_time(); });
        check!("vtkThinPlateSplineTransform::get_regularize_bulk_transform", || { let _ = a.get_regularize_bulk_transform(); });
    });
    check!("vtkTransform", || {
        let Some(a) = vtkTransform::try_new() else { return; };
        check!("vtkTransform::get_number_of_concatenated_transforms", || { let _ = a.get_number_of_concatenated_transforms(); });
        check!("vtkTransform::get_input", || { let _ = a.get_input(); });
        check!("vtkTransform::get_inverse_flag", || { let _ = a.get_inverse_flag(); });
        check!("vtkTransform::get_inverse", || { let _ = a.get_inverse(); });
        check!("vtkTransform::get_m_time", || { let _ = a.get_m_time(); });
    });
    check!("vtkTransform2D", || {
        let Some(a) = vtkTransform2D::try_new() else { return; };
        check!("vtkTransform2D::get_matrix", || { let _ = a.get_matrix(); });
        check!("vtkTransform2D::get_m_time", || { let _ = a.get_m_time(); });
    });
    check!("vtkTransformCollection", || {
        let Some(a) = vtkTransformCollection::try_new() else { return; };
        check!("vtkTransformCollection::get_next_item", || { let _ = a.get_next_item(); });
    });
}

/// Run every check for this module.
pub fn run() {
    section_0();
    section_1();
    section_2();
}
