// Generated by rvtk-gen. Do not edit.
// Crash-safety checks for the `vtkRenderingImage` VTK module.

use vtk::*;

#[inline(never)]
fn section_0() {
    check!("vtkDepthImageToPointCloud::is_type_of", || { assert_eq!(vtkDepthImageToPointCloud::is_type_of("vtkObjectBase"), 1); });
    check!("vtkImageResliceMapper::is_type_of", || { assert_eq!(vtkImageResliceMapper::is_type_of("vtkObjectBase"), 1); });
    check!("vtkImageSliceCollection::is_type_of", || { assert_eq!(vtkImageSliceCollection::is_type_of("vtkObjectBase"), 1); });
    check!("vtkImageStack::is_type_of", || { assert_eq!(vtkImageStack::is_type_of("vtkObjectBase"), 1); });
    check!("vtkDepthImageToPointCloud::new", || {
        let Some(a) = vtkDepthImageToPointCloud::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkDepthImageToPointCloud");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkDepthImageToPointCloud") == 1 || a.get_class_name().ends_with("vtkDepthImageToPointCloud"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkImageResliceMapper::new", || {
        let Some(a) = vtkImageResliceMapper::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkImageResliceMapper");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkImageResliceMapper") == 1 || a.get_class_name().ends_with("vtkImageResliceMapper"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkImageSliceCollection::new", || {
        let Some(a) = vtkImageSliceCollection::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkImageSliceCollection");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkImageSliceCollection") == 1 || a.get_class_name().ends_with("vtkImageSliceCollection"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkImageStack::new", || {
        let Some(a) = vtkImageStack::try_new() else {
            println!("      ({} cannot be instantiated: VTK factory returned null)", "vtkImageStack");
            return;
        };
        assert_eq!(a.is_a("vtkObjectBase"), 1, "not refcounted");
        assert!(a.is_a("vtkImageStack") == 1 || a.get_class_name().ends_with("vtkImageStack"), "class name {:?} does not match the wrapper type", a.get_class_name());
        let before = a.get_reference_count();
        let b = a.clone();
        assert!(b.get_reference_count() > before, "clone did not add a reference");
        drop(b);
        assert_eq!(a.get_reference_count(), before, "drop did not release exactly one reference");
    });
    check!("vtkDepthImageToPointCloud", || {
        let Some(a) = vtkDepthImageToPointCloud::try_new() else { return; };
        check!("vtkDepthImageToPointCloud::get_m_time", || { let _ = a.get_m_time(); });
        check!("vtkDepthImageToPointCloud::get_camera", || { let _ = a.get_camera(); });
        check!("vtkDepthImageToPointCloud::get_cull_near_points", || { let _ = a.get_cull_near_points(); });
        check!("vtkDepthImageToPointCloud::get_cull_far_points", || { let _ = a.get_cull_far_points(); });
        check!("vtkDepthImageToPointCloud::get_produce_color_scalars", || { let _ = a.get_produce_color_scalars(); });
        check!("vtkDepthImageToPointCloud::get_produce_vertex_cell_array", || { let _ = a.get_produce_vertex_cell_array(); });
        check!("vtkDepthImageToPointCloud::get_output_points_precision", || { let _ = a.get_output_points_precision(); });
    });
    check!("vtkImageResliceMapper", || {
        let Some(a) = vtkImageResliceMapper::try_new() else { return; };
        check!("vtkImageResliceMapper::get_slice_plane", || { let _ = a.get_slice_plane(); });
        check!("vtkImageResliceMapper::get_jump_to_nearest_slice", || { let _ = a.get_jump_to_nearest_slice(); });
        check!("vtkImageResliceMapper::get_slab_thickness", || { let _ = a.get_slab_thickness(); });
        check!("vtkImageResliceMapper::get_slab_type_min_value", || { let _ = a.get_slab_type_min_value(); });
        check!("vtkImageResliceMapper::get_slab_type_max_value", || { let _ = a.get_slab_type_max_value(); });
        check!("vtkImageResliceMapper::get_slab_type", || { let _ = a.get_slab_type(); });
        check!("vtkImageResliceMapper::get_slab_type_as_string", || { let _ = a.get_slab_type_as_string(); });
        check!("vtkImageResliceMapper::get_slab_sample_factor_min_value", || { let _ = a.get_slab_sample_factor_min_value(); });
        check!("vtkImageResliceMapper::get_slab_sample_factor_max_value", || { let _ = a.get_slab_sample_factor_max_value(); });
        check!("vtkImageResliceMapper::get_slab_sample_factor", || { let _ = a.get_slab_sample_factor(); });
        check!("vtkImageResliceMapper::get_image_sample_factor_min_value", || { let _ = a.get_image_sample_factor_min_value(); });
        check!("vtkImageResliceMapper::get_image_sample_factor_max_value", || { let _ = a.get_image_sample_factor_max_value(); });
        check!("vtkImageResliceMapper::get_image_sample_factor", || { let _ = a.get_image_sample_factor(); });
        check!("vtkImageResliceMapper::get_auto_adjust_image_quality", || { let _ = a.get_auto_adjust_image_quality(); });
        check!("vtkImageResliceMapper::get_resample_to_screen_pixels", || { let _ = a.get_resample_to_screen_pixels(); });
        check!("vtkImageResliceMapper::get_separate_window_level_operation", || { let _ = a.get_separate_window_level_operation(); });
        check!("vtkImageResliceMapper::get_interpolator", || { let _ = a.get_interpolator(); });
        check!("vtkImageResliceMapper::get_m_time", || { let _ = a.get_m_time(); });
        check!("vtkImageResliceMapper::get_image_reslice", || { let _ = a.get_image_reslice(); });
    });
    check!("vtkImageSliceCollection", || {
        let Some(a) = vtkImageSliceCollection::try_new() else { return; };
        check!("vtkImageSliceCollection::get_next_image", || { let _ = a.get_next_image(); });
        check!("vtkImageSliceCollection::get_next_item", || { let _ = a.get_next_item(); });
    });
    check!("vtkImageStack", || {
        let Some(a) = vtkImageStack::try_new() else { return; };
        check!("vtkImageStack::get_images", || { let _ = a.get_images(); });
        check!("vtkImageStack::get_active_layer", || { let _ = a.get_active_layer(); });
        check!("vtkImageStack::get_active_image", || { let _ = a.get_active_image(); });
        check!("vtkImageStack::get_mapper", || { let _ = a.get_mapper(); });
        check!("vtkImageStack::get_property", || { let _ = a.get_property(); });
        check!("vtkImageStack::get_m_time", || { let _ = a.get_m_time(); });
        check!("vtkImageStack::get_redraw_m_time", || { let _ = a.get_redraw_m_time(); });
        check!("vtkImageStack::has_translucent_polygonal_geometry", || { let _ = a.has_translucent_polygonal_geometry(); });
        check!("vtkImageStack::get_next_path", || { let _ = a.get_next_path(); });
        check!("vtkImageStack::get_number_of_paths", || { let _ = a.get_number_of_paths(); });
    });
}

/// Run every check for this module.
pub fn run() {
    section_0();
}
