// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkAffineTypeFloat32Array.h"
#include "vtkAbstractArray.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkAffineTypeFloat32Array__rvtk_new() { return static_cast<void*>(vtkAffineTypeFloat32Array::New()); }

extern "C" int32_t vtkAffineTypeFloat32Array__IsTypeOf__0(const char* type_) {
  return vtkAffineTypeFloat32Array::IsTypeOf(type_);
}

extern "C" int32_t vtkAffineTypeFloat32Array__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->IsA(type_);
}

extern "C" void* vtkAffineTypeFloat32Array__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkAffineTypeFloat32Array::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkAffineTypeFloat32Array__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkAffineTypeFloat32Array::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkAffineTypeFloat32Array__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkAffineTypeFloat32Array__ExtendedNew__0() {
  return static_cast<void*>(vtkAffineTypeFloat32Array::ExtendedNew());
}

extern "C" int32_t vtkAffineTypeFloat32Array__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetDataType();
}

extern "C" float vtkAffineTypeFloat32Array__GetDataTypeValueMin__0(void* self) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetDataTypeValueMin();
}

extern "C" float vtkAffineTypeFloat32Array__GetDataTypeValueMax__0(void* self) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetDataTypeValueMax();
}

extern "C" void vtkAffineTypeFloat32Array__GetValueRange__0(void* self, float* range, int32_t comp) {
  (void)self;
  static_cast<vtkAffineTypeFloat32Array*>(self)->GetValueRange(range, comp);
}

extern "C" void vtkAffineTypeFloat32Array__GetValueRange__1(void* self, float* range, int32_t comp) {
  (void)self;
  static_cast<vtkAffineTypeFloat32Array*>(self)->GetValueRange(range, comp);
}

extern "C" float vtkAffineTypeFloat32Array__GetTypedComponent__0(void* self, int64_t i, int32_t c) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetTypedComponent(i, c);
}

extern "C" float vtkAffineTypeFloat32Array__GetValue__0(void* self, int64_t id) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetValue(id);
}

extern "C" bool vtkAffineTypeFloat32Array__SetNumberOfValues__0(void* self, int64_t number) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->SetNumberOfValues(number);
}

extern "C" void vtkAffineTypeFloat32Array__ConstructBackend__0(void* self, float slope, float intercept) {
  (void)self;
  static_cast<vtkAffineTypeFloat32Array*>(self)->ConstructBackend(slope, intercept);
}

extern "C" float vtkAffineTypeFloat32Array__GetSlope__0(void* self) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetSlope();
}

extern "C" float vtkAffineTypeFloat32Array__GetIntercept__0(void* self) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->GetIntercept();
}

extern "C" bool vtkAffineTypeFloat32Array__IsBackendConstructed__0(void* self) {
  (void)self;
  return static_cast<vtkAffineTypeFloat32Array*>(self)->IsBackendConstructed();
}

extern "C" void* vtkAffineTypeFloat32Array__FastDownCast__0(void* source) {
  return static_cast<void*>(vtkAffineTypeFloat32Array::FastDownCast(static_cast<vtkAbstractArray*>(source)));
}

