// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkAbstractContextBufferId.h"
#include "vtkObjectBase.h"
#include "vtkRenderWindow.h"
#include <string>

extern "C" void* vtkAbstractContextBufferId__rvtk_new() { return static_cast<void*>(vtkAbstractContextBufferId::New()); }

extern "C" int32_t vtkAbstractContextBufferId__IsTypeOf__0(const char* type_) {
  return vtkAbstractContextBufferId::IsTypeOf(type_);
}

extern "C" int32_t vtkAbstractContextBufferId__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->IsA(type_);
}

extern "C" void* vtkAbstractContextBufferId__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkAbstractContextBufferId::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkAbstractContextBufferId__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkAbstractContextBufferId::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkAbstractContextBufferId__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkAbstractContextBufferId__GetWidth__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->GetWidth();
}

extern "C" void vtkAbstractContextBufferId__SetWidth__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkAbstractContextBufferId*>(self)->SetWidth(_arg);
}

extern "C" int32_t vtkAbstractContextBufferId__GetHeight__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->GetHeight();
}

extern "C" void vtkAbstractContextBufferId__SetHeight__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkAbstractContextBufferId*>(self)->SetHeight(_arg);
}

extern "C" void vtkAbstractContextBufferId__SetContext__0(void* self, void* context) {
  (void)self;
  static_cast<vtkAbstractContextBufferId*>(self)->SetContext(static_cast<vtkRenderWindow*>(context));
}

extern "C" void* vtkAbstractContextBufferId__GetContext__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkAbstractContextBufferId*>(self)->GetContext());
}

extern "C" bool vtkAbstractContextBufferId__IsSupported__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->IsSupported();
}

extern "C" void vtkAbstractContextBufferId__Allocate__0(void* self) {
  (void)self;
  static_cast<vtkAbstractContextBufferId*>(self)->Allocate();
}

extern "C" bool vtkAbstractContextBufferId__IsAllocated__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->IsAllocated();
}

extern "C" void vtkAbstractContextBufferId__SetValues__0(void* self, int32_t srcXmin, int32_t srcYmin) {
  (void)self;
  static_cast<vtkAbstractContextBufferId*>(self)->SetValues(srcXmin, srcYmin);
}

extern "C" int64_t vtkAbstractContextBufferId__GetPickedItem__0(void* self, int32_t x, int32_t y) {
  (void)self;
  return static_cast<vtkAbstractContextBufferId*>(self)->GetPickedItem(x, y);
}

extern "C" void vtkAbstractContextBufferId__ReleaseGraphicsResources__0(void* self) {
  (void)self;
  static_cast<vtkAbstractContextBufferId*>(self)->ReleaseGraphicsResources();
}

