// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkAffineLongLongArray.h"
#include "vtkAbstractArray.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkAffineLongLongArray__rvtk_new() { return static_cast<void*>(vtkAffineLongLongArray::New()); }

extern "C" int32_t vtkAffineLongLongArray__IsTypeOf__0(const char* type_) {
  return vtkAffineLongLongArray::IsTypeOf(type_);
}

extern "C" int32_t vtkAffineLongLongArray__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->IsA(type_);
}

extern "C" void* vtkAffineLongLongArray__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkAffineLongLongArray::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkAffineLongLongArray__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkAffineLongLongArray::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkAffineLongLongArray__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkAffineLongLongArray__ExtendedNew__0() {
  return static_cast<void*>(vtkAffineLongLongArray::ExtendedNew());
}

extern "C" int32_t vtkAffineLongLongArray__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetDataType();
}

extern "C" int64_t vtkAffineLongLongArray__GetDataTypeValueMin__0(void* self) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetDataTypeValueMin();
}

extern "C" int64_t vtkAffineLongLongArray__GetDataTypeValueMax__0(void* self) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetDataTypeValueMax();
}

extern "C" void vtkAffineLongLongArray__GetValueRange__0(void* self, int64_t* range, int32_t comp) {
  (void)self;
  static_cast<vtkAffineLongLongArray*>(self)->GetValueRange(range, comp);
}

extern "C" void vtkAffineLongLongArray__GetValueRange__1(void* self, int64_t* range, int32_t comp) {
  (void)self;
  static_cast<vtkAffineLongLongArray*>(self)->GetValueRange(range, comp);
}

extern "C" int64_t vtkAffineLongLongArray__GetTypedComponent__0(void* self, int64_t i, int32_t c) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetTypedComponent(i, c);
}

extern "C" int64_t vtkAffineLongLongArray__GetValue__0(void* self, int64_t id) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetValue(id);
}

extern "C" bool vtkAffineLongLongArray__SetNumberOfValues__0(void* self, int64_t number) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->SetNumberOfValues(number);
}

extern "C" void vtkAffineLongLongArray__ConstructBackend__0(void* self, int64_t slope, int64_t intercept) {
  (void)self;
  static_cast<vtkAffineLongLongArray*>(self)->ConstructBackend(slope, intercept);
}

extern "C" int64_t vtkAffineLongLongArray__GetSlope__0(void* self) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetSlope();
}

extern "C" int64_t vtkAffineLongLongArray__GetIntercept__0(void* self) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->GetIntercept();
}

extern "C" bool vtkAffineLongLongArray__IsBackendConstructed__0(void* self) {
  (void)self;
  return static_cast<vtkAffineLongLongArray*>(self)->IsBackendConstructed();
}

extern "C" void* vtkAffineLongLongArray__FastDownCast__0(void* source) {
  return static_cast<void*>(vtkAffineLongLongArray::FastDownCast(static_cast<vtkAbstractArray*>(source)));
}

