// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkBoundedPlanePointPlacer.h"
#include "vtkObjectBase.h"
#include "vtkPlane.h"
#include "vtkPlaneCollection.h"
#include "vtkPlanes.h"
#include "vtkRenderer.h"
#include <string>

extern "C" void* vtkBoundedPlanePointPlacer__rvtk_new() { return static_cast<void*>(vtkBoundedPlanePointPlacer::New()); }

extern "C" int32_t vtkBoundedPlanePointPlacer__IsTypeOf__0(const char* type_) {
  return vtkBoundedPlanePointPlacer::IsTypeOf(type_);
}

extern "C" int32_t vtkBoundedPlanePointPlacer__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->IsA(type_);
}

extern "C" void* vtkBoundedPlanePointPlacer__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkBoundedPlanePointPlacer::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkBoundedPlanePointPlacer__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkBoundedPlanePointPlacer::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkBoundedPlanePointPlacer__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkBoundedPlanePointPlacer__SetProjectionNormal__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetProjectionNormal(_arg);
}

extern "C" int32_t vtkBoundedPlanePointPlacer__GetProjectionNormalMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->GetProjectionNormalMinValue();
}

extern "C" int32_t vtkBoundedPlanePointPlacer__GetProjectionNormalMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->GetProjectionNormalMaxValue();
}

extern "C" int32_t vtkBoundedPlanePointPlacer__GetProjectionNormal__0(void* self) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->GetProjectionNormal();
}

extern "C" void vtkBoundedPlanePointPlacer__SetProjectionNormalToXAxis__0(void* self) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetProjectionNormalToXAxis();
}

extern "C" void vtkBoundedPlanePointPlacer__SetProjectionNormalToYAxis__0(void* self) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetProjectionNormalToYAxis();
}

extern "C" void vtkBoundedPlanePointPlacer__SetProjectionNormalToZAxis__0(void* self) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetProjectionNormalToZAxis();
}

extern "C" void vtkBoundedPlanePointPlacer__SetProjectionNormalToOblique__0(void* self) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetProjectionNormalToOblique();
}

extern "C" void vtkBoundedPlanePointPlacer__SetObliquePlane__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetObliquePlane(static_cast<vtkPlane*>(arg0));
}

extern "C" void* vtkBoundedPlanePointPlacer__GetObliquePlane__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkBoundedPlanePointPlacer*>(self)->GetObliquePlane());
}

extern "C" void vtkBoundedPlanePointPlacer__SetProjectionPosition__0(void* self, double position) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetProjectionPosition(position);
}

extern "C" double vtkBoundedPlanePointPlacer__GetProjectionPosition__0(void* self) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->GetProjectionPosition();
}

extern "C" void vtkBoundedPlanePointPlacer__AddBoundingPlane__0(void* self, void* plane) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->AddBoundingPlane(static_cast<vtkPlane*>(plane));
}

extern "C" void vtkBoundedPlanePointPlacer__RemoveBoundingPlane__0(void* self, void* plane) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->RemoveBoundingPlane(static_cast<vtkPlane*>(plane));
}

extern "C" void vtkBoundedPlanePointPlacer__RemoveAllBoundingPlanes__0(void* self) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->RemoveAllBoundingPlanes();
}

extern "C" void vtkBoundedPlanePointPlacer__SetBoundingPlanes__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetBoundingPlanes(static_cast<vtkPlaneCollection*>(arg0));
}

extern "C" void* vtkBoundedPlanePointPlacer__GetBoundingPlanes__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkBoundedPlanePointPlacer*>(self)->GetBoundingPlanes());
}

extern "C" void vtkBoundedPlanePointPlacer__SetBoundingPlanes__1(void* self, void* planes) {
  (void)self;
  static_cast<vtkBoundedPlanePointPlacer*>(self)->SetBoundingPlanes(static_cast<vtkPlanes*>(planes));
}

extern "C" int32_t vtkBoundedPlanePointPlacer__ComputeWorldPosition__0(void* self, void* ren, double* displayPos, double* worldPos, double* worldOrient) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->ComputeWorldPosition(static_cast<vtkRenderer*>(ren), displayPos, worldPos, worldOrient);
}

extern "C" int32_t vtkBoundedPlanePointPlacer__ComputeWorldPosition__1(void* self, void* ren, double* displayPos, double* refWorldPos, double* worldPos, double* worldOrient) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->ComputeWorldPosition(static_cast<vtkRenderer*>(ren), displayPos, refWorldPos, worldPos, worldOrient);
}

extern "C" int32_t vtkBoundedPlanePointPlacer__ValidateWorldPosition__0(void* self, double* worldPos) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->ValidateWorldPosition(worldPos);
}

extern "C" int32_t vtkBoundedPlanePointPlacer__ValidateWorldPosition__1(void* self, double* worldPos, double* worldOrient) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->ValidateWorldPosition(worldPos, worldOrient);
}

extern "C" int32_t vtkBoundedPlanePointPlacer__UpdateWorldPosition__0(void* self, void* ren, double* worldPos, double* worldOrient) {
  (void)self;
  return static_cast<vtkBoundedPlanePointPlacer*>(self)->UpdateWorldPosition(static_cast<vtkRenderer*>(ren), worldPos, worldOrient);
}

