// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkCompositeDataDisplayAttributes.h"
#include "vtkDataObject.h"
#include "vtkObjectBase.h"
#include "vtkScalarsToColors.h"
#include "vtkTexture.h"
#include <string>

extern "C" void* vtkCompositeDataDisplayAttributes__rvtk_new() { return static_cast<void*>(vtkCompositeDataDisplayAttributes::New()); }

extern "C" int32_t vtkCompositeDataDisplayAttributes__IsTypeOf__0(const char* type_) {
  return vtkCompositeDataDisplayAttributes::IsTypeOf(type_);
}

extern "C" int32_t vtkCompositeDataDisplayAttributes__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->IsA(type_);
}

extern "C" void* vtkCompositeDataDisplayAttributes__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkCompositeDataDisplayAttributes::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkCompositeDataDisplayAttributes__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkCompositeDataDisplayAttributes::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkCompositeDataDisplayAttributes__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockVisibilities__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockVisibilities();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockVisibility__0(void* self, void* data_object, bool visible) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockVisibility(static_cast<vtkDataObject*>(data_object), visible);
}

extern "C" bool vtkCompositeDataDisplayAttributes__GetBlockVisibility__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockVisibility(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockVisibility__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockVisibility(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockVisibility__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockVisibility(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockVisibilities__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockVisibilities();
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockPickabilities__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockPickabilities();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockPickability__0(void* self, void* data_object, bool visible) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockPickability(static_cast<vtkDataObject*>(data_object), visible);
}

extern "C" bool vtkCompositeDataDisplayAttributes__GetBlockPickability__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockPickability(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockPickability__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockPickability(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockPickability__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockPickability(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockPickabilities__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockPickabilities();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockScalarVisibility__0(void* self, void* data_object, bool value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockScalarVisibility(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" bool vtkCompositeDataDisplayAttributes__GetBlockScalarVisibility__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockScalarVisibility(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockScalarVisibility__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockScalarVisibility(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockScalarVisibilities__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockScalarVisibilities();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockScalarVisibility__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockScalarVisibility(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockScalarVisibilities__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockScalarVisibilities();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockUseLookupTableScalarRange__0(void* self, void* data_object, bool value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockUseLookupTableScalarRange(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" bool vtkCompositeDataDisplayAttributes__GetBlockUseLookupTableScalarRange__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockUseLookupTableScalarRange(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockUseLookupTableScalarRange__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockUseLookupTableScalarRange(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockUseLookupTableScalarRanges__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockUseLookupTableScalarRanges();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockUseLookupTableScalarRange__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockUseLookupTableScalarRange(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockUseLookupTableScalarRanges__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockUseLookupTableScalarRanges();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockInterpolateScalarsBeforeMapping__0(void* self, void* data_object, bool value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockInterpolateScalarsBeforeMapping(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" bool vtkCompositeDataDisplayAttributes__GetBlockInterpolateScalarsBeforeMapping__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockInterpolateScalarsBeforeMapping(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockInterpolateScalarsBeforeMapping__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockInterpolateScalarsBeforeMapping(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockInterpolateScalarsBeforeMappings__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockInterpolateScalarsBeforeMappings();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockInterpolateScalarsBeforeMapping__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockInterpolateScalarsBeforeMapping(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockInterpolateScalarsBeforeMappings__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockInterpolateScalarsBeforeMappings();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockColor__0(void* self, void* data_object, const double* color) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockColor(static_cast<vtkDataObject*>(data_object), color);
}

extern "C" void vtkCompositeDataDisplayAttributes__GetBlockColor__0(void* self, void* data_object, double* color) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockColor(static_cast<vtkDataObject*>(data_object), color);
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockColors__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockColors();
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockColor__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockColor(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockColor__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockColor(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockColors__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockColors();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockOpacity__0(void* self, void* data_object, double opacity) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockOpacity(static_cast<vtkDataObject*>(data_object), opacity);
}

extern "C" double vtkCompositeDataDisplayAttributes__GetBlockOpacity__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockOpacity(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockOpacities__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockOpacities();
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockOpacity__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockOpacity(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockOpacity__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockOpacity(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockOpacities__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockOpacities();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockMaterial__0(void* self, void* data_object, const char* material) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockMaterial(static_cast<vtkDataObject*>(data_object), std::string(material));
}

extern "C" char* vtkCompositeDataDisplayAttributes__GetBlockMaterial__0(void* self, void* data_object) {
  (void)self;
  return rvtk_strdup((static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockMaterial(static_cast<vtkDataObject*>(data_object))).c_str());
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockMaterials__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockMaterials();
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockMaterial__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockMaterial(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockMaterial__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockMaterial(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockMaterials__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockMaterials();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockColorMode__0(void* self, void* data_object, int32_t value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockColorMode(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" int32_t vtkCompositeDataDisplayAttributes__GetBlockColorMode__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockColorMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockColorMode__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockColorMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockColorModes__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockColorModes();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockColorMode__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockColorMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockColorModes__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockColorModes();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockScalarMode__0(void* self, void* data_object, int32_t value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockScalarMode(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" int32_t vtkCompositeDataDisplayAttributes__GetBlockScalarMode__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockScalarMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockScalarMode__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockScalarMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockScalarModes__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockScalarModes();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockScalarMode__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockScalarMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockScalarModes__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockScalarModes();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockArrayAccessMode__0(void* self, void* data_object, int32_t value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockArrayAccessMode(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" int32_t vtkCompositeDataDisplayAttributes__GetBlockArrayAccessMode__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockArrayAccessMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayAccessMode__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayAccessMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayAccessModes__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayAccessModes();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayAccessMode__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayAccessMode(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayAccessModes__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayAccessModes();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockArrayComponent__0(void* self, void* data_object, int32_t value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockArrayComponent(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" int32_t vtkCompositeDataDisplayAttributes__GetBlockArrayComponent__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockArrayComponent(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayComponent__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayComponent(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayComponents__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayComponents();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayComponent__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayComponent(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayComponents__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayComponents();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockArrayId__0(void* self, void* data_object, int32_t value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockArrayId(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" int32_t vtkCompositeDataDisplayAttributes__GetBlockArrayId__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockArrayId(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayId__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayId(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayIds__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayIds();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayId__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayId(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayIds__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayIds();
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockScalarRange__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockScalarRange(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockScalarRanges__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockScalarRanges();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockScalarRange__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockScalarRange(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockScalarRanges__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockScalarRanges();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockArrayName__0(void* self, void* data_object, const char* value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockArrayName(static_cast<vtkDataObject*>(data_object), std::string(value));
}

extern "C" char* vtkCompositeDataDisplayAttributes__GetBlockArrayName__0(void* self, void* data_object) {
  (void)self;
  return rvtk_strdup((static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockArrayName(static_cast<vtkDataObject*>(data_object))).c_str());
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayName__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayName(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockArrayNames__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockArrayNames();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayName__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayName(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockArrayNames__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockArrayNames();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockFieldDataTupleId__0(void* self, void* data_object, int64_t value) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockFieldDataTupleId(static_cast<vtkDataObject*>(data_object), value);
}

extern "C" int64_t vtkCompositeDataDisplayAttributes__GetBlockFieldDataTupleId__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockFieldDataTupleId(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockFieldDataTupleId__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockFieldDataTupleId(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockFieldDataTupleIds__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockFieldDataTupleIds();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockFieldDataTupleId__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockFieldDataTupleId(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockFieldDataTupleIds__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockFieldDataTupleIds();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockLookupTable__0(void* self, void* data_object, void* lut) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockLookupTable(static_cast<vtkDataObject*>(data_object), static_cast<vtkScalarsToColors*>(lut));
}

extern "C" void* vtkCompositeDataDisplayAttributes__GetBlockLookupTable__0(void* self, void* data_object) {
  (void)self;
  return static_cast<void*>((static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockLookupTable(static_cast<vtkDataObject*>(data_object))).GetPointer());
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockLookupTable__0(void* self, void* data_object) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockLookupTable(static_cast<vtkDataObject*>(data_object));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockLookupTables__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockLookupTables();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockLookupTable__0(void* self, void* data_object) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockLookupTable(static_cast<vtkDataObject*>(data_object));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockLookupTables__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockLookupTables();
}

extern "C" void vtkCompositeDataDisplayAttributes__SetBlockTexture__0(void* self, void* dataObject, void* texture) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->SetBlockTexture(static_cast<vtkDataObject*>(dataObject), static_cast<vtkTexture*>(texture));
}

extern "C" void* vtkCompositeDataDisplayAttributes__GetBlockTexture__0(void* self, void* dataObject) {
  (void)self;
  return static_cast<void*>((static_cast<vtkCompositeDataDisplayAttributes*>(self)->GetBlockTexture(static_cast<vtkDataObject*>(dataObject))).GetPointer());
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockTexture__0(void* self, void* dataObject) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockTexture(static_cast<vtkDataObject*>(dataObject));
}

extern "C" bool vtkCompositeDataDisplayAttributes__HasBlockTextures__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataDisplayAttributes*>(self)->HasBlockTextures();
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockTexture__0(void* self, void* dataObject) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockTexture(static_cast<vtkDataObject*>(dataObject));
}

extern "C" void vtkCompositeDataDisplayAttributes__RemoveBlockTextures__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataDisplayAttributes*>(self)->RemoveBlockTextures();
}

extern "C" void vtkCompositeDataDisplayAttributes__ComputeVisibleBounds__0(void* cda, void* dobj, double* bounds) {
  vtkCompositeDataDisplayAttributes::ComputeVisibleBounds(static_cast<vtkCompositeDataDisplayAttributes*>(cda), static_cast<vtkDataObject*>(dobj), bounds);
}

extern "C" void* vtkCompositeDataDisplayAttributes__DataObjectFromIndex__0(uint32_t flat_index, void* parent_obj, uint32_t current_flat_index) {
  return static_cast<void*>(vtkCompositeDataDisplayAttributes::DataObjectFromIndex(flat_index, static_cast<vtkDataObject*>(parent_obj), current_flat_index));
}

