// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkClipVolume.h"
#include "vtkImplicitFunction.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkObjectBase.h"
#include "vtkUnstructuredGrid.h"
#include <string>

extern "C" void* vtkClipVolume__rvtk_new() { return static_cast<void*>(vtkClipVolume::New()); }

extern "C" int32_t vtkClipVolume__IsTypeOf__0(const char* type_) {
  return vtkClipVolume::IsTypeOf(type_);
}

extern "C" int32_t vtkClipVolume__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->IsA(type_);
}

extern "C" void* vtkClipVolume__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkClipVolume::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkClipVolume__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkClipVolume::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkClipVolume__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkClipVolume__SetValue__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetValue(_arg);
}

extern "C" double vtkClipVolume__GetValue__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetValue();
}

extern "C" void vtkClipVolume__SetInsideOut__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetInsideOut(_arg);
}

extern "C" int32_t vtkClipVolume__GetInsideOut__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetInsideOut();
}

extern "C" void vtkClipVolume__InsideOutOn__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->InsideOutOn();
}

extern "C" void vtkClipVolume__InsideOutOff__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->InsideOutOff();
}

extern "C" void vtkClipVolume__SetClipFunction__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetClipFunction(static_cast<vtkImplicitFunction*>(arg0));
}

extern "C" void* vtkClipVolume__GetClipFunction__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkClipVolume*>(self)->GetClipFunction());
}

extern "C" void vtkClipVolume__SetGenerateClipScalars__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetGenerateClipScalars(_arg);
}

extern "C" int32_t vtkClipVolume__GetGenerateClipScalars__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetGenerateClipScalars();
}

extern "C" void vtkClipVolume__GenerateClipScalarsOn__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->GenerateClipScalarsOn();
}

extern "C" void vtkClipVolume__GenerateClipScalarsOff__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->GenerateClipScalarsOff();
}

extern "C" void vtkClipVolume__SetGenerateClippedOutput__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetGenerateClippedOutput(_arg);
}

extern "C" int32_t vtkClipVolume__GetGenerateClippedOutput__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetGenerateClippedOutput();
}

extern "C" void vtkClipVolume__GenerateClippedOutputOn__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->GenerateClippedOutputOn();
}

extern "C" void vtkClipVolume__GenerateClippedOutputOff__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->GenerateClippedOutputOff();
}

extern "C" void* vtkClipVolume__GetClippedOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkClipVolume*>(self)->GetClippedOutput());
}

extern "C" void vtkClipVolume__SetMixed3DCellGeneration__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetMixed3DCellGeneration(_arg);
}

extern "C" int32_t vtkClipVolume__GetMixed3DCellGeneration__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetMixed3DCellGeneration();
}

extern "C" void vtkClipVolume__Mixed3DCellGenerationOn__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->Mixed3DCellGenerationOn();
}

extern "C" void vtkClipVolume__Mixed3DCellGenerationOff__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->Mixed3DCellGenerationOff();
}

extern "C" void vtkClipVolume__SetMergeTolerance__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetMergeTolerance(_arg);
}

extern "C" double vtkClipVolume__GetMergeToleranceMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetMergeToleranceMinValue();
}

extern "C" double vtkClipVolume__GetMergeToleranceMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetMergeToleranceMaxValue();
}

extern "C" double vtkClipVolume__GetMergeTolerance__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetMergeTolerance();
}

extern "C" void vtkClipVolume__SetLocator__0(void* self, void* locator) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->SetLocator(static_cast<vtkIncrementalPointLocator*>(locator));
}

extern "C" void* vtkClipVolume__GetLocator__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkClipVolume*>(self)->GetLocator());
}

extern "C" void vtkClipVolume__CreateDefaultLocator__0(void* self) {
  (void)self;
  static_cast<vtkClipVolume*>(self)->CreateDefaultLocator();
}

extern "C" unsigned long vtkClipVolume__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkClipVolume*>(self)->GetMTime();
}

