// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkCameraActor.h"
#include "vtkCamera.h"
#include "vtkObjectBase.h"
#include "vtkProperty.h"
#include "vtkViewport.h"
#include "vtkWindow.h"
#include <string>

extern "C" void* vtkCameraActor__rvtk_new() { return static_cast<void*>(vtkCameraActor::New()); }

extern "C" int32_t vtkCameraActor__IsTypeOf__0(const char* type_) {
  return vtkCameraActor::IsTypeOf(type_);
}

extern "C" int32_t vtkCameraActor__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCameraActor*>(self)->IsA(type_);
}

extern "C" void* vtkCameraActor__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkCameraActor::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkCameraActor__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkCameraActor::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkCameraActor__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCameraActor*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkCameraActor__SetCamera__0(void* self, void* camera) {
  (void)self;
  static_cast<vtkCameraActor*>(self)->SetCamera(static_cast<vtkCamera*>(camera));
}

extern "C" void* vtkCameraActor__GetCamera__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkCameraActor*>(self)->GetCamera());
}

extern "C" void vtkCameraActor__SetWidthByHeightRatio__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkCameraActor*>(self)->SetWidthByHeightRatio(_arg);
}

extern "C" double vtkCameraActor__GetWidthByHeightRatio__0(void* self) {
  (void)self;
  return static_cast<vtkCameraActor*>(self)->GetWidthByHeightRatio();
}

extern "C" int32_t vtkCameraActor__RenderOpaqueGeometry__0(void* self, void* viewport) {
  (void)self;
  return static_cast<vtkCameraActor*>(self)->RenderOpaqueGeometry(static_cast<vtkViewport*>(viewport));
}

extern "C" int32_t vtkCameraActor__HasTranslucentPolygonalGeometry__0(void* self) {
  (void)self;
  return static_cast<vtkCameraActor*>(self)->HasTranslucentPolygonalGeometry();
}

extern "C" void vtkCameraActor__ReleaseGraphicsResources__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkCameraActor*>(self)->ReleaseGraphicsResources(static_cast<vtkWindow*>(arg0));
}

extern "C" unsigned long vtkCameraActor__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkCameraActor*>(self)->GetMTime();
}

extern "C" void* vtkCameraActor__GetProperty__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkCameraActor*>(self)->GetProperty());
}

extern "C" void vtkCameraActor__SetProperty__0(void* self, void* p) {
  (void)self;
  static_cast<vtkCameraActor*>(self)->SetProperty(static_cast<vtkProperty*>(p));
}

