// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkConstantSignedCharArray.h"
#include "vtkAbstractArray.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkConstantSignedCharArray__rvtk_new() { return static_cast<void*>(vtkConstantSignedCharArray::New()); }

extern "C" int32_t vtkConstantSignedCharArray__IsTypeOf__0(const char* type_) {
  return vtkConstantSignedCharArray::IsTypeOf(type_);
}

extern "C" int32_t vtkConstantSignedCharArray__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->IsA(type_);
}

extern "C" void* vtkConstantSignedCharArray__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkConstantSignedCharArray::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkConstantSignedCharArray__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkConstantSignedCharArray::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkConstantSignedCharArray__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkConstantSignedCharArray__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetDataType();
}

extern "C" int8_t vtkConstantSignedCharArray__GetDataTypeValueMin__0(void* self) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetDataTypeValueMin();
}

extern "C" int8_t vtkConstantSignedCharArray__GetDataTypeValueMax__0(void* self) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetDataTypeValueMax();
}

extern "C" void vtkConstantSignedCharArray__GetValueRange__0(void* self, int8_t* range, int32_t comp) {
  (void)self;
  static_cast<vtkConstantSignedCharArray*>(self)->GetValueRange(range, comp);
}

extern "C" void vtkConstantSignedCharArray__GetValueRange__1(void* self, int8_t* range, int32_t comp) {
  (void)self;
  static_cast<vtkConstantSignedCharArray*>(self)->GetValueRange(range, comp);
}

extern "C" int8_t vtkConstantSignedCharArray__GetTypedComponent__0(void* self, int64_t i, int32_t c) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetTypedComponent(i, c);
}

extern "C" int8_t vtkConstantSignedCharArray__GetValue__0(void* self, int64_t id) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetValue(id);
}

extern "C" bool vtkConstantSignedCharArray__SetNumberOfValues__0(void* self, int64_t number) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->SetNumberOfValues(number);
}

extern "C" void vtkConstantSignedCharArray__ConstructBackend__0(void* self, int8_t value) {
  (void)self;
  static_cast<vtkConstantSignedCharArray*>(self)->ConstructBackend(value);
}

extern "C" int8_t vtkConstantSignedCharArray__GetConstantValue__0(void* self) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->GetConstantValue();
}

extern "C" bool vtkConstantSignedCharArray__IsBackendConstructed__0(void* self) {
  (void)self;
  return static_cast<vtkConstantSignedCharArray*>(self)->IsBackendConstructed();
}

extern "C" void* vtkConstantSignedCharArray__ExtendedNew__0() {
  return static_cast<void*>(vtkConstantSignedCharArray::ExtendedNew());
}

extern "C" void* vtkConstantSignedCharArray__FastDownCast__0(void* source) {
  return static_cast<void*>(vtkConstantSignedCharArray::FastDownCast(static_cast<vtkAbstractArray*>(source)));
}

