// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkFiniteElementFieldDistributor.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkFiniteElementFieldDistributor__rvtk_new() { return static_cast<void*>(vtkFiniteElementFieldDistributor::New()); }

extern "C" int32_t vtkFiniteElementFieldDistributor__IsTypeOf__0(const char* type_) {
  return vtkFiniteElementFieldDistributor::IsTypeOf(type_);
}

extern "C" int32_t vtkFiniteElementFieldDistributor__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkFiniteElementFieldDistributor*>(self)->IsA(type_);
}

extern "C" void* vtkFiniteElementFieldDistributor__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkFiniteElementFieldDistributor::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkFiniteElementFieldDistributor__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkFiniteElementFieldDistributor::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkFiniteElementFieldDistributor__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkFiniteElementFieldDistributor*>(self)->GetNumberOfGenerationsFromBase(type_);
}

