// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGLTFDocumentLoader.h"
#include "vtkMatrix4x4.h"
#include "vtkObjectBase.h"
#include "vtkResourceStream.h"
#include "vtkURILoader.h"
#include <string>

extern "C" void* vtkGLTFDocumentLoader__rvtk_new() { return static_cast<void*>(vtkGLTFDocumentLoader::New()); }

extern "C" int32_t vtkGLTFDocumentLoader__IsTypeOf__0(const char* type_) {
  return vtkGLTFDocumentLoader::IsTypeOf(type_);
}

extern "C" int32_t vtkGLTFDocumentLoader__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->IsA(type_);
}

extern "C" void* vtkGLTFDocumentLoader__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGLTFDocumentLoader::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGLTFDocumentLoader__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGLTFDocumentLoader::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGLTFDocumentLoader__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" bool vtkGLTFDocumentLoader__ApplyAnimation__0(void* self, float t, int32_t animationId, bool forceStep) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->ApplyAnimation(t, animationId, forceStep);
}

extern "C" void vtkGLTFDocumentLoader__ResetAnimation__0(void* self, int32_t animationId) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->ResetAnimation(animationId);
}

extern "C" bool vtkGLTFDocumentLoader__LoadModelMetaDataFromFile__0(void* self, const char* FileName) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->LoadModelMetaDataFromFile(std::string(FileName));
}

extern "C" bool vtkGLTFDocumentLoader__LoadModelMetaDataFromStream__0(void* self, void* stream, void* loader, bool quiet) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->LoadModelMetaDataFromStream(static_cast<vtkResourceStream*>(stream), static_cast<vtkURILoader*>(loader), quiet);
}

extern "C" bool vtkGLTFDocumentLoader__BuildModelVTKGeometry__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->BuildModelVTKGeometry();
}

extern "C" bool vtkGLTFDocumentLoader__GetIsBinary__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->GetIsBinary();
}

extern "C" void vtkGLTFDocumentLoader__BuildGlobalTransforms__0(void* self, uint32_t nodeIndex, void* parentTransform) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->BuildGlobalTransforms(nodeIndex, static_cast<vtkMatrix4x4*>(parentTransform));
}

extern "C" void vtkGLTFDocumentLoader__BuildGlobalTransforms__1(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->BuildGlobalTransforms();
}

extern "C" void vtkGLTFDocumentLoader__PrepareData__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->PrepareData();
}

extern "C" void vtkGLTFDocumentLoader__SetGLBStart__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->SetGLBStart(_arg);
}

extern "C" int64_t vtkGLTFDocumentLoader__GetGLBStart__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->GetGLBStart();
}

extern "C" void vtkGLTFDocumentLoader__SetLoadAnimation__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->SetLoadAnimation(_arg);
}

extern "C" bool vtkGLTFDocumentLoader__GetLoadAnimation__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->GetLoadAnimation();
}

extern "C" void vtkGLTFDocumentLoader__LoadAnimationOn__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->LoadAnimationOn();
}

extern "C" void vtkGLTFDocumentLoader__LoadAnimationOff__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->LoadAnimationOff();
}

extern "C" void vtkGLTFDocumentLoader__SetLoadImages__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->SetLoadImages(_arg);
}

extern "C" bool vtkGLTFDocumentLoader__GetLoadImages__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->GetLoadImages();
}

extern "C" void vtkGLTFDocumentLoader__LoadImagesOn__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->LoadImagesOn();
}

extern "C" void vtkGLTFDocumentLoader__LoadImagesOff__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->LoadImagesOff();
}

extern "C" void vtkGLTFDocumentLoader__SetLoadSkinMatrix__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->SetLoadSkinMatrix(_arg);
}

extern "C" bool vtkGLTFDocumentLoader__GetLoadSkinMatrix__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFDocumentLoader*>(self)->GetLoadSkinMatrix();
}

extern "C" void vtkGLTFDocumentLoader__LoadSkinMatrixOn__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->LoadSkinMatrixOn();
}

extern "C" void vtkGLTFDocumentLoader__LoadSkinMatrixOff__0(void* self) {
  (void)self;
  static_cast<vtkGLTFDocumentLoader*>(self)->LoadSkinMatrixOff();
}

