// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGLTFReader.h"
#include "vtkDataArraySelection.h"
#include "vtkGLTFTexture.h"
#include "vtkObjectBase.h"
#include "vtkResourceStream.h"
#include "vtkStringArray.h"
#include "vtkURILoader.h"
#include <string>

extern "C" void* vtkGLTFReader__rvtk_new() { return static_cast<void*>(vtkGLTFReader::New()); }

extern "C" int32_t vtkGLTFReader__IsTypeOf__0(const char* type_) {
  return vtkGLTFReader::IsTypeOf(type_);
}

extern "C" int32_t vtkGLTFReader__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->IsA(type_);
}

extern "C" void* vtkGLTFReader__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGLTFReader::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGLTFReader__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGLTFReader::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGLTFReader__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int64_t vtkGLTFReader__GetNumberOfTextures__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetNumberOfTextures();
}

extern "C" void* vtkGLTFReader__GetTexture__0(void* self, int64_t textureIndex) {
  (void)self;
  return static_cast<void*>((static_cast<vtkGLTFReader*>(self)->GetTexture(textureIndex)).GetPointer());
}

extern "C" void vtkGLTFReader__SetFileName__0(void* self, const char* _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetFileName(_arg);
}

extern "C" void vtkGLTFReader__SetStream__0(void* self, void* _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetStream(static_cast<vtkResourceStream*>(_arg));
}

extern "C" void* vtkGLTFReader__GetStream__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGLTFReader*>(self)->GetStream());
}

extern "C" void vtkGLTFReader__SetGLBStart__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetGLBStart(_arg);
}

extern "C" int64_t vtkGLTFReader__GetGLBStart__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetGLBStart();
}

extern "C" void vtkGLTFReader__SetURILoader__0(void* self, void* _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetURILoader(static_cast<vtkURILoader*>(_arg));
}

extern "C" void* vtkGLTFReader__GetURILoader__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGLTFReader*>(self)->GetURILoader());
}

extern "C" void vtkGLTFReader__SetApplyDeformationsToGeometry__0(void* self, bool flag) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetApplyDeformationsToGeometry(flag);
}

extern "C" bool vtkGLTFReader__GetApplyDeformationsToGeometry__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetApplyDeformationsToGeometry();
}

extern "C" void vtkGLTFReader__ApplyDeformationsToGeometryOn__0(void* self) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->ApplyDeformationsToGeometryOn();
}

extern "C" void vtkGLTFReader__ApplyDeformationsToGeometryOff__0(void* self) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->ApplyDeformationsToGeometryOff();
}

extern "C" int64_t vtkGLTFReader__GetNumberOfAnimations__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetNumberOfAnimations();
}

extern "C" char* vtkGLTFReader__GetAnimationName__0(void* self, int64_t animationIndex) {
  (void)self;
  return rvtk_strdup((static_cast<vtkGLTFReader*>(self)->GetAnimationName(animationIndex)).c_str());
}

extern "C" float vtkGLTFReader__GetAnimationDuration__0(void* self, int64_t animationIndex) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetAnimationDuration(animationIndex);
}

extern "C" void vtkGLTFReader__EnableAnimation__0(void* self, int64_t animationIndex) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->EnableAnimation(animationIndex);
}

extern "C" void vtkGLTFReader__DisableAnimation__0(void* self, int64_t animationIndex) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->DisableAnimation(animationIndex);
}

extern "C" bool vtkGLTFReader__IsAnimationEnabled__0(void* self, int64_t animationIndex) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->IsAnimationEnabled(animationIndex);
}

extern "C" char* vtkGLTFReader__GetSceneName__0(void* self, int64_t sceneIndex) {
  (void)self;
  return rvtk_strdup((static_cast<vtkGLTFReader*>(self)->GetSceneName(sceneIndex)).c_str());
}

extern "C" int64_t vtkGLTFReader__GetNumberOfScenes__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetNumberOfScenes();
}

extern "C" int64_t vtkGLTFReader__GetCurrentScene__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetCurrentScene();
}

extern "C" void vtkGLTFReader__SetCurrentScene__0(void* self, int64_t _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetCurrentScene(_arg);
}

extern "C" void vtkGLTFReader__SetScene__0(void* self, const char* scene) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetScene(std::string(scene));
}

extern "C" uint32_t vtkGLTFReader__GetFrameRate__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetFrameRate();
}

extern "C" void vtkGLTFReader__SetFrameRate__0(void* self, uint32_t _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetFrameRate(_arg);
}

extern "C" void vtkGLTFReader__SetOutputPointsPrecision__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGLTFReader*>(self)->SetOutputPointsPrecision(_arg);
}

extern "C" int32_t vtkGLTFReader__GetOutputPointsPrecision__0(void* self) {
  (void)self;
  return static_cast<vtkGLTFReader*>(self)->GetOutputPointsPrecision();
}

extern "C" void* vtkGLTFReader__GetAllSceneNames__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGLTFReader*>(self)->GetAllSceneNames());
}

extern "C" void* vtkGLTFReader__GetAnimationSelection__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGLTFReader*>(self)->GetAnimationSelection());
}

