// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGlobFileNames.h"
#include "vtkObjectBase.h"
#include "vtkStringArray.h"
#include <string>

extern "C" void* vtkGlobFileNames__rvtk_new() { return static_cast<void*>(vtkGlobFileNames::New()); }

extern "C" int32_t vtkGlobFileNames__IsTypeOf__0(const char* type_) {
  return vtkGlobFileNames::IsTypeOf(type_);
}

extern "C" int32_t vtkGlobFileNames__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGlobFileNames*>(self)->IsA(type_);
}

extern "C" void* vtkGlobFileNames__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGlobFileNames::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGlobFileNames__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGlobFileNames::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGlobFileNames__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGlobFileNames*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkGlobFileNames__Reset__0(void* self) {
  (void)self;
  static_cast<vtkGlobFileNames*>(self)->Reset();
}

extern "C" void vtkGlobFileNames__SetDirectory__0(void* self, const char* _arg) {
  (void)self;
  static_cast<vtkGlobFileNames*>(self)->SetDirectory(_arg);
}

extern "C" int32_t vtkGlobFileNames__AddFileNames__0(void* self, const char* pattern) {
  (void)self;
  return static_cast<vtkGlobFileNames*>(self)->AddFileNames(pattern);
}

extern "C" void vtkGlobFileNames__SetRecurse__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGlobFileNames*>(self)->SetRecurse(_arg);
}

extern "C" void vtkGlobFileNames__RecurseOn__0(void* self) {
  (void)self;
  static_cast<vtkGlobFileNames*>(self)->RecurseOn();
}

extern "C" void vtkGlobFileNames__RecurseOff__0(void* self) {
  (void)self;
  static_cast<vtkGlobFileNames*>(self)->RecurseOff();
}

extern "C" int32_t vtkGlobFileNames__GetRecurse__0(void* self) {
  (void)self;
  return static_cast<vtkGlobFileNames*>(self)->GetRecurse();
}

extern "C" int32_t vtkGlobFileNames__GetNumberOfFileNames__0(void* self) {
  (void)self;
  return static_cast<vtkGlobFileNames*>(self)->GetNumberOfFileNames();
}

extern "C" const char* vtkGlobFileNames__GetNthFileName__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkGlobFileNames*>(self)->GetNthFileName(index);
}

extern "C" void* vtkGlobFileNames__GetFileNames__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGlobFileNames*>(self)->GetFileNames());
}

