// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGraphicsFactory.h"
#include "vtkObject.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkGraphicsFactory__rvtk_new() { return static_cast<void*>(vtkGraphicsFactory::New()); }

extern "C" int32_t vtkGraphicsFactory__IsTypeOf__0(const char* type_) {
  return vtkGraphicsFactory::IsTypeOf(type_);
}

extern "C" int32_t vtkGraphicsFactory__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGraphicsFactory*>(self)->IsA(type_);
}

extern "C" void* vtkGraphicsFactory__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGraphicsFactory::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGraphicsFactory__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGraphicsFactory::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGraphicsFactory__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGraphicsFactory*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkGraphicsFactory__CreateInstance__0(const char* vtkclassname) {
  return static_cast<void*>(vtkGraphicsFactory::CreateInstance(vtkclassname));
}

extern "C" const char* vtkGraphicsFactory__GetRenderLibrary__0() {
  return vtkGraphicsFactory::GetRenderLibrary();
}

extern "C" void vtkGraphicsFactory__SetUseMesaClasses__0(int32_t use_) {
  vtkGraphicsFactory::SetUseMesaClasses(use_);
}

extern "C" int32_t vtkGraphicsFactory__GetUseMesaClasses__0() {
  return vtkGraphicsFactory::GetUseMesaClasses();
}

extern "C" void vtkGraphicsFactory__SetOffScreenOnlyMode__0(int32_t use_) {
  vtkGraphicsFactory::SetOffScreenOnlyMode(use_);
}

extern "C" int32_t vtkGraphicsFactory__GetOffScreenOnlyMode__0() {
  return vtkGraphicsFactory::GetOffScreenOnlyMode();
}

