// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGenericRenderWindowInteractor.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkGenericRenderWindowInteractor__rvtk_new() { return static_cast<void*>(vtkGenericRenderWindowInteractor::New()); }

extern "C" int32_t vtkGenericRenderWindowInteractor__IsTypeOf__0(const char* type_) {
  return vtkGenericRenderWindowInteractor::IsTypeOf(type_);
}

extern "C" int32_t vtkGenericRenderWindowInteractor__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGenericRenderWindowInteractor*>(self)->IsA(type_);
}

extern "C" void* vtkGenericRenderWindowInteractor__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGenericRenderWindowInteractor::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGenericRenderWindowInteractor__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGenericRenderWindowInteractor::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGenericRenderWindowInteractor__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGenericRenderWindowInteractor*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkGenericRenderWindowInteractor__TimerEvent__0(void* self) {
  (void)self;
  static_cast<vtkGenericRenderWindowInteractor*>(self)->TimerEvent();
}

extern "C" void vtkGenericRenderWindowInteractor__SetTimerEventResetsTimer__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkGenericRenderWindowInteractor*>(self)->SetTimerEventResetsTimer(_arg);
}

extern "C" int32_t vtkGenericRenderWindowInteractor__GetTimerEventResetsTimer__0(void* self) {
  (void)self;
  return static_cast<vtkGenericRenderWindowInteractor*>(self)->GetTimerEventResetsTimer();
}

extern "C" void vtkGenericRenderWindowInteractor__TimerEventResetsTimerOn__0(void* self) {
  (void)self;
  static_cast<vtkGenericRenderWindowInteractor*>(self)->TimerEventResetsTimerOn();
}

extern "C" void vtkGenericRenderWindowInteractor__TimerEventResetsTimerOff__0(void* self) {
  (void)self;
  static_cast<vtkGenericRenderWindowInteractor*>(self)->TimerEventResetsTimerOff();
}

