// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkGenericDataObjectReader.h"
#include "vtkCellGrid.h"
#include "vtkDataObject.h"
#include "vtkGraph.h"
#include "vtkInformation.h"
#include "vtkMolecule.h"
#include "vtkObjectBase.h"
#include "vtkPolyData.h"
#include "vtkRectilinearGrid.h"
#include "vtkStatisticalModel.h"
#include "vtkStructuredGrid.h"
#include "vtkStructuredPoints.h"
#include "vtkTable.h"
#include "vtkTree.h"
#include "vtkUnstructuredGrid.h"
#include <string>

extern "C" void* vtkGenericDataObjectReader__rvtk_new() { return static_cast<void*>(vtkGenericDataObjectReader::New()); }

extern "C" int32_t vtkGenericDataObjectReader__IsTypeOf__0(const char* type_) {
  return vtkGenericDataObjectReader::IsTypeOf(type_);
}

extern "C" int32_t vtkGenericDataObjectReader__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGenericDataObjectReader*>(self)->IsA(type_);
}

extern "C" void* vtkGenericDataObjectReader__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGenericDataObjectReader::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGenericDataObjectReader__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGenericDataObjectReader::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGenericDataObjectReader__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGenericDataObjectReader*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkGenericDataObjectReader__GetOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetOutput__1(void* self, int32_t idx) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetOutput(idx));
}

extern "C" void* vtkGenericDataObjectReader__GetCellGridOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetCellGridOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetGraphOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetGraphOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetMoleculeOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetMoleculeOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetPolyDataOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetPolyDataOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetRectilinearGridOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetRectilinearGridOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetStructuredGridOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetStructuredGridOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetStructuredPointsOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetStructuredPointsOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetTableOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetTableOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetTreeOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetTreeOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetStatisticalModelOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetStatisticalModelOutput());
}

extern "C" void* vtkGenericDataObjectReader__GetUnstructuredGridOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGenericDataObjectReader*>(self)->GetUnstructuredGridOutput());
}

extern "C" int32_t vtkGenericDataObjectReader__ReadOutputType__0(void* self) {
  (void)self;
  return static_cast<vtkGenericDataObjectReader*>(self)->ReadOutputType();
}

extern "C" int32_t vtkGenericDataObjectReader__ReadMetaDataSimple__0(void* self, const char* fname, void* metadata) {
  (void)self;
  return static_cast<vtkGenericDataObjectReader*>(self)->ReadMetaDataSimple(std::string(fname), static_cast<vtkInformation*>(metadata));
}

extern "C" int32_t vtkGenericDataObjectReader__ReadMeshSimple__0(void* self, const char* fname, void* output) {
  (void)self;
  return static_cast<vtkGenericDataObjectReader*>(self)->ReadMeshSimple(std::string(fname), static_cast<vtkDataObject*>(output));
}

