// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkHigherOrderWedge.h"
#include "vtkCell.h"
#include "vtkCellArray.h"
#include "vtkCellData.h"
#include "vtkDataArray.h"
#include "vtkHigherOrderCurve.h"
#include "vtkHigherOrderInterpolation.h"
#include "vtkHigherOrderQuadrilateral.h"
#include "vtkHigherOrderTriangle.h"
#include "vtkIdList.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkObjectBase.h"
#include "vtkPointData.h"
#include <string>

extern "C" int32_t vtkHigherOrderWedge__IsTypeOf__0(const char* type_) {
  return vtkHigherOrderWedge::IsTypeOf(type_);
}

extern "C" int32_t vtkHigherOrderWedge__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->IsA(type_);
}

extern "C" void* vtkHigherOrderWedge__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkHigherOrderWedge::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkHigherOrderWedge__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkHigherOrderWedge::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkHigherOrderWedge__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkHigherOrderWedge__GetCellType__0(void* self) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetCellType();
}

extern "C" int32_t vtkHigherOrderWedge__GetCellDimension__0(void* self) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetCellDimension();
}

extern "C" int32_t vtkHigherOrderWedge__RequiresInitialization__0(void* self) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->RequiresInitialization();
}

extern "C" int32_t vtkHigherOrderWedge__GetNumberOfEdges__0(void* self) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetNumberOfEdges();
}

extern "C" int32_t vtkHigherOrderWedge__GetNumberOfFaces__0(void* self) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetNumberOfFaces();
}

extern "C" void* vtkHigherOrderWedge__GetEdge__0(void* self, int32_t edgeId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHigherOrderWedge*>(self)->GetEdge(edgeId));
}

extern "C" void* vtkHigherOrderWedge__GetFace__0(void* self, int32_t faceId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHigherOrderWedge*>(self)->GetFace(faceId));
}

extern "C" void vtkHigherOrderWedge__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->Initialize();
}

extern "C" int32_t vtkHigherOrderWedge__CellBoundary__0(void* self, int32_t subId, const double* pcoords, void* pts) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->CellBoundary(subId, pcoords, static_cast<vtkIdList*>(pts));
}

extern "C" void vtkHigherOrderWedge__Contour__0(void* self, double value, void* cellScalars, void* locator, void* verts, void* lines, void* polys, void* inPd, void* outPd, void* inCd, int64_t cellId, void* outCd) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->Contour(value, static_cast<vtkDataArray*>(cellScalars), static_cast<vtkIncrementalPointLocator*>(locator), static_cast<vtkCellArray*>(verts), static_cast<vtkCellArray*>(lines), static_cast<vtkCellArray*>(polys), static_cast<vtkPointData*>(inPd), static_cast<vtkPointData*>(outPd), static_cast<vtkCellData*>(inCd), cellId, static_cast<vtkCellData*>(outCd));
}

extern "C" void vtkHigherOrderWedge__Clip__0(void* self, double value, void* cellScalars, void* locator, void* polys, void* inPd, void* outPd, void* inCd, int64_t cellId, void* outCd, int32_t insideOut) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->Clip(value, static_cast<vtkDataArray*>(cellScalars), static_cast<vtkIncrementalPointLocator*>(locator), static_cast<vtkCellArray*>(polys), static_cast<vtkPointData*>(inPd), static_cast<vtkPointData*>(outPd), static_cast<vtkCellData*>(inCd), cellId, static_cast<vtkCellData*>(outCd), insideOut);
}

extern "C" int32_t vtkHigherOrderWedge__TriangulateLocalIds__0(void* self, int32_t index, void* ptIds) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->TriangulateLocalIds(index, static_cast<vtkIdList*>(ptIds));
}

extern "C" void vtkHigherOrderWedge__SetParametricCoords__0(void* self) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->SetParametricCoords();
}

extern "C" int32_t vtkHigherOrderWedge__GetParametricCenter__0(void* self, double* center) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetParametricCenter(center);
}

extern "C" double vtkHigherOrderWedge__GetParametricDistance__0(void* self, const double* pcoords) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetParametricDistance(pcoords);
}

extern "C" void vtkHigherOrderWedge__SetOrderFromCellData__0(void* self, void* cell_data, int64_t numPts, int64_t cell_id) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->SetOrderFromCellData(static_cast<vtkCellData*>(cell_data), numPts, cell_id);
}

extern "C" void vtkHigherOrderWedge__SetUniformOrderFromNumPoints__0(void* self, int64_t numPts) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->SetUniformOrderFromNumPoints(numPts);
}

extern "C" void vtkHigherOrderWedge__SetOrder__0(void* self, int32_t s, int32_t t, int32_t u, int64_t numPts) {
  (void)self;
  static_cast<vtkHigherOrderWedge*>(self)->SetOrder(s, t, u, numPts);
}

extern "C" int32_t vtkHigherOrderWedge__GetOrder__0(void* self, int32_t i) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetOrder(i);
}

extern "C" bool vtkHigherOrderWedge__PointCountSupportsUniformOrder__0(int64_t pointsPerCell) {
  return vtkHigherOrderWedge::PointCountSupportsUniformOrder(pointsPerCell);
}

extern "C" int32_t vtkHigherOrderWedge__PointIndexFromIJK__0(void* self, int32_t i, int32_t j, int32_t k) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->PointIndexFromIJK(i, j, k);
}

extern "C" int32_t vtkHigherOrderWedge__GetNumberOfApproximatingWedges__0(void* self) {
  (void)self;
  return static_cast<vtkHigherOrderWedge*>(self)->GetNumberOfApproximatingWedges();
}

extern "C" void* vtkHigherOrderWedge__GetBoundaryQuad__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHigherOrderWedge*>(self)->GetBoundaryQuad());
}

extern "C" void* vtkHigherOrderWedge__GetBoundaryTri__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHigherOrderWedge*>(self)->GetBoundaryTri());
}

extern "C" void* vtkHigherOrderWedge__GetEdgeCell__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHigherOrderWedge*>(self)->GetEdgeCell());
}

extern "C" void* vtkHigherOrderWedge__GetInterpolation__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHigherOrderWedge*>(self)->GetInterpolation());
}

