// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkHardwareSelector.h"
#include "vtkObjectBase.h"
#include "vtkProp.h"
#include "vtkRenderer.h"
#include "vtkSelection.h"
#include <string>

extern "C" void* vtkHardwareSelector__rvtk_new() { return static_cast<void*>(vtkHardwareSelector::New()); }

extern "C" int32_t vtkHardwareSelector__IsTypeOf__0(const char* type_) {
  return vtkHardwareSelector::IsTypeOf(type_);
}

extern "C" int32_t vtkHardwareSelector__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->IsA(type_);
}

extern "C" void* vtkHardwareSelector__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkHardwareSelector::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkHardwareSelector__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkHardwareSelector::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkHardwareSelector__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkHardwareSelector__SetRenderer__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetRenderer(static_cast<vtkRenderer*>(arg0));
}

extern "C" void* vtkHardwareSelector__GetRenderer__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHardwareSelector*>(self)->GetRenderer());
}

extern "C" void vtkHardwareSelector__SetArea__0(void* self, uint32_t _arg1, uint32_t _arg2, uint32_t _arg3, uint32_t _arg4) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetArea(_arg1, _arg2, _arg3, _arg4);
}

extern "C" void vtkHardwareSelector__SetArea__1(void* self, const uint32_t* _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetArea(_arg);
}

extern "C" void vtkHardwareSelector__SetFieldAssociation__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetFieldAssociation(_arg);
}

extern "C" int32_t vtkHardwareSelector__GetFieldAssociation__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetFieldAssociation();
}

extern "C" void vtkHardwareSelector__SetUseProcessIdFromData__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetUseProcessIdFromData(_arg);
}

extern "C" bool vtkHardwareSelector__GetUseProcessIdFromData__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetUseProcessIdFromData();
}

extern "C" void* vtkHardwareSelector__Select__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHardwareSelector*>(self)->Select());
}

extern "C" bool vtkHardwareSelector__CaptureBuffers__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->CaptureBuffers();
}

extern "C" void vtkHardwareSelector__ClearBuffers__0(void* self) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->ClearBuffers();
}

extern "C" void vtkHardwareSelector__RenderCompositeIndex__0(void* self, uint32_t index) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->RenderCompositeIndex(index);
}

extern "C" void vtkHardwareSelector__UpdateMaximumCellId__0(void* self, int64_t attribid) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->UpdateMaximumCellId(attribid);
}

extern "C" void vtkHardwareSelector__UpdateMaximumPointId__0(void* self, int64_t attribid) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->UpdateMaximumPointId(attribid);
}

extern "C" void vtkHardwareSelector__UpdateMaximumCellGridTupleId__0(void* self, int64_t attribid) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->UpdateMaximumCellGridTupleId(attribid);
}

extern "C" void vtkHardwareSelector__RenderProcessId__0(void* self, uint32_t processid) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->RenderProcessId(processid);
}

extern "C" bool vtkHardwareSelector__GetActorPassOnly__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetActorPassOnly();
}

extern "C" void vtkHardwareSelector__SetActorPassOnly__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetActorPassOnly(_arg);
}

extern "C" bool vtkHardwareSelector__GetCaptureZValues__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetCaptureZValues();
}

extern "C" void vtkHardwareSelector__SetCaptureZValues__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetCaptureZValues(_arg);
}

extern "C" void vtkHardwareSelector__BeginRenderProp__0(void* self) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->BeginRenderProp();
}

extern "C" void vtkHardwareSelector__EndRenderProp__0(void* self) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->EndRenderProp();
}

extern "C" void vtkHardwareSelector__SetProcessID__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetProcessID(_arg);
}

extern "C" int32_t vtkHardwareSelector__GetProcessID__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetProcessID();
}

extern "C" void vtkHardwareSelector__SetPropColorValue__0(void* self, float _arg1, float _arg2, float _arg3) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetPropColorValue(_arg1, _arg2, _arg3);
}

extern "C" void vtkHardwareSelector__SetPropColorValue__1(void* self, const float* _arg) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetPropColorValue(_arg);
}

extern "C" void vtkHardwareSelector__SetPropColorValue__2(void* self, int64_t val) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SetPropColorValue(val);
}

extern "C" int32_t vtkHardwareSelector__GetCurrentPass__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->GetCurrentPass();
}

extern "C" void* vtkHardwareSelector__GenerateSelection__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHardwareSelector*>(self)->GenerateSelection());
}

extern "C" void* vtkHardwareSelector__GenerateSelection__1(void* self, uint32_t* r) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHardwareSelector*>(self)->GenerateSelection(r));
}

extern "C" void* vtkHardwareSelector__GenerateSelection__2(void* self, uint32_t x1, uint32_t y1, uint32_t x2, uint32_t y2) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHardwareSelector*>(self)->GenerateSelection(x1, y1, x2, y2));
}

extern "C" void* vtkHardwareSelector__GetPropFromID__0(void* self, int32_t id) {
  (void)self;
  return static_cast<void*>(static_cast<vtkHardwareSelector*>(self)->GetPropFromID(id));
}

extern "C" void vtkHardwareSelector__Convert__0(int64_t id, float* tcoord) {
  vtkHardwareSelector::Convert(id, tcoord);
}

extern "C" void vtkHardwareSelector__SavePixelBuffer__0(void* self, int32_t passNo) {
  (void)self;
  static_cast<vtkHardwareSelector*>(self)->SavePixelBuffer(passNo);
}

extern "C" bool vtkHardwareSelector__HasHighCellIds__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->HasHighCellIds();
}

extern "C" bool vtkHardwareSelector__HasHighPointIds__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->HasHighPointIds();
}

extern "C" bool vtkHardwareSelector__HasHighCellGridTupleIds__0(void* self) {
  (void)self;
  return static_cast<vtkHardwareSelector*>(self)->HasHighCellGridTupleIds();
}

