// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkInterpolatingSubdivisionFilter.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" int32_t vtkInterpolatingSubdivisionFilter__IsTypeOf__0(const char* type_) {
  return vtkInterpolatingSubdivisionFilter::IsTypeOf(type_);
}

extern "C" int32_t vtkInterpolatingSubdivisionFilter__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkInterpolatingSubdivisionFilter*>(self)->IsA(type_);
}

extern "C" void* vtkInterpolatingSubdivisionFilter__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkInterpolatingSubdivisionFilter::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkInterpolatingSubdivisionFilter__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkInterpolatingSubdivisionFilter::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkInterpolatingSubdivisionFilter__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkInterpolatingSubdivisionFilter*>(self)->GetNumberOfGenerationsFromBase(type_);
}

