// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkImageResliceMapper.h"
#include "vtkAbstractImageInterpolator.h"
#include "vtkImageResliceToColors.h"
#include "vtkImageSlice.h"
#include "vtkObjectBase.h"
#include "vtkPlane.h"
#include "vtkRenderer.h"
#include "vtkWindow.h"
#include <string>

extern "C" void* vtkImageResliceMapper__rvtk_new() { return static_cast<void*>(vtkImageResliceMapper::New()); }

extern "C" int32_t vtkImageResliceMapper__IsTypeOf__0(const char* type_) {
  return vtkImageResliceMapper::IsTypeOf(type_);
}

extern "C" int32_t vtkImageResliceMapper__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->IsA(type_);
}

extern "C" void* vtkImageResliceMapper__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkImageResliceMapper::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkImageResliceMapper__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkImageResliceMapper::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkImageResliceMapper__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkImageResliceMapper__SetSlicePlane__0(void* self, void* plane) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlicePlane(static_cast<vtkPlane*>(plane));
}

extern "C" void* vtkImageResliceMapper__GetSlicePlane__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkImageResliceMapper*>(self)->GetSlicePlane());
}

extern "C" void vtkImageResliceMapper__SetJumpToNearestSlice__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetJumpToNearestSlice(_arg);
}

extern "C" void vtkImageResliceMapper__JumpToNearestSliceOn__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->JumpToNearestSliceOn();
}

extern "C" void vtkImageResliceMapper__JumpToNearestSliceOff__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->JumpToNearestSliceOff();
}

extern "C" int32_t vtkImageResliceMapper__GetJumpToNearestSlice__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetJumpToNearestSlice();
}

extern "C" void vtkImageResliceMapper__SetSlabThickness__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabThickness(_arg);
}

extern "C" double vtkImageResliceMapper__GetSlabThickness__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabThickness();
}

extern "C" void vtkImageResliceMapper__SetSlabType__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabType(_arg);
}

extern "C" int32_t vtkImageResliceMapper__GetSlabTypeMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabTypeMinValue();
}

extern "C" int32_t vtkImageResliceMapper__GetSlabTypeMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabTypeMaxValue();
}

extern "C" int32_t vtkImageResliceMapper__GetSlabType__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabType();
}

extern "C" void vtkImageResliceMapper__SetSlabTypeToMin__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabTypeToMin();
}

extern "C" void vtkImageResliceMapper__SetSlabTypeToMax__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabTypeToMax();
}

extern "C" void vtkImageResliceMapper__SetSlabTypeToMean__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabTypeToMean();
}

extern "C" void vtkImageResliceMapper__SetSlabTypeToSum__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabTypeToSum();
}

extern "C" const char* vtkImageResliceMapper__GetSlabTypeAsString__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabTypeAsString();
}

extern "C" void vtkImageResliceMapper__SetSlabSampleFactor__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSlabSampleFactor(_arg);
}

extern "C" int32_t vtkImageResliceMapper__GetSlabSampleFactorMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabSampleFactorMinValue();
}

extern "C" int32_t vtkImageResliceMapper__GetSlabSampleFactorMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabSampleFactorMaxValue();
}

extern "C" int32_t vtkImageResliceMapper__GetSlabSampleFactor__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSlabSampleFactor();
}

extern "C" void vtkImageResliceMapper__SetImageSampleFactor__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetImageSampleFactor(_arg);
}

extern "C" int32_t vtkImageResliceMapper__GetImageSampleFactorMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetImageSampleFactorMinValue();
}

extern "C" int32_t vtkImageResliceMapper__GetImageSampleFactorMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetImageSampleFactorMaxValue();
}

extern "C" int32_t vtkImageResliceMapper__GetImageSampleFactor__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetImageSampleFactor();
}

extern "C" void vtkImageResliceMapper__SetAutoAdjustImageQuality__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetAutoAdjustImageQuality(_arg);
}

extern "C" void vtkImageResliceMapper__AutoAdjustImageQualityOn__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->AutoAdjustImageQualityOn();
}

extern "C" void vtkImageResliceMapper__AutoAdjustImageQualityOff__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->AutoAdjustImageQualityOff();
}

extern "C" int32_t vtkImageResliceMapper__GetAutoAdjustImageQuality__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetAutoAdjustImageQuality();
}

extern "C" void vtkImageResliceMapper__SetResampleToScreenPixels__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetResampleToScreenPixels(_arg);
}

extern "C" void vtkImageResliceMapper__ResampleToScreenPixelsOn__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->ResampleToScreenPixelsOn();
}

extern "C" void vtkImageResliceMapper__ResampleToScreenPixelsOff__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->ResampleToScreenPixelsOff();
}

extern "C" int32_t vtkImageResliceMapper__GetResampleToScreenPixels__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetResampleToScreenPixels();
}

extern "C" void vtkImageResliceMapper__SetSeparateWindowLevelOperation__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetSeparateWindowLevelOperation(_arg);
}

extern "C" void vtkImageResliceMapper__SeparateWindowLevelOperationOn__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SeparateWindowLevelOperationOn();
}

extern "C" void vtkImageResliceMapper__SeparateWindowLevelOperationOff__0(void* self) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SeparateWindowLevelOperationOff();
}

extern "C" int32_t vtkImageResliceMapper__GetSeparateWindowLevelOperation__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetSeparateWindowLevelOperation();
}

extern "C" void vtkImageResliceMapper__SetInterpolator__0(void* self, void* interpolator) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetInterpolator(static_cast<vtkAbstractImageInterpolator*>(interpolator));
}

extern "C" void* vtkImageResliceMapper__GetInterpolator__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkImageResliceMapper*>(self)->GetInterpolator());
}

extern "C" void vtkImageResliceMapper__Render__0(void* self, void* renderer, void* prop) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->Render(static_cast<vtkRenderer*>(renderer), static_cast<vtkImageSlice*>(prop));
}

extern "C" void vtkImageResliceMapper__ReleaseGraphicsResources__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->ReleaseGraphicsResources(static_cast<vtkWindow*>(arg0));
}

extern "C" unsigned long vtkImageResliceMapper__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkImageResliceMapper*>(self)->GetMTime();
}

extern "C" void vtkImageResliceMapper__GetBounds__0(void* self, double* bounds) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->GetBounds(bounds);
}

extern "C" void vtkImageResliceMapper__GetIndexBounds__0(void* self, double* extent) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->GetIndexBounds(extent);
}

extern "C" void* vtkImageResliceMapper__GetImageReslice__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkImageResliceMapper*>(self)->GetImageReslice());
}

extern "C" void vtkImageResliceMapper__SetImageReslice__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkImageResliceMapper*>(self)->SetImageReslice(static_cast<vtkImageResliceToColors*>(arg0));
}

