// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkIndexedUnsignedLongLongArray.h"
#include "vtkAbstractArray.h"
#include "vtkDataArray.h"
#include "vtkIdList.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkIndexedUnsignedLongLongArray__rvtk_new() { return static_cast<void*>(vtkIndexedUnsignedLongLongArray::New()); }

extern "C" int32_t vtkIndexedUnsignedLongLongArray__IsTypeOf__0(const char* type_) {
  return vtkIndexedUnsignedLongLongArray::IsTypeOf(type_);
}

extern "C" int32_t vtkIndexedUnsignedLongLongArray__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->IsA(type_);
}

extern "C" void* vtkIndexedUnsignedLongLongArray__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkIndexedUnsignedLongLongArray::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkIndexedUnsignedLongLongArray__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkIndexedUnsignedLongLongArray::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkIndexedUnsignedLongLongArray__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkIndexedUnsignedLongLongArray__ExtendedNew__0() {
  return static_cast<void*>(vtkIndexedUnsignedLongLongArray::ExtendedNew());
}

extern "C" int32_t vtkIndexedUnsignedLongLongArray__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetDataType();
}

extern "C" uint64_t vtkIndexedUnsignedLongLongArray__GetDataTypeValueMin__0(void* self) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetDataTypeValueMin();
}

extern "C" uint64_t vtkIndexedUnsignedLongLongArray__GetDataTypeValueMax__0(void* self) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetDataTypeValueMax();
}

extern "C" void vtkIndexedUnsignedLongLongArray__GetValueRange__0(void* self, uint64_t* range, int32_t comp) {
  (void)self;
  static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetValueRange(range, comp);
}

extern "C" void vtkIndexedUnsignedLongLongArray__GetValueRange__1(void* self, uint64_t* range, int32_t comp) {
  (void)self;
  static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetValueRange(range, comp);
}

extern "C" uint64_t vtkIndexedUnsignedLongLongArray__GetTypedComponent__0(void* self, int64_t i, int32_t c) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetTypedComponent(i, c);
}

extern "C" uint64_t vtkIndexedUnsignedLongLongArray__GetValue__0(void* self, int64_t id) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetValue(id);
}

extern "C" bool vtkIndexedUnsignedLongLongArray__SetNumberOfValues__0(void* self, int64_t number) {
  (void)self;
  return static_cast<vtkIndexedUnsignedLongLongArray*>(self)->SetNumberOfValues(number);
}

extern "C" void vtkIndexedUnsignedLongLongArray__ConstructBackend__0(void* self, void* indexes, void* array) {
  (void)self;
  static_cast<vtkIndexedUnsignedLongLongArray*>(self)->ConstructBackend(static_cast<vtkIdList*>(indexes), static_cast<vtkDataArray*>(array));
}

extern "C" void vtkIndexedUnsignedLongLongArray__ConstructBackend__1(void* self, void* indexes, void* array) {
  (void)self;
  static_cast<vtkIndexedUnsignedLongLongArray*>(self)->ConstructBackend(static_cast<vtkDataArray*>(indexes), static_cast<vtkDataArray*>(array));
}

extern "C" void* vtkIndexedUnsignedLongLongArray__GetBaseArray__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetBaseArray());
}

extern "C" void* vtkIndexedUnsignedLongLongArray__GetIndexArray__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkIndexedUnsignedLongLongArray*>(self)->GetIndexArray());
}

extern "C" void* vtkIndexedUnsignedLongLongArray__FastDownCast__0(void* source) {
  return static_cast<void*>(vtkIndexedUnsignedLongLongArray::FastDownCast(static_cast<vtkAbstractArray*>(source)));
}

