// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkMultiPieceDataSet.h"
#include "vtkDataObject.h"
#include "vtkDataSet.h"
#include "vtkInformation.h"
#include "vtkInformationVector.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkMultiPieceDataSet__rvtk_new() { return static_cast<void*>(vtkMultiPieceDataSet::New()); }

extern "C" int32_t vtkMultiPieceDataSet__IsTypeOf__0(const char* type_) {
  return vtkMultiPieceDataSet::IsTypeOf(type_);
}

extern "C" int32_t vtkMultiPieceDataSet__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkMultiPieceDataSet*>(self)->IsA(type_);
}

extern "C" void* vtkMultiPieceDataSet__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkMultiPieceDataSet::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkMultiPieceDataSet__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkMultiPieceDataSet::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkMultiPieceDataSet__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkMultiPieceDataSet*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkMultiPieceDataSet__GetDataObjectType__0(void* self) {
  (void)self;
  return static_cast<vtkMultiPieceDataSet*>(self)->GetDataObjectType();
}

extern "C" void vtkMultiPieceDataSet__SetNumberOfPieces__0(void* self, uint32_t numpieces) {
  (void)self;
  static_cast<vtkMultiPieceDataSet*>(self)->SetNumberOfPieces(numpieces);
}

extern "C" uint32_t vtkMultiPieceDataSet__GetNumberOfPieces__0(void* self) {
  (void)self;
  return static_cast<vtkMultiPieceDataSet*>(self)->GetNumberOfPieces();
}

extern "C" void* vtkMultiPieceDataSet__GetPiece__0(void* self, uint32_t pieceno) {
  (void)self;
  return static_cast<void*>(static_cast<vtkMultiPieceDataSet*>(self)->GetPiece(pieceno));
}

extern "C" void* vtkMultiPieceDataSet__GetPieceAsDataObject__0(void* self, uint32_t pieceno) {
  (void)self;
  return static_cast<void*>(static_cast<vtkMultiPieceDataSet*>(self)->GetPieceAsDataObject(pieceno));
}

extern "C" void vtkMultiPieceDataSet__SetPiece__0(void* self, uint32_t pieceno, void* piece) {
  (void)self;
  static_cast<vtkMultiPieceDataSet*>(self)->SetPiece(pieceno, static_cast<vtkDataObject*>(piece));
}

extern "C" void* vtkMultiPieceDataSet__GetData__0(void* info) {
  return static_cast<void*>(vtkMultiPieceDataSet::GetData(static_cast<vtkInformation*>(info)));
}

extern "C" void* vtkMultiPieceDataSet__GetData__1(void* v, int32_t i) {
  return static_cast<void*>(vtkMultiPieceDataSet::GetData(static_cast<vtkInformationVector*>(v), i));
}

