// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkMath.h"
#include "vtkDataArray.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkMath__rvtk_new() { return static_cast<void*>(vtkMath::New()); }

extern "C" int32_t vtkMath__IsTypeOf__0(const char* type_) {
  return vtkMath::IsTypeOf(type_);
}

extern "C" int32_t vtkMath__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkMath*>(self)->IsA(type_);
}

extern "C" void* vtkMath__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkMath::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkMath__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkMath::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkMath__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkMath*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkMath__DYNAMIC_VECTOR_SIZE__0() {
  return vtkMath::DYNAMIC_VECTOR_SIZE();
}

extern "C" double vtkMath__Pi__0() {
  return vtkMath::Pi();
}

extern "C" float vtkMath__RadiansFromDegrees__0(float degrees) {
  return vtkMath::RadiansFromDegrees(degrees);
}

extern "C" double vtkMath__RadiansFromDegrees__1(double degrees) {
  return vtkMath::RadiansFromDegrees(degrees);
}

extern "C" float vtkMath__DegreesFromRadians__0(float radians) {
  return vtkMath::DegreesFromRadians(radians);
}

extern "C" double vtkMath__DegreesFromRadians__1(double radians) {
  return vtkMath::DegreesFromRadians(radians);
}

extern "C" int32_t vtkMath__Round__0(float f) {
  return vtkMath::Round(f);
}

extern "C" int32_t vtkMath__Round__1(double f) {
  return vtkMath::Round(f);
}

extern "C" int32_t vtkMath__Floor__0(double x) {
  return vtkMath::Floor(x);
}

extern "C" int32_t vtkMath__Ceil__0(double x) {
  return vtkMath::Ceil(x);
}

extern "C" int32_t vtkMath__CeilLog2__0(uint64_t x) {
  return vtkMath::CeilLog2(x);
}

extern "C" bool vtkMath__IsPowerOfTwo__0(uint64_t x) {
  return vtkMath::IsPowerOfTwo(x);
}

extern "C" int32_t vtkMath__NearestPowerOfTwo__0(int32_t x) {
  return vtkMath::NearestPowerOfTwo(x);
}

extern "C" int64_t vtkMath__Factorial__0(int32_t N) {
  return vtkMath::Factorial(N);
}

extern "C" int64_t vtkMath__Binomial__0(int32_t m, int32_t n) {
  return vtkMath::Binomial(m, n);
}

extern "C" void vtkMath__RandomSeed__0(int32_t s) {
  vtkMath::RandomSeed(s);
}

extern "C" int32_t vtkMath__GetSeed__0() {
  return vtkMath::GetSeed();
}

extern "C" double vtkMath__Random__0() {
  return vtkMath::Random();
}

extern "C" double vtkMath__Random__1(double min, double max) {
  return vtkMath::Random(min, max);
}

extern "C" double vtkMath__Gaussian__0() {
  return vtkMath::Gaussian();
}

extern "C" double vtkMath__Gaussian__1(double mean, double std) {
  return vtkMath::Gaussian(mean, std);
}

extern "C" void vtkMath__Assign__0(const double* a, double* b) {
  vtkMath::Assign(a, b);
}

extern "C" void vtkMath__Add__0(const float* a, const float* b, float* c) {
  vtkMath::Add(a, b, c);
}

extern "C" void vtkMath__Add__1(const double* a, const double* b, double* c) {
  vtkMath::Add(a, b, c);
}

extern "C" void vtkMath__Subtract__0(const float* a, const float* b, float* c) {
  vtkMath::Subtract(a, b, c);
}

extern "C" void vtkMath__Subtract__1(const double* a, const double* b, double* c) {
  vtkMath::Subtract(a, b, c);
}

extern "C" void vtkMath__MultiplyScalar__0(float* a, float s) {
  vtkMath::MultiplyScalar(a, s);
}

extern "C" void vtkMath__MultiplyScalar2D__0(float* a, float s) {
  vtkMath::MultiplyScalar2D(a, s);
}

extern "C" void vtkMath__MultiplyScalar__1(double* a, double s) {
  vtkMath::MultiplyScalar(a, s);
}

extern "C" void vtkMath__MultiplyScalar2D__1(double* a, double s) {
  vtkMath::MultiplyScalar2D(a, s);
}

extern "C" float vtkMath__Dot__0(const float* a, const float* b) {
  return vtkMath::Dot(a, b);
}

extern "C" double vtkMath__Dot__1(const double* a, const double* b) {
  return vtkMath::Dot(a, b);
}

extern "C" void vtkMath__Cross__0(const float* a, const float* b, float* c) {
  vtkMath::Cross(a, b, c);
}

extern "C" void vtkMath__Cross__1(const double* a, const double* b, double* c) {
  vtkMath::Cross(a, b, c);
}

extern "C" float vtkMath__Norm__0(const float* v) {
  return vtkMath::Norm(v);
}

extern "C" double vtkMath__Norm__1(const double* v) {
  return vtkMath::Norm(v);
}

extern "C" float vtkMath__Normalize__0(float* v) {
  return vtkMath::Normalize(v);
}

extern "C" double vtkMath__Normalize__1(double* v) {
  return vtkMath::Normalize(v);
}

extern "C" void vtkMath__Perpendiculars__0(const double* v1, double* v2, double* v3, double theta) {
  vtkMath::Perpendiculars(v1, v2, v3, theta);
}

extern "C" void vtkMath__Perpendiculars__1(const float* v1, float* v2, float* v3, double theta) {
  vtkMath::Perpendiculars(v1, v2, v3, theta);
}

extern "C" bool vtkMath__ProjectVector__0(const float* a, const float* b, float* projection) {
  return vtkMath::ProjectVector(a, b, projection);
}

extern "C" bool vtkMath__ProjectVector__1(const double* a, const double* b, double* projection) {
  return vtkMath::ProjectVector(a, b, projection);
}

extern "C" bool vtkMath__ProjectVector2D__0(const float* a, const float* b, float* projection) {
  return vtkMath::ProjectVector2D(a, b, projection);
}

extern "C" bool vtkMath__ProjectVector2D__1(const double* a, const double* b, double* projection) {
  return vtkMath::ProjectVector2D(a, b, projection);
}

extern "C" float vtkMath__Distance2BetweenPoints__0(const float* p1, const float* p2) {
  return vtkMath::Distance2BetweenPoints(p1, p2);
}

extern "C" double vtkMath__Distance2BetweenPoints__1(const double* p1, const double* p2) {
  return vtkMath::Distance2BetweenPoints(p1, p2);
}

extern "C" double vtkMath__Distance2BetweenPoints2D__0(const double* p1, const double* p2) {
  return vtkMath::Distance2BetweenPoints2D(p1, p2);
}

extern "C" double vtkMath__AngleBetweenVectors__0(const double* v1, const double* v2) {
  return vtkMath::AngleBetweenVectors(v1, v2);
}

extern "C" double vtkMath__SignedAngleBetweenVectors__0(const double* v1, const double* v2, const double* vn) {
  return vtkMath::SignedAngleBetweenVectors(v1, v2, vn);
}

extern "C" double vtkMath__GaussianAmplitude__0(double variance, double distanceFromMean) {
  return vtkMath::GaussianAmplitude(variance, distanceFromMean);
}

extern "C" double vtkMath__GaussianAmplitude__1(double mean, double variance, double position) {
  return vtkMath::GaussianAmplitude(mean, variance, position);
}

extern "C" double vtkMath__GaussianWeight__0(double variance, double distanceFromMean) {
  return vtkMath::GaussianWeight(variance, distanceFromMean);
}

extern "C" double vtkMath__GaussianWeight__1(double mean, double variance, double position) {
  return vtkMath::GaussianWeight(mean, variance, position);
}

extern "C" float vtkMath__Dot2D__0(const float* x, const float* y) {
  return vtkMath::Dot2D(x, y);
}

extern "C" double vtkMath__Dot2D__1(const double* x, const double* y) {
  return vtkMath::Dot2D(x, y);
}

extern "C" float vtkMath__Norm2D__0(const float* x) {
  return vtkMath::Norm2D(x);
}

extern "C" double vtkMath__Norm2D__1(const double* x) {
  return vtkMath::Norm2D(x);
}

extern "C" float vtkMath__Normalize2D__0(float* v) {
  return vtkMath::Normalize2D(v);
}

extern "C" double vtkMath__Normalize2D__1(double* v) {
  return vtkMath::Normalize2D(v);
}

extern "C" float vtkMath__Determinant2x2__0(const float* c1, const float* c2) {
  return vtkMath::Determinant2x2(c1, c2);
}

extern "C" double vtkMath__Determinant2x2__1(double a, double b, double c, double d) {
  return vtkMath::Determinant2x2(a, b, c, d);
}

extern "C" double vtkMath__Determinant2x2__2(const double* c1, const double* c2) {
  return vtkMath::Determinant2x2(c1, c2);
}

extern "C" float vtkMath__Determinant3x3__0(const float* c1, const float* c2, const float* c3) {
  return vtkMath::Determinant3x3(c1, c2, c3);
}

extern "C" double vtkMath__Determinant3x3__1(const double* c1, const double* c2, const double* c3) {
  return vtkMath::Determinant3x3(c1, c2, c3);
}

extern "C" double vtkMath__Determinant3x3__2(double a1, double a2, double a3, double b1, double b2, double b3, double c1, double c2, double c3) {
  return vtkMath::Determinant3x3(a1, a2, a3, b1, b2, b3, c1, c2, c3);
}

extern "C" void vtkMath__MultiplyQuaternion__0(const float* q1, const float* q2, float* q) {
  vtkMath::MultiplyQuaternion(q1, q2, q);
}

extern "C" void vtkMath__MultiplyQuaternion__1(const double* q1, const double* q2, double* q) {
  vtkMath::MultiplyQuaternion(q1, q2, q);
}

extern "C" void vtkMath__RotateVectorByNormalizedQuaternion__0(const float* v, const float* q, float* r) {
  vtkMath::RotateVectorByNormalizedQuaternion(v, q, r);
}

extern "C" void vtkMath__RotateVectorByNormalizedQuaternion__1(const double* v, const double* q, double* r) {
  vtkMath::RotateVectorByNormalizedQuaternion(v, q, r);
}

extern "C" void vtkMath__RotateVectorByWXYZ__0(const float* v, const float* q, float* r) {
  vtkMath::RotateVectorByWXYZ(v, q, r);
}

extern "C" void vtkMath__RotateVectorByWXYZ__1(const double* v, const double* q, double* r) {
  vtkMath::RotateVectorByWXYZ(v, q, r);
}

extern "C" void vtkMath__RGBToHSV__0(const float* rgb, float* hsv) {
  vtkMath::RGBToHSV(rgb, hsv);
}

extern "C" void vtkMath__RGBToHSV__1(const double* rgb, double* hsv) {
  vtkMath::RGBToHSV(rgb, hsv);
}

extern "C" void vtkMath__HSVToRGB__0(const float* hsv, float* rgb) {
  vtkMath::HSVToRGB(hsv, rgb);
}

extern "C" void vtkMath__HSVToRGB__1(const double* hsv, double* rgb) {
  vtkMath::HSVToRGB(hsv, rgb);
}

extern "C" void vtkMath__ProLabToXYZ__0(const double* prolab, double* xyz) {
  vtkMath::ProLabToXYZ(prolab, xyz);
}

extern "C" void vtkMath__XYZToProLab__0(const double* xyz, double* prolab) {
  vtkMath::XYZToProLab(xyz, prolab);
}

extern "C" void vtkMath__LabToXYZ__0(const double* lab, double* xyz) {
  vtkMath::LabToXYZ(lab, xyz);
}

extern "C" void vtkMath__XYZToLab__0(const double* xyz, double* lab) {
  vtkMath::XYZToLab(xyz, lab);
}

extern "C" void vtkMath__XYZToRGB__0(const double* xyz, double* rgb) {
  vtkMath::XYZToRGB(xyz, rgb);
}

extern "C" void vtkMath__RGBToXYZ__0(const double* rgb, double* xyz) {
  vtkMath::RGBToXYZ(rgb, xyz);
}

extern "C" void vtkMath__RGBToLab__0(const double* rgb, double* lab) {
  vtkMath::RGBToLab(rgb, lab);
}

extern "C" void vtkMath__ProLabToRGB__0(const double* prolab, double* rgb) {
  vtkMath::ProLabToRGB(prolab, rgb);
}

extern "C" void vtkMath__RGBToProLab__0(const double* rgb, double* prolab) {
  vtkMath::RGBToProLab(rgb, prolab);
}

extern "C" void vtkMath__LabToRGB__0(const double* lab, double* rgb) {
  vtkMath::LabToRGB(lab, rgb);
}

extern "C" void vtkMath__UninitializeBounds__0(double* bounds) {
  vtkMath::UninitializeBounds(bounds);
}

extern "C" int32_t vtkMath__AreBoundsInitialized__0(const double* bounds) {
  return vtkMath::AreBoundsInitialized(bounds);
}

extern "C" double vtkMath__ClampAndNormalizeValue__0(double value, const double* range) {
  return vtkMath::ClampAndNormalizeValue(value, range);
}

extern "C" int32_t vtkMath__GetScalarTypeFittingRange__0(double range_min, double range_max, double scale, double shift) {
  return vtkMath::GetScalarTypeFittingRange(range_min, range_max, scale, shift);
}

extern "C" int32_t vtkMath__GetAdjustedScalarRange__0(void* array, int32_t comp, double* range) {
  return vtkMath::GetAdjustedScalarRange(static_cast<vtkDataArray*>(array), comp, range);
}

extern "C" int32_t vtkMath__ExtentIsWithinOtherExtent__0(const int32_t* extent1, const int32_t* extent2) {
  return vtkMath::ExtentIsWithinOtherExtent(extent1, extent2);
}

extern "C" int32_t vtkMath__BoundsIsWithinOtherBounds__0(const double* bounds1, const double* bounds2, const double* delta) {
  return vtkMath::BoundsIsWithinOtherBounds(bounds1, bounds2, delta);
}

extern "C" int32_t vtkMath__PointIsWithinBounds__0(const double* point, const double* bounds, const double* delta) {
  return vtkMath::PointIsWithinBounds(point, bounds, delta);
}

extern "C" int32_t vtkMath__PlaneIntersectsAABB__0(const double* bounds, const double* normal, const double* point) {
  return vtkMath::PlaneIntersectsAABB(bounds, normal, point);
}

extern "C" double vtkMath__Solve3PointCircle__0(const double* p1, const double* p2, const double* p3, double* center) {
  return vtkMath::Solve3PointCircle(p1, p2, p3, center);
}

extern "C" double vtkMath__Inf__0() {
  return vtkMath::Inf();
}

extern "C" double vtkMath__NegInf__0() {
  return vtkMath::NegInf();
}

extern "C" double vtkMath__Nan__0() {
  return vtkMath::Nan();
}

extern "C" int32_t vtkMath__IsInf__0(double x) {
  return vtkMath::IsInf(x);
}

extern "C" int32_t vtkMath__IsNan__0(double x) {
  return vtkMath::IsNan(x);
}

extern "C" bool vtkMath__IsFinite__0(double x) {
  return vtkMath::IsFinite(x);
}

extern "C" int64_t vtkMath__ComputeGCD__0(int64_t m, int64_t n) {
  return vtkMath::ComputeGCD(m, n);
}

extern "C" void vtkMath__GetPointAlongLine__0(double* result, double* p1, double* p2, double offset) {
  vtkMath::GetPointAlongLine(result, p1, p2, offset);
}

