// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkOpenGLLowMemoryBatchedPolyDataMapper.h"
#include "vtkActor.h"
#include "vtkCompositePolyDataMapper.h"
#include "vtkObjectBase.h"
#include "vtkRenderer.h"
#include <string>

extern "C" void* vtkOpenGLLowMemoryBatchedPolyDataMapper__rvtk_new() { return static_cast<void*>(vtkOpenGLLowMemoryBatchedPolyDataMapper::New()); }

extern "C" int32_t vtkOpenGLLowMemoryBatchedPolyDataMapper__IsTypeOf__0(const char* type_) {
  return vtkOpenGLLowMemoryBatchedPolyDataMapper::IsTypeOf(type_);
}

extern "C" int32_t vtkOpenGLLowMemoryBatchedPolyDataMapper__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->IsA(type_);
}

extern "C" void* vtkOpenGLLowMemoryBatchedPolyDataMapper__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkOpenGLLowMemoryBatchedPolyDataMapper::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkOpenGLLowMemoryBatchedPolyDataMapper__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkOpenGLLowMemoryBatchedPolyDataMapper::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkOpenGLLowMemoryBatchedPolyDataMapper__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkOpenGLLowMemoryBatchedPolyDataMapper__ClearBatchElements__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->ClearBatchElements();
}

extern "C" void vtkOpenGLLowMemoryBatchedPolyDataMapper__SetParent__0(void* self, void* parent) {
  (void)self;
  static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->SetParent(static_cast<vtkCompositePolyDataMapper*>(parent));
}

extern "C" void vtkOpenGLLowMemoryBatchedPolyDataMapper__RenderPiece__0(void* self, void* renderer, void* actor) {
  (void)self;
  static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->RenderPiece(static_cast<vtkRenderer*>(renderer), static_cast<vtkActor*>(actor));
}

extern "C" void vtkOpenGLLowMemoryBatchedPolyDataMapper__UnmarkBatchElements__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->UnmarkBatchElements();
}

extern "C" void vtkOpenGLLowMemoryBatchedPolyDataMapper__ClearUnmarkedBatchElements__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->ClearUnmarkedBatchElements();
}

extern "C" unsigned long vtkOpenGLLowMemoryBatchedPolyDataMapper__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLLowMemoryBatchedPolyDataMapper*>(self)->GetMTime();
}

