// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkOpenGLTexture.h"
#include "vtkObjectBase.h"
#include "vtkOverrideAttribute.h"
#include "vtkRenderer.h"
#include "vtkTextureObject.h"
#include "vtkWindow.h"
#include <string>

extern "C" void* vtkOpenGLTexture__rvtk_new() { return static_cast<void*>(vtkOpenGLTexture::New()); }

extern "C" void* vtkOpenGLTexture__CreateOverrideAttributes__0() {
  return static_cast<void*>(vtkOpenGLTexture::CreateOverrideAttributes());
}

extern "C" int32_t vtkOpenGLTexture__IsTypeOf__0(const char* type_) {
  return vtkOpenGLTexture::IsTypeOf(type_);
}

extern "C" int32_t vtkOpenGLTexture__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLTexture*>(self)->IsA(type_);
}

extern "C" void* vtkOpenGLTexture__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkOpenGLTexture::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkOpenGLTexture__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkOpenGLTexture::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkOpenGLTexture__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLTexture*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkOpenGLTexture__Render__0(void* self, void* ren) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->Render(static_cast<vtkRenderer*>(ren));
}

extern "C" void vtkOpenGLTexture__Load__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->Load(static_cast<vtkRenderer*>(arg0));
}

extern "C" void vtkOpenGLTexture__PostRender__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->PostRender(static_cast<vtkRenderer*>(arg0));
}

extern "C" void vtkOpenGLTexture__ReleaseGraphicsResources__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->ReleaseGraphicsResources(static_cast<vtkWindow*>(arg0));
}

extern "C" void vtkOpenGLTexture__CopyTexImage__0(void* self, int32_t x, int32_t y, int32_t width, int32_t height) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->CopyTexImage(x, y, width, height);
}

extern "C" int32_t vtkOpenGLTexture__GetIsDepthTexture__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLTexture*>(self)->GetIsDepthTexture();
}

extern "C" void vtkOpenGLTexture__SetIsDepthTexture__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->SetIsDepthTexture(_arg);
}

extern "C" int32_t vtkOpenGLTexture__GetTextureType__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLTexture*>(self)->GetTextureType();
}

extern "C" void vtkOpenGLTexture__SetTextureType__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->SetTextureType(_arg);
}

extern "C" void* vtkOpenGLTexture__GetTextureObject__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkOpenGLTexture*>(self)->GetTextureObject());
}

extern "C" void vtkOpenGLTexture__SetTextureObject__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkOpenGLTexture*>(self)->SetTextureObject(static_cast<vtkTextureObject*>(arg0));
}

extern "C" int32_t vtkOpenGLTexture__GetTextureUnit__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLTexture*>(self)->GetTextureUnit();
}

extern "C" int32_t vtkOpenGLTexture__IsTranslucent__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLTexture*>(self)->IsTranslucent();
}

