// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkOpenGLCompositePolyDataMapperDelegator.h"
#include "vtkCompositePolyDataMapper.h"
#include "vtkObjectBase.h"
#include "vtkOverrideAttribute.h"
#include <string>

extern "C" void* vtkOpenGLCompositePolyDataMapperDelegator__rvtk_new() { return static_cast<void*>(vtkOpenGLCompositePolyDataMapperDelegator::New()); }

extern "C" void* vtkOpenGLCompositePolyDataMapperDelegator__CreateOverrideAttributes__0() {
  return static_cast<void*>(vtkOpenGLCompositePolyDataMapperDelegator::CreateOverrideAttributes());
}

extern "C" int32_t vtkOpenGLCompositePolyDataMapperDelegator__IsTypeOf__0(const char* type_) {
  return vtkOpenGLCompositePolyDataMapperDelegator::IsTypeOf(type_);
}

extern "C" int32_t vtkOpenGLCompositePolyDataMapperDelegator__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLCompositePolyDataMapperDelegator*>(self)->IsA(type_);
}

extern "C" void* vtkOpenGLCompositePolyDataMapperDelegator__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkOpenGLCompositePolyDataMapperDelegator::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkOpenGLCompositePolyDataMapperDelegator__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkOpenGLCompositePolyDataMapperDelegator::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkOpenGLCompositePolyDataMapperDelegator__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLCompositePolyDataMapperDelegator*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkOpenGLCompositePolyDataMapperDelegator__ShallowCopy__0(void* self, void* mapper) {
  (void)self;
  static_cast<vtkOpenGLCompositePolyDataMapperDelegator*>(self)->ShallowCopy(static_cast<vtkCompositePolyDataMapper*>(mapper));
}

extern "C" void vtkOpenGLCompositePolyDataMapperDelegator__ClearUnmarkedBatchElements__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLCompositePolyDataMapperDelegator*>(self)->ClearUnmarkedBatchElements();
}

extern "C" void vtkOpenGLCompositePolyDataMapperDelegator__UnmarkBatchElements__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLCompositePolyDataMapperDelegator*>(self)->UnmarkBatchElements();
}

