// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkProbeFilter.h"
#include "vtkAbstractCellLocator.h"
#include "vtkAlgorithmOutput.h"
#include "vtkDataObject.h"
#include "vtkIdTypeArray.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkProbeFilter__rvtk_new() { return static_cast<void*>(vtkProbeFilter::New()); }

extern "C" int32_t vtkProbeFilter__IsTypeOf__0(const char* type_) {
  return vtkProbeFilter::IsTypeOf(type_);
}

extern "C" int32_t vtkProbeFilter__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->IsA(type_);
}

extern "C" void* vtkProbeFilter__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkProbeFilter::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkProbeFilter__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkProbeFilter::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkProbeFilter__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkProbeFilter__SetSourceData__0(void* self, void* source) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetSourceData(static_cast<vtkDataObject*>(source));
}

extern "C" void* vtkProbeFilter__GetSource__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkProbeFilter*>(self)->GetSource());
}

extern "C" void vtkProbeFilter__SetSourceConnection__0(void* self, void* algOutput) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetSourceConnection(static_cast<vtkAlgorithmOutput*>(algOutput));
}

extern "C" void vtkProbeFilter__SetCategoricalData__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetCategoricalData(_arg);
}

extern "C" int32_t vtkProbeFilter__GetCategoricalData__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetCategoricalData();
}

extern "C" void vtkProbeFilter__CategoricalDataOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->CategoricalDataOn();
}

extern "C" void vtkProbeFilter__CategoricalDataOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->CategoricalDataOff();
}

extern "C" void vtkProbeFilter__SetSpatialMatch__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetSpatialMatch(_arg);
}

extern "C" int32_t vtkProbeFilter__GetSpatialMatch__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetSpatialMatch();
}

extern "C" void vtkProbeFilter__SpatialMatchOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SpatialMatchOn();
}

extern "C" void vtkProbeFilter__SpatialMatchOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SpatialMatchOff();
}

extern "C" void* vtkProbeFilter__GetValidPoints__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkProbeFilter*>(self)->GetValidPoints());
}

extern "C" void vtkProbeFilter__SetValidPointMaskArrayName__0(void* self, const char* _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetValidPointMaskArrayName(_arg);
}

extern "C" void vtkProbeFilter__SetPassCellArrays__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetPassCellArrays(_arg);
}

extern "C" void vtkProbeFilter__PassCellArraysOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->PassCellArraysOn();
}

extern "C" void vtkProbeFilter__PassCellArraysOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->PassCellArraysOff();
}

extern "C" int32_t vtkProbeFilter__GetPassCellArrays__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetPassCellArrays();
}

extern "C" void vtkProbeFilter__SetPassPointArrays__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetPassPointArrays(_arg);
}

extern "C" void vtkProbeFilter__PassPointArraysOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->PassPointArraysOn();
}

extern "C" void vtkProbeFilter__PassPointArraysOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->PassPointArraysOff();
}

extern "C" int32_t vtkProbeFilter__GetPassPointArrays__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetPassPointArrays();
}

extern "C" void vtkProbeFilter__SetPassFieldArrays__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetPassFieldArrays(_arg);
}

extern "C" void vtkProbeFilter__PassFieldArraysOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->PassFieldArraysOn();
}

extern "C" void vtkProbeFilter__PassFieldArraysOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->PassFieldArraysOff();
}

extern "C" int32_t vtkProbeFilter__GetPassFieldArrays__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetPassFieldArrays();
}

extern "C" void vtkProbeFilter__SetTolerance__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetTolerance(_arg);
}

extern "C" double vtkProbeFilter__GetTolerance__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetTolerance();
}

extern "C" void vtkProbeFilter__SetSnapToCellWithClosestPoint__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetSnapToCellWithClosestPoint(_arg);
}

extern "C" void vtkProbeFilter__SnapToCellWithClosestPointOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SnapToCellWithClosestPointOn();
}

extern "C" void vtkProbeFilter__SnapToCellWithClosestPointOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SnapToCellWithClosestPointOff();
}

extern "C" bool vtkProbeFilter__GetSnapToCellWithClosestPoint__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetSnapToCellWithClosestPoint();
}

extern "C" void vtkProbeFilter__SetSnappingRadius__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetSnappingRadius(_arg);
}

extern "C" double vtkProbeFilter__GetSnappingRadius__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetSnappingRadius();
}

extern "C" void vtkProbeFilter__SetComputeTolerance__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetComputeTolerance(_arg);
}

extern "C" void vtkProbeFilter__ComputeToleranceOn__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->ComputeToleranceOn();
}

extern "C" void vtkProbeFilter__ComputeToleranceOff__0(void* self) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->ComputeToleranceOff();
}

extern "C" bool vtkProbeFilter__GetComputeTolerance__0(void* self) {
  (void)self;
  return static_cast<vtkProbeFilter*>(self)->GetComputeTolerance();
}

extern "C" void vtkProbeFilter__SetCellLocator__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkProbeFilter*>(self)->SetCellLocator(static_cast<vtkAbstractCellLocator*>(arg0));
}

extern "C" void* vtkProbeFilter__GetCellLocator__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkProbeFilter*>(self)->GetCellLocator());
}

