// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkRenderingCellGrid.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" int32_t vtkRenderingCellGrid__IsTypeOf__0(const char* type_) {
  return vtkRenderingCellGrid::IsTypeOf(type_);
}

extern "C" int32_t vtkRenderingCellGrid__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkRenderingCellGrid*>(self)->IsA(type_);
}

extern "C" void* vtkRenderingCellGrid__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkRenderingCellGrid::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkRenderingCellGrid__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkRenderingCellGrid::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkRenderingCellGrid__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkRenderingCellGrid*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" bool vtkRenderingCellGrid__RegisterCellsAndResponders__0() {
  return vtkRenderingCellGrid::RegisterCellsAndResponders();
}

