// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkRenderPassCollection.h"
#include "vtkObjectBase.h"
#include "vtkRenderPass.h"
#include <string>

extern "C" void* vtkRenderPassCollection__rvtk_new() { return static_cast<void*>(vtkRenderPassCollection::New()); }

extern "C" int32_t vtkRenderPassCollection__IsTypeOf__0(const char* type_) {
  return vtkRenderPassCollection::IsTypeOf(type_);
}

extern "C" int32_t vtkRenderPassCollection__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkRenderPassCollection*>(self)->IsA(type_);
}

extern "C" void* vtkRenderPassCollection__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkRenderPassCollection::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkRenderPassCollection__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkRenderPassCollection::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkRenderPassCollection__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkRenderPassCollection*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkRenderPassCollection__AddItem__0(void* self, void* pass) {
  (void)self;
  static_cast<vtkRenderPassCollection*>(self)->AddItem(static_cast<vtkRenderPass*>(pass));
}

extern "C" void* vtkRenderPassCollection__GetNextRenderPass__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkRenderPassCollection*>(self)->GetNextRenderPass());
}

extern "C" void* vtkRenderPassCollection__GetLastRenderPass__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkRenderPassCollection*>(self)->GetLastRenderPass());
}

