// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkSplitSharpEdgesPolyData.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkSplitSharpEdgesPolyData__rvtk_new() { return static_cast<void*>(vtkSplitSharpEdgesPolyData::New()); }

extern "C" int32_t vtkSplitSharpEdgesPolyData__IsTypeOf__0(const char* type_) {
  return vtkSplitSharpEdgesPolyData::IsTypeOf(type_);
}

extern "C" int32_t vtkSplitSharpEdgesPolyData__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->IsA(type_);
}

extern "C" void* vtkSplitSharpEdgesPolyData__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkSplitSharpEdgesPolyData::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkSplitSharpEdgesPolyData__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkSplitSharpEdgesPolyData::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkSplitSharpEdgesPolyData__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkSplitSharpEdgesPolyData__SetFeatureAngle__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkSplitSharpEdgesPolyData*>(self)->SetFeatureAngle(_arg);
}

extern "C" double vtkSplitSharpEdgesPolyData__GetFeatureAngleMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetFeatureAngleMinValue();
}

extern "C" double vtkSplitSharpEdgesPolyData__GetFeatureAngleMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetFeatureAngleMaxValue();
}

extern "C" double vtkSplitSharpEdgesPolyData__GetFeatureAngle__0(void* self) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetFeatureAngle();
}

extern "C" void vtkSplitSharpEdgesPolyData__SetOutputPointsPrecision__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSplitSharpEdgesPolyData*>(self)->SetOutputPointsPrecision(_arg);
}

extern "C" int32_t vtkSplitSharpEdgesPolyData__GetOutputPointsPrecisionMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetOutputPointsPrecisionMinValue();
}

extern "C" int32_t vtkSplitSharpEdgesPolyData__GetOutputPointsPrecisionMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetOutputPointsPrecisionMaxValue();
}

extern "C" int32_t vtkSplitSharpEdgesPolyData__GetOutputPointsPrecision__0(void* self) {
  (void)self;
  return static_cast<vtkSplitSharpEdgesPolyData*>(self)->GetOutputPointsPrecision();
}

