// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkStaticCellLinks.h"
#include "vtkAbstractCellLinks.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkStaticCellLinks__rvtk_new() { return static_cast<void*>(vtkStaticCellLinks::New()); }

extern "C" int32_t vtkStaticCellLinks__IsTypeOf__0(const char* type_) {
  return vtkStaticCellLinks::IsTypeOf(type_);
}

extern "C" int32_t vtkStaticCellLinks__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkStaticCellLinks*>(self)->IsA(type_);
}

extern "C" void* vtkStaticCellLinks__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkStaticCellLinks::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkStaticCellLinks__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkStaticCellLinks::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkStaticCellLinks__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkStaticCellLinks*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkStaticCellLinks__BuildLinks__0(void* self) {
  (void)self;
  static_cast<vtkStaticCellLinks*>(self)->BuildLinks();
}

extern "C" int64_t vtkStaticCellLinks__GetNumberOfCells__0(void* self, int64_t ptId) {
  (void)self;
  return static_cast<vtkStaticCellLinks*>(self)->GetNumberOfCells(ptId);
}

extern "C" int64_t vtkStaticCellLinks__GetNcells__0(void* self, int64_t ptId) {
  (void)self;
  return static_cast<vtkStaticCellLinks*>(self)->GetNcells(ptId);
}

extern "C" void vtkStaticCellLinks__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkStaticCellLinks*>(self)->Initialize();
}

extern "C" void vtkStaticCellLinks__Squeeze__0(void* self) {
  (void)self;
  static_cast<vtkStaticCellLinks*>(self)->Squeeze();
}

extern "C" void vtkStaticCellLinks__Reset__0(void* self) {
  (void)self;
  static_cast<vtkStaticCellLinks*>(self)->Reset();
}

extern "C" unsigned long vtkStaticCellLinks__GetActualMemorySize__0(void* self) {
  (void)self;
  return static_cast<vtkStaticCellLinks*>(self)->GetActualMemorySize();
}

extern "C" void vtkStaticCellLinks__DeepCopy__0(void* self, void* src) {
  (void)self;
  static_cast<vtkStaticCellLinks*>(self)->DeepCopy(static_cast<vtkAbstractCellLinks*>(src));
}

extern "C" void vtkStaticCellLinks__ShallowCopy__0(void* self, void* src) {
  (void)self;
  static_cast<vtkStaticCellLinks*>(self)->ShallowCopy(static_cast<vtkAbstractCellLinks*>(src));
}

