// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkSimpleScalarTree.h"
#include "vtkObjectBase.h"
#include "vtkScalarTree.h"
#include <string>

extern "C" void* vtkSimpleScalarTree__rvtk_new() { return static_cast<void*>(vtkSimpleScalarTree::New()); }

extern "C" int32_t vtkSimpleScalarTree__IsTypeOf__0(const char* type_) {
  return vtkSimpleScalarTree::IsTypeOf(type_);
}

extern "C" int32_t vtkSimpleScalarTree__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->IsA(type_);
}

extern "C" void* vtkSimpleScalarTree__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkSimpleScalarTree::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkSimpleScalarTree__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkSimpleScalarTree::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkSimpleScalarTree__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkSimpleScalarTree__ShallowCopy__0(void* self, void* stree) {
  (void)self;
  static_cast<vtkSimpleScalarTree*>(self)->ShallowCopy(static_cast<vtkScalarTree*>(stree));
}

extern "C" void vtkSimpleScalarTree__SetBranchingFactor__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSimpleScalarTree*>(self)->SetBranchingFactor(_arg);
}

extern "C" int32_t vtkSimpleScalarTree__GetBranchingFactorMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetBranchingFactorMinValue();
}

extern "C" int32_t vtkSimpleScalarTree__GetBranchingFactorMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetBranchingFactorMaxValue();
}

extern "C" int32_t vtkSimpleScalarTree__GetBranchingFactor__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetBranchingFactor();
}

extern "C" int32_t vtkSimpleScalarTree__GetLevel__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetLevel();
}

extern "C" void vtkSimpleScalarTree__SetMaxLevel__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSimpleScalarTree*>(self)->SetMaxLevel(_arg);
}

extern "C" int32_t vtkSimpleScalarTree__GetMaxLevelMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetMaxLevelMinValue();
}

extern "C" int32_t vtkSimpleScalarTree__GetMaxLevelMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetMaxLevelMaxValue();
}

extern "C" int32_t vtkSimpleScalarTree__GetMaxLevel__0(void* self) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetMaxLevel();
}

extern "C" void vtkSimpleScalarTree__BuildTree__0(void* self) {
  (void)self;
  static_cast<vtkSimpleScalarTree*>(self)->BuildTree();
}

extern "C" void vtkSimpleScalarTree__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkSimpleScalarTree*>(self)->Initialize();
}

extern "C" void vtkSimpleScalarTree__InitTraversal__0(void* self, double scalarValue) {
  (void)self;
  static_cast<vtkSimpleScalarTree*>(self)->InitTraversal(scalarValue);
}

extern "C" int64_t vtkSimpleScalarTree__GetNumberOfCellBatches__0(void* self, double scalarValue) {
  (void)self;
  return static_cast<vtkSimpleScalarTree*>(self)->GetNumberOfCellBatches(scalarValue);
}

