// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkTranslucentPass.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkTranslucentPass__rvtk_new() { return static_cast<void*>(vtkTranslucentPass::New()); }

extern "C" int32_t vtkTranslucentPass__IsTypeOf__0(const char* type_) {
  return vtkTranslucentPass::IsTypeOf(type_);
}

extern "C" int32_t vtkTranslucentPass__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTranslucentPass*>(self)->IsA(type_);
}

extern "C" void* vtkTranslucentPass__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkTranslucentPass::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkTranslucentPass__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkTranslucentPass::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkTranslucentPass__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTranslucentPass*>(self)->GetNumberOfGenerationsFromBase(type_);
}

