// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkTensorGlyph.h"
#include "vtkAlgorithmOutput.h"
#include "vtkObjectBase.h"
#include "vtkPolyData.h"
#include <string>

extern "C" void* vtkTensorGlyph__rvtk_new() { return static_cast<void*>(vtkTensorGlyph::New()); }

extern "C" int32_t vtkTensorGlyph__IsTypeOf__0(const char* type_) {
  return vtkTensorGlyph::IsTypeOf(type_);
}

extern "C" int32_t vtkTensorGlyph__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->IsA(type_);
}

extern "C" void* vtkTensorGlyph__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkTensorGlyph::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkTensorGlyph__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkTensorGlyph::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkTensorGlyph__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkTensorGlyph__SetSourceData__0(void* self, void* source) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetSourceData(static_cast<vtkPolyData*>(source));
}

extern "C" void* vtkTensorGlyph__GetSource__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTensorGlyph*>(self)->GetSource());
}

extern "C" void vtkTensorGlyph__SetSourceConnection__0(void* self, int32_t id, void* algOutput) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetSourceConnection(id, static_cast<vtkAlgorithmOutput*>(algOutput));
}

extern "C" void vtkTensorGlyph__SetSourceConnection__1(void* self, void* algOutput) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetSourceConnection(static_cast<vtkAlgorithmOutput*>(algOutput));
}

extern "C" void vtkTensorGlyph__SetScaling__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetScaling(_arg);
}

extern "C" int32_t vtkTensorGlyph__GetScaling__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetScaling();
}

extern "C" void vtkTensorGlyph__ScalingOn__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ScalingOn();
}

extern "C" void vtkTensorGlyph__ScalingOff__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ScalingOff();
}

extern "C" void vtkTensorGlyph__SetScaleFactor__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetScaleFactor(_arg);
}

extern "C" double vtkTensorGlyph__GetScaleFactor__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetScaleFactor();
}

extern "C" void vtkTensorGlyph__SetThreeGlyphs__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetThreeGlyphs(_arg);
}

extern "C" int32_t vtkTensorGlyph__GetThreeGlyphs__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetThreeGlyphs();
}

extern "C" void vtkTensorGlyph__ThreeGlyphsOn__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ThreeGlyphsOn();
}

extern "C" void vtkTensorGlyph__ThreeGlyphsOff__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ThreeGlyphsOff();
}

extern "C" void vtkTensorGlyph__SetSymmetric__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetSymmetric(_arg);
}

extern "C" int32_t vtkTensorGlyph__GetSymmetric__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetSymmetric();
}

extern "C" void vtkTensorGlyph__SymmetricOn__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SymmetricOn();
}

extern "C" void vtkTensorGlyph__SymmetricOff__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SymmetricOff();
}

extern "C" void vtkTensorGlyph__SetLength__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetLength(_arg);
}

extern "C" double vtkTensorGlyph__GetLength__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetLength();
}

extern "C" void vtkTensorGlyph__SetExtractEigenvalues__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetExtractEigenvalues(_arg);
}

extern "C" void vtkTensorGlyph__ExtractEigenvaluesOn__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ExtractEigenvaluesOn();
}

extern "C" void vtkTensorGlyph__ExtractEigenvaluesOff__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ExtractEigenvaluesOff();
}

extern "C" int32_t vtkTensorGlyph__GetExtractEigenvalues__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetExtractEigenvalues();
}

extern "C" void vtkTensorGlyph__SetColorGlyphs__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetColorGlyphs(_arg);
}

extern "C" int32_t vtkTensorGlyph__GetColorGlyphs__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetColorGlyphs();
}

extern "C" void vtkTensorGlyph__ColorGlyphsOn__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ColorGlyphsOn();
}

extern "C" void vtkTensorGlyph__ColorGlyphsOff__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ColorGlyphsOff();
}

extern "C" void vtkTensorGlyph__SetColorMode__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetColorMode(_arg);
}

extern "C" int32_t vtkTensorGlyph__GetColorModeMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetColorModeMinValue();
}

extern "C" int32_t vtkTensorGlyph__GetColorModeMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetColorModeMaxValue();
}

extern "C" int32_t vtkTensorGlyph__GetColorMode__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetColorMode();
}

extern "C" void vtkTensorGlyph__SetColorModeToScalars__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetColorModeToScalars();
}

extern "C" void vtkTensorGlyph__SetColorModeToEigenvalues__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetColorModeToEigenvalues();
}

extern "C" void vtkTensorGlyph__SetClampScaling__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetClampScaling(_arg);
}

extern "C" int32_t vtkTensorGlyph__GetClampScaling__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetClampScaling();
}

extern "C" void vtkTensorGlyph__ClampScalingOn__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ClampScalingOn();
}

extern "C" void vtkTensorGlyph__ClampScalingOff__0(void* self) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->ClampScalingOff();
}

extern "C" void vtkTensorGlyph__SetMaxScaleFactor__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkTensorGlyph*>(self)->SetMaxScaleFactor(_arg);
}

extern "C" double vtkTensorGlyph__GetMaxScaleFactor__0(void* self) {
  (void)self;
  return static_cast<vtkTensorGlyph*>(self)->GetMaxScaleFactor();
}

