// Generated by rvtk-gen. Do not edit.
#include "rvtk_shim.h"
#include "vtkVoidArray.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkVoidArray__rvtk_new() { return static_cast<void*>(vtkVoidArray::New()); }

extern "C" void* vtkVoidArray__ExtendedNew__0() {
  return static_cast<void*>(vtkVoidArray::ExtendedNew());
}

extern "C" int32_t vtkVoidArray__IsTypeOf__0(const char* type_) {
  return vtkVoidArray::IsTypeOf(type_);
}

extern "C" int32_t vtkVoidArray__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->IsA(type_);
}

extern "C" void* vtkVoidArray__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkVoidArray::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkVoidArray__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkVoidArray::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkVoidArray__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkVoidArray__Allocate__0(void* self, int64_t sz, int64_t ext) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->Allocate(sz, ext);
}

extern "C" void vtkVoidArray__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->Initialize();
}

extern "C" int32_t vtkVoidArray__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->GetDataType();
}

extern "C" int32_t vtkVoidArray__GetDataTypeSize__0(void* self) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->GetDataTypeSize();
}

extern "C" void vtkVoidArray__SetNumberOfPointers__0(void* self, int64_t number) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->SetNumberOfPointers(number);
}

extern "C" int64_t vtkVoidArray__GetNumberOfPointers__0(void* self) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->GetNumberOfPointers();
}

extern "C" void* vtkVoidArray__GetVoidPointer__0(void* self, int64_t id) {
  (void)self;
  return const_cast<void*>(static_cast<vtkVoidArray*>(self)->GetVoidPointer(id));
}

extern "C" void vtkVoidArray__SetVoidPointer__0(void* self, int64_t id, void* ptr) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->SetVoidPointer(id, ptr);
}

extern "C" void vtkVoidArray__InsertVoidPointer__0(void* self, int64_t i, void* ptr) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->InsertVoidPointer(i, ptr);
}

extern "C" int64_t vtkVoidArray__InsertNextVoidPointer__0(void* self, void* tuple) {
  (void)self;
  return static_cast<vtkVoidArray*>(self)->InsertNextVoidPointer(tuple);
}

extern "C" void vtkVoidArray__Reset__0(void* self) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->Reset();
}

extern "C" void vtkVoidArray__Squeeze__0(void* self) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->Squeeze();
}

extern "C" void vtkVoidArray__DeepCopy__0(void* self, void* va) {
  (void)self;
  static_cast<vtkVoidArray*>(self)->DeepCopy(static_cast<vtkVoidArray*>(va));
}

