// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkAbstractBuffer.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" int32_t vtkAbstractBuffer__IsTypeOf__0(const char* type_) {
  return vtkAbstractBuffer::IsTypeOf(type_);
}

extern "C" int32_t vtkAbstractBuffer__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAbstractBuffer*>(self)->IsA(type_);
}

extern "C" void* vtkAbstractBuffer__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkAbstractBuffer::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkAbstractBuffer__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkAbstractBuffer::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkAbstractBuffer__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAbstractBuffer*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkAbstractBuffer__GetVoidBuffer__0(void* self) {
  (void)self;
  return const_cast<void*>(static_cast<vtkAbstractBuffer*>(self)->GetVoidBuffer());
}

extern "C" int64_t vtkAbstractBuffer__GetNumberOfElements__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractBuffer*>(self)->GetNumberOfElements();
}

extern "C" int32_t vtkAbstractBuffer__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractBuffer*>(self)->GetDataType();
}

extern "C" int32_t vtkAbstractBuffer__GetDataTypeSize__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractBuffer*>(self)->GetDataTypeSize();
}

