// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkAbstractArray.h"
#include "vtkIdList.h"
#include "vtkInformation.h"
#include "vtkInformationDoubleVectorKey.h"
#include "vtkInformationInformationVectorKey.h"
#include "vtkInformationIntegerKey.h"
#include "vtkInformationVariantVectorKey.h"
#include "vtkObjectBase.h"
#include "vtkVariantArray.h"
#include <string>

extern "C" int32_t vtkAbstractArray__IsTypeOf__0(const char* type_) {
  return vtkAbstractArray::IsTypeOf(type_);
}

extern "C" int32_t vtkAbstractArray__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->IsA(type_);
}

extern "C" void* vtkAbstractArray__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkAbstractArray::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkAbstractArray__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkAbstractArray::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkAbstractArray__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkAbstractArray__ReserveTuples__0(void* self, int64_t numTuples) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->ReserveTuples(numTuples);
}

extern "C" int32_t vtkAbstractArray__ReserveValues__0(void* self, int64_t numValues) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->ReserveValues(numValues);
}

extern "C" void vtkAbstractArray__Initialize__0(void* self) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->Initialize();
}

extern "C" int32_t vtkAbstractArray__GetDataType__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetDataType();
}

extern "C" int32_t vtkAbstractArray__GetDataTypeSize__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetDataTypeSize();
}

extern "C" int32_t vtkAbstractArray__GetDataTypeSize__1(int32_t type_) {
  return vtkAbstractArray::GetDataTypeSize(type_);
}

extern "C" int32_t vtkAbstractArray__GetElementComponentSize__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetElementComponentSize();
}

extern "C" void vtkAbstractArray__SetNumberOfComponents__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetNumberOfComponents(_arg);
}

extern "C" int32_t vtkAbstractArray__GetNumberOfComponentsMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetNumberOfComponentsMinValue();
}

extern "C" int32_t vtkAbstractArray__GetNumberOfComponentsMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetNumberOfComponentsMaxValue();
}

extern "C" int32_t vtkAbstractArray__GetNumberOfComponents__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetNumberOfComponents();
}

extern "C" void vtkAbstractArray__SetComponentName__0(void* self, int64_t component, const char* name) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetComponentName(component, name);
}

extern "C" const char* vtkAbstractArray__GetComponentName__0(void* self, int64_t component) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetComponentName(component);
}

extern "C" bool vtkAbstractArray__HasAComponentName__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->HasAComponentName();
}

extern "C" int32_t vtkAbstractArray__CopyComponentNames__0(void* self, void* da) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->CopyComponentNames(static_cast<vtkAbstractArray*>(da));
}

extern "C" bool vtkAbstractArray__CopyComponent__0(void* self, int32_t dstComponent, void* src, int32_t srcComponent) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->CopyComponent(dstComponent, static_cast<vtkAbstractArray*>(src), srcComponent);
}

extern "C" void vtkAbstractArray__SetNumberOfTuples__0(void* self, int64_t numTuples) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetNumberOfTuples(numTuples);
}

extern "C" bool vtkAbstractArray__SetNumberOfValues__0(void* self, int64_t numValues) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->SetNumberOfValues(numValues);
}

extern "C" int64_t vtkAbstractArray__GetNumberOfTuples__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetNumberOfTuples();
}

extern "C" int64_t vtkAbstractArray__GetNumberOfValues__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetNumberOfValues();
}

extern "C" void vtkAbstractArray__SetTuple__0(void* self, int64_t dstTupleIdx, int64_t srcTupleIdx, void* source) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetTuple(dstTupleIdx, srcTupleIdx, static_cast<vtkAbstractArray*>(source));
}

extern "C" void vtkAbstractArray__InsertTuple__0(void* self, int64_t dstTupleIdx, int64_t srcTupleIdx, void* source) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->InsertTuple(dstTupleIdx, srcTupleIdx, static_cast<vtkAbstractArray*>(source));
}

extern "C" void vtkAbstractArray__InsertTuples__0(void* self, void* dstIds, void* srcIds, void* source) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->InsertTuples(static_cast<vtkIdList*>(dstIds), static_cast<vtkIdList*>(srcIds), static_cast<vtkAbstractArray*>(source));
}

extern "C" void vtkAbstractArray__InsertTuplesStartingAt__0(void* self, int64_t dstStart, void* srcIds, void* source) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->InsertTuplesStartingAt(dstStart, static_cast<vtkIdList*>(srcIds), static_cast<vtkAbstractArray*>(source));
}

extern "C" void vtkAbstractArray__InsertTuples__1(void* self, int64_t dstStart, int64_t n, int64_t srcStart, void* source) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->InsertTuples(dstStart, n, srcStart, static_cast<vtkAbstractArray*>(source));
}

extern "C" int64_t vtkAbstractArray__InsertNextTuple__0(void* self, int64_t srcTupleIdx, void* source) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->InsertNextTuple(srcTupleIdx, static_cast<vtkAbstractArray*>(source));
}

extern "C" void vtkAbstractArray__GetTuples__0(void* self, void* tupleIds, void* output) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->GetTuples(static_cast<vtkIdList*>(tupleIds), static_cast<vtkAbstractArray*>(output));
}

extern "C" void vtkAbstractArray__GetTuples__1(void* self, int64_t p1, int64_t p2, void* output) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->GetTuples(p1, p2, static_cast<vtkAbstractArray*>(output));
}

extern "C" bool vtkAbstractArray__HasStandardMemoryLayout__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->HasStandardMemoryLayout();
}

extern "C" void* vtkAbstractArray__GetVoidPointer__0(void* self, int64_t valueIdx) {
  (void)self;
  return const_cast<void*>(static_cast<vtkAbstractArray*>(self)->GetVoidPointer(valueIdx));
}

extern "C" void vtkAbstractArray__DeepCopy__0(void* self, void* da) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->DeepCopy(static_cast<vtkAbstractArray*>(da));
}

extern "C" void vtkAbstractArray__ShallowCopy__0(void* self, void* src) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->ShallowCopy(static_cast<vtkAbstractArray*>(src));
}

extern "C" void vtkAbstractArray__InterpolateTuple__0(void* self, int64_t dstTupleIdx, int64_t srcTupleIdx1, void* source1, int64_t srcTupleIdx2, void* source2, double t) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->InterpolateTuple(dstTupleIdx, srcTupleIdx1, static_cast<vtkAbstractArray*>(source1), srcTupleIdx2, static_cast<vtkAbstractArray*>(source2), t);
}

extern "C" void vtkAbstractArray__Squeeze__0(void* self) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->Squeeze();
}

extern "C" void vtkAbstractArray__Reset__0(void* self) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->Reset();
}

extern "C" int64_t vtkAbstractArray__GetCapacity__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetCapacity();
}

extern "C" int64_t vtkAbstractArray__GetMaxId__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetMaxId();
}

extern "C" void vtkAbstractArray__SetVoidArray__0(void* self, void* array, int64_t size, int32_t save) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetVoidArray(array, size, save);
}

extern "C" void vtkAbstractArray__SetVoidArray__1(void* self, void* array, int64_t size, int32_t save, int32_t deleteMethod) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetVoidArray(array, size, save, deleteMethod);
}

extern "C" unsigned long vtkAbstractArray__GetActualMemorySize__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetActualMemorySize();
}

extern "C" void vtkAbstractArray__SetName__0(void* self, const char* _arg) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetName(_arg);
}

extern "C" const char* vtkAbstractArray__GetDataTypeAsString__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetDataTypeAsString();
}

extern "C" void* vtkAbstractArray__CreateArray__0(int32_t dataType) {
  return static_cast<void*>(vtkAbstractArray::CreateArray(dataType));
}

extern "C" int32_t vtkAbstractArray__IsNumeric__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->IsNumeric();
}

extern "C" bool vtkAbstractArray__IsIntegral__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->IsIntegral();
}

extern "C" int64_t vtkAbstractArray__GetDataSize__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetDataSize();
}

extern "C" void vtkAbstractArray__DataChanged__0(void* self) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->DataChanged();
}

extern "C" void vtkAbstractArray__ClearLookup__0(void* self) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->ClearLookup();
}

extern "C" void vtkAbstractArray__GetProminentComponentValues__0(void* self, int32_t comp, void* values, double uncertainty, double minimumProminence) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->GetProminentComponentValues(comp, static_cast<vtkVariantArray*>(values), uncertainty, minimumProminence);
}

extern "C" void* vtkAbstractArray__GetInformation__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkAbstractArray*>(self)->GetInformation());
}

extern "C" bool vtkAbstractArray__HasInformation__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->HasInformation();
}

extern "C" int32_t vtkAbstractArray__CopyInformation__0(void* self, void* infoFrom, int32_t deep) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->CopyInformation(static_cast<vtkInformation*>(infoFrom), deep);
}

extern "C" void* vtkAbstractArray__GUI_HIDE__0() {
  return static_cast<void*>(vtkAbstractArray::GUI_HIDE());
}

extern "C" void* vtkAbstractArray__PER_COMPONENT__0() {
  return static_cast<void*>(vtkAbstractArray::PER_COMPONENT());
}

extern "C" void* vtkAbstractArray__PER_FINITE_COMPONENT__0() {
  return static_cast<void*>(vtkAbstractArray::PER_FINITE_COMPONENT());
}

extern "C" void vtkAbstractArray__Modified__0(void* self) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->Modified();
}

extern "C" void* vtkAbstractArray__DISCRETE_VALUES__0() {
  return static_cast<void*>(vtkAbstractArray::DISCRETE_VALUES());
}

extern "C" void* vtkAbstractArray__DISCRETE_VALUE_SAMPLE_PARAMETERS__0() {
  return static_cast<void*>(vtkAbstractArray::DISCRETE_VALUE_SAMPLE_PARAMETERS());
}

extern "C" uint32_t vtkAbstractArray__GetMaxDiscreteValues__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetMaxDiscreteValues();
}

extern "C" void vtkAbstractArray__SetMaxDiscreteValues__0(void* self, uint32_t _arg) {
  (void)self;
  static_cast<vtkAbstractArray*>(self)->SetMaxDiscreteValues(_arg);
}

extern "C" int32_t vtkAbstractArray__GetArrayType__0(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetArrayType();
}

extern "C" const char* vtkAbstractArray__GetArrayTypeAsString__0(int32_t arrayType) {
  return vtkAbstractArray::GetArrayTypeAsString(arrayType);
}

extern "C" const char* vtkAbstractArray__GetArrayTypeAsString__1(void* self) {
  (void)self;
  return static_cast<vtkAbstractArray*>(self)->GetArrayTypeAsString();
}

