// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkBorderWidget.h"
#include "vtkBorderRepresentation.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkBorderWidget__vtk_wrap_new() { return static_cast<void*>(vtkBorderWidget::New()); }

extern "C" int32_t vtkBorderWidget__IsTypeOf__0(const char* type_) {
  return vtkBorderWidget::IsTypeOf(type_);
}

extern "C" int32_t vtkBorderWidget__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkBorderWidget*>(self)->IsA(type_);
}

extern "C" void* vtkBorderWidget__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkBorderWidget::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkBorderWidget__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkBorderWidget::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkBorderWidget__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkBorderWidget*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkBorderWidget__SetSelectable__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->SetSelectable(_arg);
}

extern "C" int32_t vtkBorderWidget__GetSelectable__0(void* self) {
  (void)self;
  return static_cast<vtkBorderWidget*>(self)->GetSelectable();
}

extern "C" void vtkBorderWidget__SelectableOn__0(void* self) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->SelectableOn();
}

extern "C" void vtkBorderWidget__SelectableOff__0(void* self) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->SelectableOff();
}

extern "C" void vtkBorderWidget__SetResizable__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->SetResizable(_arg);
}

extern "C" int32_t vtkBorderWidget__GetResizable__0(void* self) {
  (void)self;
  return static_cast<vtkBorderWidget*>(self)->GetResizable();
}

extern "C" void vtkBorderWidget__ResizableOn__0(void* self) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->ResizableOn();
}

extern "C" void vtkBorderWidget__ResizableOff__0(void* self) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->ResizableOff();
}

extern "C" void vtkBorderWidget__SetRepresentation__0(void* self, void* r) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->SetRepresentation(static_cast<vtkBorderRepresentation*>(r));
}

extern "C" void* vtkBorderWidget__GetBorderRepresentation__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkBorderWidget*>(self)->GetBorderRepresentation());
}

extern "C" void vtkBorderWidget__CreateDefaultRepresentation__0(void* self) {
  (void)self;
  static_cast<vtkBorderWidget*>(self)->CreateDefaultRepresentation();
}

extern "C" int32_t vtkBorderWidget__GetProcessEvents__0(void* self) {
  (void)self;
  return static_cast<vtkBorderWidget*>(self)->GetProcessEvents();
}

