// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkCompositeDataIterator.h"
#include "vtkCompositeDataSet.h"
#include "vtkDataObject.h"
#include "vtkInformation.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" int32_t vtkCompositeDataIterator__IsTypeOf__0(const char* type_) {
  return vtkCompositeDataIterator::IsTypeOf(type_);
}

extern "C" int32_t vtkCompositeDataIterator__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->IsA(type_);
}

extern "C" void* vtkCompositeDataIterator__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkCompositeDataIterator::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkCompositeDataIterator__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkCompositeDataIterator::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkCompositeDataIterator__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkCompositeDataIterator__SetDataSet__0(void* self, void* ds) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->SetDataSet(static_cast<vtkCompositeDataSet*>(ds));
}

extern "C" void* vtkCompositeDataIterator__GetDataSet__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkCompositeDataIterator*>(self)->GetDataSet());
}

extern "C" void vtkCompositeDataIterator__InitTraversal__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->InitTraversal();
}

extern "C" void vtkCompositeDataIterator__InitReverseTraversal__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->InitReverseTraversal();
}

extern "C" void vtkCompositeDataIterator__GoToFirstItem__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->GoToFirstItem();
}

extern "C" void vtkCompositeDataIterator__GoToNextItem__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->GoToNextItem();
}

extern "C" int32_t vtkCompositeDataIterator__IsDoneWithTraversal__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->IsDoneWithTraversal();
}

extern "C" void* vtkCompositeDataIterator__GetCurrentDataObject__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkCompositeDataIterator*>(self)->GetCurrentDataObject());
}

extern "C" void* vtkCompositeDataIterator__GetCurrentMetaData__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkCompositeDataIterator*>(self)->GetCurrentMetaData());
}

extern "C" int32_t vtkCompositeDataIterator__HasCurrentMetaData__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->HasCurrentMetaData();
}

extern "C" void vtkCompositeDataIterator__SetSkipEmptyNodes__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->SetSkipEmptyNodes(_arg);
}

extern "C" int32_t vtkCompositeDataIterator__GetSkipEmptyNodes__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->GetSkipEmptyNodes();
}

extern "C" void vtkCompositeDataIterator__SkipEmptyNodesOn__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->SkipEmptyNodesOn();
}

extern "C" void vtkCompositeDataIterator__SkipEmptyNodesOff__0(void* self) {
  (void)self;
  static_cast<vtkCompositeDataIterator*>(self)->SkipEmptyNodesOff();
}

extern "C" uint32_t vtkCompositeDataIterator__GetCurrentFlatIndex__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->GetCurrentFlatIndex();
}

extern "C" int32_t vtkCompositeDataIterator__GetReverse__0(void* self) {
  (void)self;
  return static_cast<vtkCompositeDataIterator*>(self)->GetReverse();
}

