// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkDataSetEdgeSubdivisionCriterion.h"
#include "vtkCell.h"
#include "vtkDataSet.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkDataSetEdgeSubdivisionCriterion__vtk_wrap_new() { return static_cast<void*>(vtkDataSetEdgeSubdivisionCriterion::New()); }

extern "C" int32_t vtkDataSetEdgeSubdivisionCriterion__IsTypeOf__0(const char* type_) {
  return vtkDataSetEdgeSubdivisionCriterion::IsTypeOf(type_);
}

extern "C" int32_t vtkDataSetEdgeSubdivisionCriterion__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->IsA(type_);
}

extern "C" void* vtkDataSetEdgeSubdivisionCriterion__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkDataSetEdgeSubdivisionCriterion::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkDataSetEdgeSubdivisionCriterion__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkDataSetEdgeSubdivisionCriterion::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkDataSetEdgeSubdivisionCriterion__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkDataSetEdgeSubdivisionCriterion__SetMesh__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->SetMesh(static_cast<vtkDataSet*>(arg0));
}

extern "C" void* vtkDataSetEdgeSubdivisionCriterion__GetMesh__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetMesh());
}

extern "C" void* vtkDataSetEdgeSubdivisionCriterion__GetMesh__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetMesh());
}

extern "C" void vtkDataSetEdgeSubdivisionCriterion__SetCellId__0(void* self, int64_t cell) {
  (void)self;
  static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->SetCellId(cell);
}

extern "C" int64_t vtkDataSetEdgeSubdivisionCriterion__GetCellId__0(void* self) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetCellId();
}

extern "C" int64_t vtkDataSetEdgeSubdivisionCriterion__GetCellId__1(void* self) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetCellId();
}

extern "C" void* vtkDataSetEdgeSubdivisionCriterion__GetCell__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetCell());
}

extern "C" void* vtkDataSetEdgeSubdivisionCriterion__GetCell__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetCell());
}

extern "C" void vtkDataSetEdgeSubdivisionCriterion__SetChordError2__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->SetChordError2(_arg);
}

extern "C" double vtkDataSetEdgeSubdivisionCriterion__GetChordError2__0(void* self) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetChordError2();
}

extern "C" void vtkDataSetEdgeSubdivisionCriterion__SetFieldError2__0(void* self, int32_t s, double err) {
  (void)self;
  static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->SetFieldError2(s, err);
}

extern "C" double vtkDataSetEdgeSubdivisionCriterion__GetFieldError2__0(void* self, int32_t s) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetFieldError2(s);
}

extern "C" void vtkDataSetEdgeSubdivisionCriterion__ResetFieldError2__0(void* self) {
  (void)self;
  static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->ResetFieldError2();
}

extern "C" int32_t vtkDataSetEdgeSubdivisionCriterion__GetActiveFieldCriteria__0(void* self) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetActiveFieldCriteria();
}

extern "C" int32_t vtkDataSetEdgeSubdivisionCriterion__GetActiveFieldCriteria__1(void* self) {
  (void)self;
  return static_cast<vtkDataSetEdgeSubdivisionCriterion*>(self)->GetActiveFieldCriteria();
}

