// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkDataSetGradientPrecompute.h"
#include "vtkDataSet.h"
#include "vtkDataSetAlgorithm.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkDataSetGradientPrecompute__vtk_wrap_new() { return static_cast<void*>(vtkDataSetGradientPrecompute::New()); }

extern "C" int32_t vtkDataSetGradientPrecompute__IsTypeOf__0(const char* type_) {
  return vtkDataSetGradientPrecompute::IsTypeOf(type_);
}

extern "C" int32_t vtkDataSetGradientPrecompute__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkDataSetGradientPrecompute*>(self)->IsA(type_);
}

extern "C" void* vtkDataSetGradientPrecompute__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkDataSetGradientPrecompute::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkDataSetGradientPrecompute__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkDataSetGradientPrecompute::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkDataSetGradientPrecompute__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkDataSetGradientPrecompute*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkDataSetGradientPrecompute__GradientPrecompute__0(void* ds, void* self_) {
  return vtkDataSetGradientPrecompute::GradientPrecompute(static_cast<vtkDataSet*>(ds), static_cast<vtkDataSetAlgorithm*>(self_));
}

