// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkGPUInfoList.h"
#include "vtkGPUInfo.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkGPUInfoList__vtk_wrap_new() { return static_cast<void*>(vtkGPUInfoList::New()); }

extern "C" int32_t vtkGPUInfoList__IsTypeOf__0(const char* type_) {
  return vtkGPUInfoList::IsTypeOf(type_);
}

extern "C" int32_t vtkGPUInfoList__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGPUInfoList*>(self)->IsA(type_);
}

extern "C" void* vtkGPUInfoList__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkGPUInfoList::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkGPUInfoList__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkGPUInfoList::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkGPUInfoList__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkGPUInfoList*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkGPUInfoList__Probe__0(void* self) {
  (void)self;
  static_cast<vtkGPUInfoList*>(self)->Probe();
}

extern "C" bool vtkGPUInfoList__IsProbed__0(void* self) {
  (void)self;
  return static_cast<vtkGPUInfoList*>(self)->IsProbed();
}

extern "C" int32_t vtkGPUInfoList__GetNumberOfGPUs__0(void* self) {
  (void)self;
  return static_cast<vtkGPUInfoList*>(self)->GetNumberOfGPUs();
}

extern "C" void* vtkGPUInfoList__GetGPUInfo__0(void* self, int32_t i) {
  (void)self;
  return static_cast<void*>(static_cast<vtkGPUInfoList*>(self)->GetGPUInfo(i));
}

