// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkInformationDoubleVectorKey.h"
#include "vtkInformation.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" int32_t vtkInformationDoubleVectorKey__IsTypeOf__0(const char* type_) {
  return vtkInformationDoubleVectorKey::IsTypeOf(type_);
}

extern "C" int32_t vtkInformationDoubleVectorKey__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkInformationDoubleVectorKey*>(self)->IsA(type_);
}

extern "C" void* vtkInformationDoubleVectorKey__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkInformationDoubleVectorKey::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkInformationDoubleVectorKey__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkInformationDoubleVectorKey::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkInformationDoubleVectorKey__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkInformationDoubleVectorKey*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void* vtkInformationDoubleVectorKey__MakeKey__0(const char* name, const char* location, int32_t length) {
  return static_cast<void*>(vtkInformationDoubleVectorKey::MakeKey(name, location, length));
}

extern "C" void vtkInformationDoubleVectorKey__Append__0(void* self, void* info, double value) {
  (void)self;
  static_cast<vtkInformationDoubleVectorKey*>(self)->Append(static_cast<vtkInformation*>(info), value);
}

extern "C" double vtkInformationDoubleVectorKey__Get__0(void* self, void* info, int32_t idx) {
  (void)self;
  return static_cast<vtkInformationDoubleVectorKey*>(self)->Get(static_cast<vtkInformation*>(info), idx);
}

extern "C" int32_t vtkInformationDoubleVectorKey__Length__0(void* self, void* info) {
  (void)self;
  return static_cast<vtkInformationDoubleVectorKey*>(self)->Length(static_cast<vtkInformation*>(info));
}

extern "C" void vtkInformationDoubleVectorKey__ShallowCopy__0(void* self, void* from, void* to) {
  (void)self;
  static_cast<vtkInformationDoubleVectorKey*>(self)->ShallowCopy(static_cast<vtkInformation*>(from), static_cast<vtkInformation*>(to));
}

