// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkImplicitSelectionLoop.h"
#include "vtkObjectBase.h"
#include "vtkPoints.h"
#include <string>

extern "C" void* vtkImplicitSelectionLoop__vtk_wrap_new() { return static_cast<void*>(vtkImplicitSelectionLoop::New()); }

extern "C" int32_t vtkImplicitSelectionLoop__IsTypeOf__0(const char* type_) {
  return vtkImplicitSelectionLoop::IsTypeOf(type_);
}

extern "C" int32_t vtkImplicitSelectionLoop__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkImplicitSelectionLoop*>(self)->IsA(type_);
}

extern "C" void* vtkImplicitSelectionLoop__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkImplicitSelectionLoop::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkImplicitSelectionLoop__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkImplicitSelectionLoop::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkImplicitSelectionLoop__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkImplicitSelectionLoop*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" double vtkImplicitSelectionLoop__EvaluateFunction__0(void* self, double* x) {
  (void)self;
  return static_cast<vtkImplicitSelectionLoop*>(self)->EvaluateFunction(x);
}

extern "C" void vtkImplicitSelectionLoop__EvaluateGradient__0(void* self, double* x, double* n) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->EvaluateGradient(x, n);
}

extern "C" void vtkImplicitSelectionLoop__SetLoop__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->SetLoop(static_cast<vtkPoints*>(arg0));
}

extern "C" void* vtkImplicitSelectionLoop__GetLoop__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkImplicitSelectionLoop*>(self)->GetLoop());
}

extern "C" void vtkImplicitSelectionLoop__SetAutomaticNormalGeneration__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->SetAutomaticNormalGeneration(_arg);
}

extern "C" int32_t vtkImplicitSelectionLoop__GetAutomaticNormalGeneration__0(void* self) {
  (void)self;
  return static_cast<vtkImplicitSelectionLoop*>(self)->GetAutomaticNormalGeneration();
}

extern "C" void vtkImplicitSelectionLoop__AutomaticNormalGenerationOn__0(void* self) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->AutomaticNormalGenerationOn();
}

extern "C" void vtkImplicitSelectionLoop__AutomaticNormalGenerationOff__0(void* self) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->AutomaticNormalGenerationOff();
}

extern "C" void vtkImplicitSelectionLoop__SetNormal__0(void* self, double _arg1, double _arg2, double _arg3) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->SetNormal(_arg1, _arg2, _arg3);
}

extern "C" void vtkImplicitSelectionLoop__SetNormal__1(void* self, const double* _arg) {
  (void)self;
  static_cast<vtkImplicitSelectionLoop*>(self)->SetNormal(_arg);
}

extern "C" unsigned long vtkImplicitSelectionLoop__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkImplicitSelectionLoop*>(self)->GetMTime();
}

