// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkImplicitHalo.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkImplicitHalo__vtk_wrap_new() { return static_cast<void*>(vtkImplicitHalo::New()); }

extern "C" int32_t vtkImplicitHalo__IsTypeOf__0(const char* type_) {
  return vtkImplicitHalo::IsTypeOf(type_);
}

extern "C" int32_t vtkImplicitHalo__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkImplicitHalo*>(self)->IsA(type_);
}

extern "C" void* vtkImplicitHalo__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkImplicitHalo::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkImplicitHalo__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkImplicitHalo::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkImplicitHalo__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkImplicitHalo*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" double vtkImplicitHalo__EvaluateFunction__0(void* self, double* x) {
  (void)self;
  return static_cast<vtkImplicitHalo*>(self)->EvaluateFunction(x);
}

extern "C" void vtkImplicitHalo__EvaluateGradient__0(void* self, double* x, double* g) {
  (void)self;
  static_cast<vtkImplicitHalo*>(self)->EvaluateGradient(x, g);
}

extern "C" void vtkImplicitHalo__SetRadius__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkImplicitHalo*>(self)->SetRadius(_arg);
}

extern "C" double vtkImplicitHalo__GetRadius__0(void* self) {
  (void)self;
  return static_cast<vtkImplicitHalo*>(self)->GetRadius();
}

extern "C" void vtkImplicitHalo__SetCenter__0(void* self, double _arg1, double _arg2, double _arg3) {
  (void)self;
  static_cast<vtkImplicitHalo*>(self)->SetCenter(_arg1, _arg2, _arg3);
}

extern "C" void vtkImplicitHalo__SetCenter__1(void* self, const double* _arg) {
  (void)self;
  static_cast<vtkImplicitHalo*>(self)->SetCenter(_arg);
}

extern "C" void vtkImplicitHalo__SetFadeOut__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkImplicitHalo*>(self)->SetFadeOut(_arg);
}

extern "C" double vtkImplicitHalo__GetFadeOut__0(void* self) {
  (void)self;
  return static_cast<vtkImplicitHalo*>(self)->GetFadeOut();
}

