// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkInformation.h"
#include "vtkDataObject.h"
#include "vtkInformationDataObjectKey.h"
#include "vtkInformationDoubleKey.h"
#include "vtkInformationDoubleVectorKey.h"
#include "vtkInformationIdTypeKey.h"
#include "vtkInformationInformationKey.h"
#include "vtkInformationInformationVectorKey.h"
#include "vtkInformationIntegerKey.h"
#include "vtkInformationIntegerPointerKey.h"
#include "vtkInformationIntegerVectorKey.h"
#include "vtkInformationKey.h"
#include "vtkInformationKeyVectorKey.h"
#include "vtkInformationObjectBaseKey.h"
#include "vtkInformationObjectBaseVectorKey.h"
#include "vtkInformationRequestKey.h"
#include "vtkInformationStringKey.h"
#include "vtkInformationStringVectorKey.h"
#include "vtkInformationUnsignedLongKey.h"
#include "vtkInformationVariantKey.h"
#include "vtkInformationVariantVectorKey.h"
#include "vtkInformationVector.h"
#include "vtkObjectBase.h"
#include <string>

extern "C" void* vtkInformation__vtk_wrap_new() { return static_cast<void*>(vtkInformation::New()); }

extern "C" int32_t vtkInformation__IsTypeOf__0(const char* type_) {
  return vtkInformation::IsTypeOf(type_);
}

extern "C" int32_t vtkInformation__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkInformation*>(self)->IsA(type_);
}

extern "C" void* vtkInformation__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkInformation::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkInformation__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkInformation::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkInformation__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkInformation*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkInformation__Modified__0(void* self) {
  (void)self;
  static_cast<vtkInformation*>(self)->Modified();
}

extern "C" void vtkInformation__Modified__1(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Modified(static_cast<vtkInformationKey*>(key));
}

extern "C" void vtkInformation__Clear__0(void* self) {
  (void)self;
  static_cast<vtkInformation*>(self)->Clear();
}

extern "C" int32_t vtkInformation__GetNumberOfKeys__0(void* self) {
  (void)self;
  return static_cast<vtkInformation*>(self)->GetNumberOfKeys();
}

extern "C" void vtkInformation__Copy__0(void* self, void* from, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->Copy(static_cast<vtkInformation*>(from), deep);
}

extern "C" void vtkInformation__Append__0(void* self, void* from, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformation*>(from), deep);
}

extern "C" void vtkInformation__CopyEntry__0(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__1(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationDataObjectKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__2(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationDoubleVectorKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__3(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationVariantKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__4(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationVariantVectorKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__5(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationInformationKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__6(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationInformationVectorKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__7(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationIntegerKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__8(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationIntegerVectorKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__9(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationObjectBaseVectorKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__10(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationRequestKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__11(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationStringKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__12(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationStringVectorKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntry__13(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntry(static_cast<vtkInformation*>(from), static_cast<vtkInformationUnsignedLongKey*>(key), deep);
}

extern "C" void vtkInformation__CopyEntries__0(void* self, void* from, void* key, int32_t deep) {
  (void)self;
  static_cast<vtkInformation*>(self)->CopyEntries(static_cast<vtkInformation*>(from), static_cast<vtkInformationKeyVectorKey*>(key), deep);
}

extern "C" int32_t vtkInformation__Has__0(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationKey*>(key));
}

extern "C" void vtkInformation__Remove__0(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationKey*>(key));
}

extern "C" void vtkInformation__Set__0(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationRequestKey*>(key));
}

extern "C" void vtkInformation__Remove__1(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationRequestKey*>(key));
}

extern "C" int32_t vtkInformation__Has__1(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationRequestKey*>(key));
}

extern "C" void vtkInformation__Set__1(void* self, void* key, int32_t value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationIntegerKey*>(key), value);
}

extern "C" int32_t vtkInformation__Get__0(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationIntegerKey*>(key));
}

extern "C" void vtkInformation__Remove__2(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationIntegerKey*>(key));
}

extern "C" int32_t vtkInformation__Has__2(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationIntegerKey*>(key));
}

extern "C" void vtkInformation__Set__2(void* self, void* key, int64_t value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationIdTypeKey*>(key), value);
}

extern "C" int64_t vtkInformation__Get__1(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationIdTypeKey*>(key));
}

extern "C" void vtkInformation__Remove__3(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationIdTypeKey*>(key));
}

extern "C" int32_t vtkInformation__Has__3(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationIdTypeKey*>(key));
}

extern "C" void vtkInformation__Set__3(void* self, void* key, double value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationDoubleKey*>(key), value);
}

extern "C" double vtkInformation__Get__2(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationDoubleKey*>(key));
}

extern "C" void vtkInformation__Remove__4(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationDoubleKey*>(key));
}

extern "C" int32_t vtkInformation__Has__4(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationDoubleKey*>(key));
}

extern "C" void vtkInformation__Remove__5(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationVariantKey*>(key));
}

extern "C" int32_t vtkInformation__Has__5(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationVariantKey*>(key));
}

extern "C" void vtkInformation__Append__1(void* self, void* key, int32_t value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationIntegerVectorKey*>(key), value);
}

extern "C" void vtkInformation__Set__4(void* self, void* key, int32_t value1, int32_t value2, int32_t value3) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationIntegerVectorKey*>(key), value1, value2, value3);
}

extern "C" void vtkInformation__Set__5(void* self, void* key, int32_t value1, int32_t value2, int32_t value3, int32_t value4, int32_t value5, int32_t value6) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationIntegerVectorKey*>(key), value1, value2, value3, value4, value5, value6);
}

extern "C" int32_t vtkInformation__Get__3(void* self, void* key, int32_t idx) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationIntegerVectorKey*>(key), idx);
}

extern "C" int32_t vtkInformation__Length__0(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationIntegerVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__6(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationIntegerVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Has__6(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationIntegerVectorKey*>(key));
}

extern "C" void vtkInformation__Append__2(void* self, void* key, const char* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationStringVectorKey*>(key), value);
}

extern "C" void vtkInformation__Set__6(void* self, void* key, const char* value, int32_t idx) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationStringVectorKey*>(key), value, idx);
}

extern "C" void vtkInformation__Append__3(void* self, void* key, const char* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationStringVectorKey*>(key), std::string(value));
}

extern "C" void vtkInformation__Set__7(void* self, void* key, const char* value, int32_t idx) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationStringVectorKey*>(key), std::string(value), idx);
}

extern "C" const char* vtkInformation__Get__4(void* self, void* key, int32_t idx) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationStringVectorKey*>(key), idx);
}

extern "C" int32_t vtkInformation__Length__1(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationStringVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__7(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationStringVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Has__7(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationStringVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Length__2(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationIntegerPointerKey*>(key));
}

extern "C" void vtkInformation__Remove__8(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationIntegerPointerKey*>(key));
}

extern "C" int32_t vtkInformation__Has__8(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationIntegerPointerKey*>(key));
}

extern "C" void vtkInformation__Set__8(void* self, void* key, unsigned long value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationUnsignedLongKey*>(key), value);
}

extern "C" unsigned long vtkInformation__Get__5(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationUnsignedLongKey*>(key));
}

extern "C" void vtkInformation__Remove__9(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationUnsignedLongKey*>(key));
}

extern "C" int32_t vtkInformation__Has__9(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationUnsignedLongKey*>(key));
}

extern "C" void vtkInformation__Append__4(void* self, void* key, double value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationDoubleVectorKey*>(key), value);
}

extern "C" void vtkInformation__Set__9(void* self, void* key, double value1, double value2, double value3) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationDoubleVectorKey*>(key), value1, value2, value3);
}

extern "C" void vtkInformation__Set__10(void* self, void* key, double value1, double value2, double value3, double value4, double value5, double value6) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationDoubleVectorKey*>(key), value1, value2, value3, value4, value5, value6);
}

extern "C" double vtkInformation__Get__6(void* self, void* key, int32_t idx) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationDoubleVectorKey*>(key), idx);
}

extern "C" int32_t vtkInformation__Length__3(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationDoubleVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__10(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationDoubleVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Has__10(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationDoubleVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Length__4(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationVariantVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__11(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationVariantVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Has__11(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationVariantVectorKey*>(key));
}

extern "C" void vtkInformation__Append__5(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__0(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationKey*>(value));
}

extern "C" void vtkInformation__Remove__12(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationKey*>(value));
}

extern "C" void* vtkInformation__Get__7(void* self, void* key, int32_t idx) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationKeyVectorKey*>(key), idx));
}

extern "C" int32_t vtkInformation__Length__5(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationKeyVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__13(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationKeyVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Has__12(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationKeyVectorKey*>(key));
}

extern "C" void vtkInformation__Append__6(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationDataObjectKey*>(value));
}

extern "C" void vtkInformation__Append__7(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationDoubleKey*>(value));
}

extern "C" void vtkInformation__Append__8(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationDoubleVectorKey*>(value));
}

extern "C" void vtkInformation__Append__9(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationInformationKey*>(value));
}

extern "C" void vtkInformation__Append__10(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationInformationVectorKey*>(value));
}

extern "C" void vtkInformation__Append__11(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationIntegerKey*>(value));
}

extern "C" void vtkInformation__Append__12(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationIntegerVectorKey*>(value));
}

extern "C" void vtkInformation__Append__13(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationStringKey*>(value));
}

extern "C" void vtkInformation__Append__14(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationStringVectorKey*>(value));
}

extern "C" void vtkInformation__Append__15(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationObjectBaseKey*>(value));
}

extern "C" void vtkInformation__Append__16(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationUnsignedLongKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__1(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationDataObjectKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__2(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationDoubleKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__3(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationDoubleVectorKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__4(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationInformationKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__5(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationInformationVectorKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__6(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationIntegerKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__7(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationIntegerVectorKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__8(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationStringKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__9(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationStringVectorKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__10(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationObjectBaseKey*>(value));
}

extern "C" void vtkInformation__AppendUnique__11(void* self, void* key, void* value) {
  (void)self;
  static_cast<vtkInformation*>(self)->AppendUnique(static_cast<vtkInformationKeyVectorKey*>(key), static_cast<vtkInformationUnsignedLongKey*>(value));
}

extern "C" void vtkInformation__Set__11(void* self, void* key, const char* arg1) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationStringKey*>(key), arg1);
}

extern "C" void vtkInformation__Set__12(void* self, void* key, const char* arg1) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationStringKey*>(key), std::string(arg1));
}

extern "C" const char* vtkInformation__Get__8(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationStringKey*>(key));
}

extern "C" void vtkInformation__Remove__14(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationStringKey*>(key));
}

extern "C" int32_t vtkInformation__Has__13(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationStringKey*>(key));
}

extern "C" void vtkInformation__Set__13(void* self, void* key, void* arg1) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationInformationKey*>(key), static_cast<vtkInformation*>(arg1));
}

extern "C" void* vtkInformation__Get__9(void* self, void* key) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationInformationKey*>(key)));
}

extern "C" void vtkInformation__Remove__15(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationInformationKey*>(key));
}

extern "C" int32_t vtkInformation__Has__14(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationInformationKey*>(key));
}

extern "C" void vtkInformation__Set__14(void* self, void* key, void* arg1) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationInformationVectorKey*>(key), static_cast<vtkInformationVector*>(arg1));
}

extern "C" void* vtkInformation__Get__10(void* self, void* key) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationInformationVectorKey*>(key)));
}

extern "C" void vtkInformation__Remove__16(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationInformationVectorKey*>(key));
}

extern "C" int32_t vtkInformation__Has__15(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationInformationVectorKey*>(key));
}

extern "C" void vtkInformation__Set__15(void* self, void* key, void* arg1) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationObjectBaseKey*>(key), static_cast<vtkObjectBase*>(arg1));
}

extern "C" void* vtkInformation__Get__11(void* self, void* key) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationObjectBaseKey*>(key)));
}

extern "C" void vtkInformation__Remove__17(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationObjectBaseKey*>(key));
}

extern "C" int32_t vtkInformation__Has__16(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationObjectBaseKey*>(key));
}

extern "C" void vtkInformation__Append__17(void* self, void* key, void* data) {
  (void)self;
  static_cast<vtkInformation*>(self)->Append(static_cast<vtkInformationObjectBaseVectorKey*>(key), static_cast<vtkObjectBase*>(data));
}

extern "C" void vtkInformation__Set__16(void* self, void* key, void* value, int32_t idx) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationObjectBaseVectorKey*>(key), static_cast<vtkObjectBase*>(value), idx);
}

extern "C" void* vtkInformation__Get__12(void* self, void* key, int32_t idx) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationObjectBaseVectorKey*>(key), idx));
}

extern "C" int32_t vtkInformation__Length__6(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Length(static_cast<vtkInformationObjectBaseVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__18(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationObjectBaseVectorKey*>(key));
}

extern "C" void vtkInformation__Remove__19(void* self, void* key, void* objectToRemove) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationObjectBaseVectorKey*>(key), static_cast<vtkObjectBase*>(objectToRemove));
}

extern "C" void vtkInformation__Remove__20(void* self, void* key, int32_t indexToRemove) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationObjectBaseVectorKey*>(key), indexToRemove);
}

extern "C" int32_t vtkInformation__Has__17(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationObjectBaseVectorKey*>(key));
}

extern "C" void vtkInformation__Set__17(void* self, void* key, void* arg1) {
  (void)self;
  static_cast<vtkInformation*>(self)->Set(static_cast<vtkInformationDataObjectKey*>(key), static_cast<vtkDataObject*>(arg1));
}

extern "C" void* vtkInformation__Get__13(void* self, void* key) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->Get(static_cast<vtkInformationDataObjectKey*>(key)));
}

extern "C" void vtkInformation__Remove__21(void* self, void* key) {
  (void)self;
  static_cast<vtkInformation*>(self)->Remove(static_cast<vtkInformationDataObjectKey*>(key));
}

extern "C" int32_t vtkInformation__Has__18(void* self, void* key) {
  (void)self;
  return static_cast<vtkInformation*>(self)->Has(static_cast<vtkInformationDataObjectKey*>(key));
}

extern "C" void* vtkInformation__GetKey__0(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationDataObjectKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__1(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationDoubleKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__2(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationDoubleVectorKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__3(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationInformationKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__4(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationInformationVectorKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__5(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationIntegerKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__6(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationIntegerVectorKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__7(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationRequestKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__8(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationStringKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__9(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationStringVectorKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__10(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__11(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationUnsignedLongKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__12(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationVariantKey*>(key)));
}

extern "C" void* vtkInformation__GetKey__13(void* key) {
  return static_cast<void*>(vtkInformation::GetKey(static_cast<vtkInformationVariantVectorKey*>(key)));
}

extern "C" bool vtkInformation__UsesGarbageCollector__0(void* self) {
  (void)self;
  return static_cast<vtkInformation*>(self)->UsesGarbageCollector();
}

extern "C" void vtkInformation__SetRequest__0(void* self, void* request) {
  (void)self;
  static_cast<vtkInformation*>(self)->SetRequest(static_cast<vtkInformationRequestKey*>(request));
}

extern "C" void* vtkInformation__GetRequest__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkInformation*>(self)->GetRequest());
}

