// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkOpenGLPolyDataMapper.h"
#include "vtkAbstractMapper.h"
#include "vtkActor.h"
#include "vtkObjectBase.h"
#include "vtkOpenGLVertexBufferObjectGroup.h"
#include "vtkOverrideAttribute.h"
#include "vtkRenderer.h"
#include "vtkWindow.h"
#include <string>

extern "C" void* vtkOpenGLPolyDataMapper__vtk_wrap_new() { return static_cast<void*>(vtkOpenGLPolyDataMapper::New()); }

extern "C" void* vtkOpenGLPolyDataMapper__CreateOverrideAttributes__0() {
  return static_cast<void*>(vtkOpenGLPolyDataMapper::CreateOverrideAttributes());
}

extern "C" int32_t vtkOpenGLPolyDataMapper__IsTypeOf__0(const char* type_) {
  return vtkOpenGLPolyDataMapper::IsTypeOf(type_);
}

extern "C" int32_t vtkOpenGLPolyDataMapper__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLPolyDataMapper*>(self)->IsA(type_);
}

extern "C" void* vtkOpenGLPolyDataMapper__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkOpenGLPolyDataMapper::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkOpenGLPolyDataMapper__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkOpenGLPolyDataMapper::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkOpenGLPolyDataMapper__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkOpenGLPolyDataMapper*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkOpenGLPolyDataMapper__RenderPiece__0(void* self, void* ren, void* act) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->RenderPiece(static_cast<vtkRenderer*>(ren), static_cast<vtkActor*>(act));
}

extern "C" int64_t vtkOpenGLPolyDataMapper__GetMaximumNumberOfTriangles__0(void* self, void* ren) {
  (void)self;
  return static_cast<vtkOpenGLPolyDataMapper*>(self)->GetMaximumNumberOfTriangles(static_cast<vtkRenderer*>(ren));
}

extern "C" void vtkOpenGLPolyDataMapper__RenderPieceStart__0(void* self, void* ren, void* act) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->RenderPieceStart(static_cast<vtkRenderer*>(ren), static_cast<vtkActor*>(act));
}

extern "C" void vtkOpenGLPolyDataMapper__RenderPieceDraw__0(void* self, void* ren, void* act) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->RenderPieceDraw(static_cast<vtkRenderer*>(ren), static_cast<vtkActor*>(act));
}

extern "C" void vtkOpenGLPolyDataMapper__RenderPieceFinish__0(void* self, void* ren, void* act) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->RenderPieceFinish(static_cast<vtkRenderer*>(ren), static_cast<vtkActor*>(act));
}

extern "C" void vtkOpenGLPolyDataMapper__ReleaseGraphicsResources__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->ReleaseGraphicsResources(static_cast<vtkWindow*>(arg0));
}

extern "C" int32_t vtkOpenGLPolyDataMapper__GetPopulateSelectionSettings__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLPolyDataMapper*>(self)->GetPopulateSelectionSettings();
}

extern "C" void vtkOpenGLPolyDataMapper__SetPopulateSelectionSettings__0(void* self, int32_t v) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->SetPopulateSelectionSettings(v);
}

extern "C" bool vtkOpenGLPolyDataMapper__GetSupportsSelection__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLPolyDataMapper*>(self)->GetSupportsSelection();
}

extern "C" void vtkOpenGLPolyDataMapper__ShallowCopy__0(void* self, void* m) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->ShallowCopy(static_cast<vtkAbstractMapper*>(m));
}

extern "C" void* vtkOpenGLPolyDataMapper__GetVBOs__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkOpenGLPolyDataMapper*>(self)->GetVBOs());
}

extern "C" void vtkOpenGLPolyDataMapper__SetVBOShiftScaleMethod__0(void* self, int32_t method) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->SetVBOShiftScaleMethod(method);
}

extern "C" bool vtkOpenGLPolyDataMapper__GetUseProgramPointSize__0(void* self) {
  (void)self;
  return static_cast<vtkOpenGLPolyDataMapper*>(self)->GetUseProgramPointSize();
}

extern "C" void vtkOpenGLPolyDataMapper__SetUseProgramPointSize__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->SetUseProgramPointSize(_arg);
}

extern "C" void vtkOpenGLPolyDataMapper__UseProgramPointSizeOn__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->UseProgramPointSizeOn();
}

extern "C" void vtkOpenGLPolyDataMapper__UseProgramPointSizeOff__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->UseProgramPointSizeOff();
}

extern "C" void vtkOpenGLPolyDataMapper__MapDataArrayToVertexAttribute__0(void* self, const char* vertexAttributeName, const char* dataArrayName, int32_t fieldAssociation, int32_t componentno) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->MapDataArrayToVertexAttribute(vertexAttributeName, dataArrayName, fieldAssociation, componentno);
}

extern "C" void vtkOpenGLPolyDataMapper__MapDataArrayToMultiTextureAttribute__0(void* self, const char* tname, const char* dataArrayName, int32_t fieldAssociation, int32_t componentno) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->MapDataArrayToMultiTextureAttribute(tname, dataArrayName, fieldAssociation, componentno);
}

extern "C" void vtkOpenGLPolyDataMapper__RemoveVertexAttributeMapping__0(void* self, const char* vertexAttributeName) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->RemoveVertexAttributeMapping(vertexAttributeName);
}

extern "C" void vtkOpenGLPolyDataMapper__RemoveAllVertexAttributeMappings__0(void* self) {
  (void)self;
  static_cast<vtkOpenGLPolyDataMapper*>(self)->RemoveAllVertexAttributeMappings();
}

