// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkPolyDataToReebGraphFilter.h"
#include "vtkObjectBase.h"
#include "vtkReebGraph.h"
#include <string>

extern "C" void* vtkPolyDataToReebGraphFilter__vtk_wrap_new() { return static_cast<void*>(vtkPolyDataToReebGraphFilter::New()); }

extern "C" int32_t vtkPolyDataToReebGraphFilter__IsTypeOf__0(const char* type_) {
  return vtkPolyDataToReebGraphFilter::IsTypeOf(type_);
}

extern "C" int32_t vtkPolyDataToReebGraphFilter__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPolyDataToReebGraphFilter*>(self)->IsA(type_);
}

extern "C" void* vtkPolyDataToReebGraphFilter__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkPolyDataToReebGraphFilter::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkPolyDataToReebGraphFilter__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkPolyDataToReebGraphFilter::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkPolyDataToReebGraphFilter__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPolyDataToReebGraphFilter*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkPolyDataToReebGraphFilter__SetFieldId__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkPolyDataToReebGraphFilter*>(self)->SetFieldId(_arg);
}

extern "C" int32_t vtkPolyDataToReebGraphFilter__GetFieldId__0(void* self) {
  (void)self;
  return static_cast<vtkPolyDataToReebGraphFilter*>(self)->GetFieldId();
}

extern "C" void* vtkPolyDataToReebGraphFilter__GetOutput__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyDataToReebGraphFilter*>(self)->GetOutput());
}

