// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkPyramid.h"
#include "vtkCell.h"
#include "vtkCellArray.h"
#include "vtkCellData.h"
#include "vtkDataArray.h"
#include "vtkIdList.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkObjectBase.h"
#include "vtkPointData.h"
#include <string>

extern "C" void* vtkPyramid__vtk_wrap_new() { return static_cast<void*>(vtkPyramid::New()); }

extern "C" int32_t vtkPyramid__IsTypeOf__0(const char* type_) {
  return vtkPyramid::IsTypeOf(type_);
}

extern "C" int32_t vtkPyramid__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->IsA(type_);
}

extern "C" void* vtkPyramid__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkPyramid::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkPyramid__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkPyramid::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkPyramid__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" bool vtkPyramid__GetCentroid__0(void* self, double* centroid) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetCentroid(centroid);
}

extern "C" bool vtkPyramid__IsInsideOut__0(void* self) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->IsInsideOut();
}

extern "C" int32_t vtkPyramid__GetCellType__0(void* self) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetCellType();
}

extern "C" int32_t vtkPyramid__GetCellDimension__0(void* self) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetCellDimension();
}

extern "C" int32_t vtkPyramid__GetNumberOfEdges__0(void* self) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetNumberOfEdges();
}

extern "C" int32_t vtkPyramid__GetNumberOfFaces__0(void* self) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetNumberOfFaces();
}

extern "C" void* vtkPyramid__GetEdge__0(void* self, int32_t edgeId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPyramid*>(self)->GetEdge(edgeId));
}

extern "C" void* vtkPyramid__GetFace__0(void* self, int32_t faceId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPyramid*>(self)->GetFace(faceId));
}

extern "C" int32_t vtkPyramid__CellBoundary__0(void* self, int32_t subId, const double* pcoords, void* pts) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->CellBoundary(subId, pcoords, static_cast<vtkIdList*>(pts));
}

extern "C" void vtkPyramid__Contour__0(void* self, double value, void* cellScalars, void* locator, void* verts, void* lines, void* polys, void* inPd, void* outPd, void* inCd, int64_t cellId, void* outCd) {
  (void)self;
  static_cast<vtkPyramid*>(self)->Contour(value, static_cast<vtkDataArray*>(cellScalars), static_cast<vtkIncrementalPointLocator*>(locator), static_cast<vtkCellArray*>(verts), static_cast<vtkCellArray*>(lines), static_cast<vtkCellArray*>(polys), static_cast<vtkPointData*>(inPd), static_cast<vtkPointData*>(outPd), static_cast<vtkCellData*>(inCd), cellId, static_cast<vtkCellData*>(outCd));
}

extern "C" void vtkPyramid__Clip__0(void* self, double value, void* cellScalars, void* locator, void* connectivity, void* inPd, void* outPd, void* inCd, int64_t cellId, void* outCd, int32_t insideOut) {
  (void)self;
  static_cast<vtkPyramid*>(self)->Clip(value, static_cast<vtkDataArray*>(cellScalars), static_cast<vtkIncrementalPointLocator*>(locator), static_cast<vtkCellArray*>(connectivity), static_cast<vtkPointData*>(inPd), static_cast<vtkPointData*>(outPd), static_cast<vtkCellData*>(inCd), cellId, static_cast<vtkCellData*>(outCd), insideOut);
}

extern "C" int32_t vtkPyramid__TriangulateLocalIds__0(void* self, int32_t index, void* ptIds) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->TriangulateLocalIds(index, static_cast<vtkIdList*>(ptIds));
}

extern "C" int32_t vtkPyramid__GetParametricCenter__0(void* self, double* pcoords) {
  (void)self;
  return static_cast<vtkPyramid*>(self)->GetParametricCenter(pcoords);
}

extern "C" void vtkPyramid__InterpolationFunctions__0(const double* pcoords, double* weights) {
  vtkPyramid::InterpolationFunctions(pcoords, weights);
}

extern "C" void vtkPyramid__InterpolationDerivs__0(const double* pcoords, double* derivs) {
  vtkPyramid::InterpolationDerivs(pcoords, derivs);
}

extern "C" void vtkPyramid__InterpolateFunctions__0(void* self, const double* pcoords, double* weights) {
  (void)self;
  static_cast<vtkPyramid*>(self)->InterpolateFunctions(pcoords, weights);
}

extern "C" void vtkPyramid__InterpolateDerivs__0(void* self, const double* pcoords, double* derivs) {
  (void)self;
  static_cast<vtkPyramid*>(self)->InterpolateDerivs(pcoords, derivs);
}

