// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkPolyDataCollection.h"
#include "vtkObjectBase.h"
#include "vtkPolyData.h"
#include <string>

extern "C" void* vtkPolyDataCollection__vtk_wrap_new() { return static_cast<void*>(vtkPolyDataCollection::New()); }

extern "C" int32_t vtkPolyDataCollection__IsTypeOf__0(const char* type_) {
  return vtkPolyDataCollection::IsTypeOf(type_);
}

extern "C" int32_t vtkPolyDataCollection__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPolyDataCollection*>(self)->IsA(type_);
}

extern "C" void* vtkPolyDataCollection__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkPolyDataCollection::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkPolyDataCollection__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkPolyDataCollection::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkPolyDataCollection__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkPolyDataCollection*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkPolyDataCollection__AddItem__0(void* self, void* pd) {
  (void)self;
  static_cast<vtkPolyDataCollection*>(self)->AddItem(static_cast<vtkPolyData*>(pd));
}

extern "C" void* vtkPolyDataCollection__GetNextItem__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkPolyDataCollection*>(self)->GetNextItem());
}

