// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkQuadraticWedge.h"
#include "vtkCell.h"
#include "vtkCellArray.h"
#include "vtkCellData.h"
#include "vtkDataArray.h"
#include "vtkIdList.h"
#include "vtkIncrementalPointLocator.h"
#include "vtkObjectBase.h"
#include "vtkPointData.h"
#include <string>

extern "C" void* vtkQuadraticWedge__vtk_wrap_new() { return static_cast<void*>(vtkQuadraticWedge::New()); }

extern "C" int32_t vtkQuadraticWedge__IsTypeOf__0(const char* type_) {
  return vtkQuadraticWedge::IsTypeOf(type_);
}

extern "C" int32_t vtkQuadraticWedge__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->IsA(type_);
}

extern "C" void* vtkQuadraticWedge__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkQuadraticWedge::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkQuadraticWedge__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkQuadraticWedge::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkQuadraticWedge__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" int32_t vtkQuadraticWedge__GetCellType__0(void* self) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->GetCellType();
}

extern "C" int32_t vtkQuadraticWedge__GetCellDimension__0(void* self) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->GetCellDimension();
}

extern "C" int32_t vtkQuadraticWedge__GetNumberOfEdges__0(void* self) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->GetNumberOfEdges();
}

extern "C" int32_t vtkQuadraticWedge__GetNumberOfFaces__0(void* self) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->GetNumberOfFaces();
}

extern "C" void* vtkQuadraticWedge__GetEdge__0(void* self, int32_t edgeId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkQuadraticWedge*>(self)->GetEdge(edgeId));
}

extern "C" void* vtkQuadraticWedge__GetFace__0(void* self, int32_t faceId) {
  (void)self;
  return static_cast<void*>(static_cast<vtkQuadraticWedge*>(self)->GetFace(faceId));
}

extern "C" int32_t vtkQuadraticWedge__CellBoundary__0(void* self, int32_t subId, const double* pcoords, void* pts) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->CellBoundary(subId, pcoords, static_cast<vtkIdList*>(pts));
}

extern "C" void vtkQuadraticWedge__Contour__0(void* self, double value, void* cellScalars, void* locator, void* verts, void* lines, void* polys, void* inPd, void* outPd, void* inCd, int64_t cellId, void* outCd) {
  (void)self;
  static_cast<vtkQuadraticWedge*>(self)->Contour(value, static_cast<vtkDataArray*>(cellScalars), static_cast<vtkIncrementalPointLocator*>(locator), static_cast<vtkCellArray*>(verts), static_cast<vtkCellArray*>(lines), static_cast<vtkCellArray*>(polys), static_cast<vtkPointData*>(inPd), static_cast<vtkPointData*>(outPd), static_cast<vtkCellData*>(inCd), cellId, static_cast<vtkCellData*>(outCd));
}

extern "C" int32_t vtkQuadraticWedge__TriangulateLocalIds__0(void* self, int32_t index, void* ptIds) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->TriangulateLocalIds(index, static_cast<vtkIdList*>(ptIds));
}

extern "C" void vtkQuadraticWedge__Clip__0(void* self, double value, void* cellScalars, void* locator, void* tetras, void* inPd, void* outPd, void* inCd, int64_t cellId, void* outCd, int32_t insideOut) {
  (void)self;
  static_cast<vtkQuadraticWedge*>(self)->Clip(value, static_cast<vtkDataArray*>(cellScalars), static_cast<vtkIncrementalPointLocator*>(locator), static_cast<vtkCellArray*>(tetras), static_cast<vtkPointData*>(inPd), static_cast<vtkPointData*>(outPd), static_cast<vtkCellData*>(inCd), cellId, static_cast<vtkCellData*>(outCd), insideOut);
}

extern "C" int32_t vtkQuadraticWedge__GetParametricCenter__0(void* self, double* pcoords) {
  (void)self;
  return static_cast<vtkQuadraticWedge*>(self)->GetParametricCenter(pcoords);
}

extern "C" void vtkQuadraticWedge__InterpolationFunctions__0(const double* pcoords, double* weights) {
  vtkQuadraticWedge::InterpolationFunctions(pcoords, weights);
}

extern "C" void vtkQuadraticWedge__InterpolationDerivs__0(const double* pcoords, double* derivs) {
  vtkQuadraticWedge::InterpolationDerivs(pcoords, derivs);
}

extern "C" void vtkQuadraticWedge__InterpolateFunctions__0(void* self, const double* pcoords, double* weights) {
  (void)self;
  static_cast<vtkQuadraticWedge*>(self)->InterpolateFunctions(pcoords, weights);
}

extern "C" void vtkQuadraticWedge__InterpolateDerivs__0(void* self, const double* pcoords, double* derivs) {
  (void)self;
  static_cast<vtkQuadraticWedge*>(self)->InterpolateDerivs(pcoords, derivs);
}

