// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkRemovePolyData.h"
#include "vtkIdTypeArray.h"
#include "vtkObjectBase.h"
#include "vtkPolyData.h"
#include <string>

extern "C" void* vtkRemovePolyData__vtk_wrap_new() { return static_cast<void*>(vtkRemovePolyData::New()); }

extern "C" int32_t vtkRemovePolyData__IsTypeOf__0(const char* type_) {
  return vtkRemovePolyData::IsTypeOf(type_);
}

extern "C" int32_t vtkRemovePolyData__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkRemovePolyData*>(self)->IsA(type_);
}

extern "C" void* vtkRemovePolyData__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkRemovePolyData::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkRemovePolyData__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkRemovePolyData::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkRemovePolyData__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkRemovePolyData*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkRemovePolyData__RemoveInputData__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkRemovePolyData*>(self)->RemoveInputData(static_cast<vtkPolyData*>(arg0));
}

extern "C" void* vtkRemovePolyData__GetInput__0(void* self, int32_t idx) {
  (void)self;
  return static_cast<void*>(static_cast<vtkRemovePolyData*>(self)->GetInput(idx));
}

extern "C" void* vtkRemovePolyData__GetInput__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkRemovePolyData*>(self)->GetInput());
}

extern "C" void vtkRemovePolyData__SetCellIds__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkRemovePolyData*>(self)->SetCellIds(static_cast<vtkIdTypeArray*>(arg0));
}

extern "C" void* vtkRemovePolyData__GetCellIds__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkRemovePolyData*>(self)->GetCellIds());
}

extern "C" void vtkRemovePolyData__SetPointIds__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkRemovePolyData*>(self)->SetPointIds(static_cast<vtkIdTypeArray*>(arg0));
}

extern "C" void* vtkRemovePolyData__GetPointIds__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkRemovePolyData*>(self)->GetPointIds());
}

extern "C" void vtkRemovePolyData__SetExactMatch__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkRemovePolyData*>(self)->SetExactMatch(_arg);
}

extern "C" bool vtkRemovePolyData__GetExactMatch__0(void* self) {
  (void)self;
  return static_cast<vtkRemovePolyData*>(self)->GetExactMatch();
}

extern "C" void vtkRemovePolyData__ExactMatchOn__0(void* self) {
  (void)self;
  static_cast<vtkRemovePolyData*>(self)->ExactMatchOn();
}

extern "C" void vtkRemovePolyData__ExactMatchOff__0(void* self) {
  (void)self;
  static_cast<vtkRemovePolyData*>(self)->ExactMatchOff();
}

