// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkSelectVisiblePoints.h"
#include "vtkObjectBase.h"
#include "vtkRenderer.h"
#include <string>

extern "C" void* vtkSelectVisiblePoints__vtk_wrap_new() { return static_cast<void*>(vtkSelectVisiblePoints::New()); }

extern "C" int32_t vtkSelectVisiblePoints__IsTypeOf__0(const char* type_) {
  return vtkSelectVisiblePoints::IsTypeOf(type_);
}

extern "C" int32_t vtkSelectVisiblePoints__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->IsA(type_);
}

extern "C" void* vtkSelectVisiblePoints__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkSelectVisiblePoints::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkSelectVisiblePoints__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkSelectVisiblePoints::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkSelectVisiblePoints__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkSelectVisiblePoints__SetRenderer__0(void* self, void* ren) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetRenderer(static_cast<vtkRenderer*>(ren));
}

extern "C" void* vtkSelectVisiblePoints__GetRenderer__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkSelectVisiblePoints*>(self)->GetRenderer());
}

extern "C" void vtkSelectVisiblePoints__SetSelectionWindow__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetSelectionWindow(_arg);
}

extern "C" int32_t vtkSelectVisiblePoints__GetSelectionWindow__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetSelectionWindow();
}

extern "C" void vtkSelectVisiblePoints__SelectionWindowOn__0(void* self) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SelectionWindowOn();
}

extern "C" void vtkSelectVisiblePoints__SelectionWindowOff__0(void* self) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SelectionWindowOff();
}

extern "C" void vtkSelectVisiblePoints__SetSelection__0(void* self, int32_t _arg1, int32_t _arg2, int32_t _arg3, int32_t _arg4) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetSelection(_arg1, _arg2, _arg3, _arg4);
}

extern "C" void vtkSelectVisiblePoints__SetSelection__1(void* self, const int32_t* _arg) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetSelection(_arg);
}

extern "C" void vtkSelectVisiblePoints__SetSelectInvisible__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetSelectInvisible(_arg);
}

extern "C" int32_t vtkSelectVisiblePoints__GetSelectInvisible__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetSelectInvisible();
}

extern "C" void vtkSelectVisiblePoints__SelectInvisibleOn__0(void* self) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SelectInvisibleOn();
}

extern "C" void vtkSelectVisiblePoints__SelectInvisibleOff__0(void* self) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SelectInvisibleOff();
}

extern "C" void vtkSelectVisiblePoints__SetTolerance__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetTolerance(_arg);
}

extern "C" double vtkSelectVisiblePoints__GetToleranceMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetToleranceMinValue();
}

extern "C" double vtkSelectVisiblePoints__GetToleranceMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetToleranceMaxValue();
}

extern "C" double vtkSelectVisiblePoints__GetTolerance__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetTolerance();
}

extern "C" void vtkSelectVisiblePoints__SetToleranceWorld__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkSelectVisiblePoints*>(self)->SetToleranceWorld(_arg);
}

extern "C" double vtkSelectVisiblePoints__GetToleranceWorldMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetToleranceWorldMinValue();
}

extern "C" double vtkSelectVisiblePoints__GetToleranceWorldMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetToleranceWorldMaxValue();
}

extern "C" double vtkSelectVisiblePoints__GetToleranceWorld__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetToleranceWorld();
}

extern "C" unsigned long vtkSelectVisiblePoints__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkSelectVisiblePoints*>(self)->GetMTime();
}

