// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkSphereTreeFilter.h"
#include "vtkObjectBase.h"
#include "vtkSphereTree.h"
#include <string>

extern "C" void* vtkSphereTreeFilter__vtk_wrap_new() { return static_cast<void*>(vtkSphereTreeFilter::New()); }

extern "C" int32_t vtkSphereTreeFilter__IsTypeOf__0(const char* type_) {
  return vtkSphereTreeFilter::IsTypeOf(type_);
}

extern "C" int32_t vtkSphereTreeFilter__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->IsA(type_);
}

extern "C" void* vtkSphereTreeFilter__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkSphereTreeFilter::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkSphereTreeFilter__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkSphereTreeFilter::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkSphereTreeFilter__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkSphereTreeFilter__SetSphereTree__0(void* self, void* arg0) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetSphereTree(static_cast<vtkSphereTree*>(arg0));
}

extern "C" void* vtkSphereTreeFilter__GetSphereTree__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkSphereTreeFilter*>(self)->GetSphereTree());
}

extern "C" void vtkSphereTreeFilter__SetExtractionMode__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetExtractionMode(_arg);
}

extern "C" int32_t vtkSphereTreeFilter__GetExtractionMode__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetExtractionMode();
}

extern "C" void vtkSphereTreeFilter__SetExtractionModeToLevels__0(void* self) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetExtractionModeToLevels();
}

extern "C" void vtkSphereTreeFilter__SetExtractionModeToPoint__0(void* self) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetExtractionModeToPoint();
}

extern "C" void vtkSphereTreeFilter__SetExtractionModeToLine__0(void* self) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetExtractionModeToLine();
}

extern "C" void vtkSphereTreeFilter__SetExtractionModeToPlane__0(void* self) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetExtractionModeToPlane();
}

extern "C" const char* vtkSphereTreeFilter__GetExtractionModeAsString__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetExtractionModeAsString();
}

extern "C" void vtkSphereTreeFilter__SetTreeHierarchy__0(void* self, bool _arg) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetTreeHierarchy(_arg);
}

extern "C" bool vtkSphereTreeFilter__GetTreeHierarchy__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetTreeHierarchy();
}

extern "C" void vtkSphereTreeFilter__TreeHierarchyOn__0(void* self) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->TreeHierarchyOn();
}

extern "C" void vtkSphereTreeFilter__TreeHierarchyOff__0(void* self) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->TreeHierarchyOff();
}

extern "C" void vtkSphereTreeFilter__SetLevel__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetLevel(_arg);
}

extern "C" int32_t vtkSphereTreeFilter__GetLevelMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetLevelMinValue();
}

extern "C" int32_t vtkSphereTreeFilter__GetLevelMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetLevelMaxValue();
}

extern "C" int32_t vtkSphereTreeFilter__GetLevel__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetLevel();
}

extern "C" void vtkSphereTreeFilter__SetPoint__0(void* self, double _arg1, double _arg2, double _arg3) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetPoint(_arg1, _arg2, _arg3);
}

extern "C" void vtkSphereTreeFilter__SetPoint__1(void* self, const double* _arg) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetPoint(_arg);
}

extern "C" void vtkSphereTreeFilter__SetRay__0(void* self, double _arg1, double _arg2, double _arg3) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetRay(_arg1, _arg2, _arg3);
}

extern "C" void vtkSphereTreeFilter__SetRay__1(void* self, const double* _arg) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetRay(_arg);
}

extern "C" void vtkSphereTreeFilter__SetNormal__0(void* self, double _arg1, double _arg2, double _arg3) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetNormal(_arg1, _arg2, _arg3);
}

extern "C" void vtkSphereTreeFilter__SetNormal__1(void* self, const double* _arg) {
  (void)self;
  static_cast<vtkSphereTreeFilter*>(self)->SetNormal(_arg);
}

extern "C" unsigned long vtkSphereTreeFilter__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkSphereTreeFilter*>(self)->GetMTime();
}

