// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkTooltipItem.h"
#include "vtkBrush.h"
#include "vtkContext2D.h"
#include "vtkObjectBase.h"
#include "vtkPen.h"
#include "vtkTextProperty.h"
#include <string>

extern "C" void* vtkTooltipItem__vtk_wrap_new() { return static_cast<void*>(vtkTooltipItem::New()); }

extern "C" int32_t vtkTooltipItem__IsTypeOf__0(const char* type_) {
  return vtkTooltipItem::IsTypeOf(type_);
}

extern "C" int32_t vtkTooltipItem__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTooltipItem*>(self)->IsA(type_);
}

extern "C" void* vtkTooltipItem__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkTooltipItem::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkTooltipItem__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkTooltipItem::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkTooltipItem__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkTooltipItem*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkTooltipItem__SetPosition__0(void* self, float _arg1, float _arg2) {
  (void)self;
  static_cast<vtkTooltipItem*>(self)->SetPosition(_arg1, _arg2);
}

extern "C" void vtkTooltipItem__SetPosition__1(void* self, const float* _arg) {
  (void)self;
  static_cast<vtkTooltipItem*>(self)->SetPosition(_arg);
}

extern "C" char* vtkTooltipItem__GetText__0(void* self) {
  (void)self;
  return vtk_wrap_strdup((static_cast<vtkTooltipItem*>(self)->GetText()).c_str());
}

extern "C" void* vtkTooltipItem__GetPen__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTooltipItem*>(self)->GetPen());
}

extern "C" void* vtkTooltipItem__GetBrush__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTooltipItem*>(self)->GetBrush());
}

extern "C" void* vtkTooltipItem__GetTextProperties__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkTooltipItem*>(self)->GetTextProperties());
}

extern "C" void vtkTooltipItem__Update__0(void* self) {
  (void)self;
  static_cast<vtkTooltipItem*>(self)->Update();
}

extern "C" bool vtkTooltipItem__Paint__0(void* self, void* painter) {
  (void)self;
  return static_cast<vtkTooltipItem*>(self)->Paint(static_cast<vtkContext2D*>(painter));
}

