// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkUnstructuredGridVolumeZSweepMapper.h"
#include "vtkObjectBase.h"
#include "vtkRenderer.h"
#include "vtkUnstructuredGridVolumeRayIntegrator.h"
#include "vtkVolume.h"
#include <string>

extern "C" void* vtkUnstructuredGridVolumeZSweepMapper__vtk_wrap_new() { return static_cast<void*>(vtkUnstructuredGridVolumeZSweepMapper::New()); }

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__IsTypeOf__0(const char* type_) {
  return vtkUnstructuredGridVolumeZSweepMapper::IsTypeOf(type_);
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->IsA(type_);
}

extern "C" void* vtkUnstructuredGridVolumeZSweepMapper__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkUnstructuredGridVolumeZSweepMapper::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkUnstructuredGridVolumeZSweepMapper__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkUnstructuredGridVolumeZSweepMapper::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkUnstructuredGridVolumeZSweepMapper__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetImageSampleDistance__0(void* self, float _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetImageSampleDistance(_arg);
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetImageSampleDistanceMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetImageSampleDistanceMinValue();
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetImageSampleDistanceMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetImageSampleDistanceMaxValue();
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetImageSampleDistance__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetImageSampleDistance();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetMinimumImageSampleDistance__0(void* self, float _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetMinimumImageSampleDistance(_arg);
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetMinimumImageSampleDistanceMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMinimumImageSampleDistanceMinValue();
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetMinimumImageSampleDistanceMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMinimumImageSampleDistanceMaxValue();
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetMinimumImageSampleDistance__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMinimumImageSampleDistance();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetMaximumImageSampleDistance__0(void* self, float _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetMaximumImageSampleDistance(_arg);
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetMaximumImageSampleDistanceMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMaximumImageSampleDistanceMinValue();
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetMaximumImageSampleDistanceMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMaximumImageSampleDistanceMaxValue();
}

extern "C" float vtkUnstructuredGridVolumeZSweepMapper__GetMaximumImageSampleDistance__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMaximumImageSampleDistance();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetAutoAdjustSampleDistances__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetAutoAdjustSampleDistances(_arg);
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetAutoAdjustSampleDistancesMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetAutoAdjustSampleDistancesMinValue();
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetAutoAdjustSampleDistancesMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetAutoAdjustSampleDistancesMaxValue();
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetAutoAdjustSampleDistances__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetAutoAdjustSampleDistances();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__AutoAdjustSampleDistancesOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->AutoAdjustSampleDistancesOn();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__AutoAdjustSampleDistancesOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->AutoAdjustSampleDistancesOff();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetIntermixIntersectingGeometry__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetIntermixIntersectingGeometry(_arg);
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetIntermixIntersectingGeometryMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetIntermixIntersectingGeometryMinValue();
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetIntermixIntersectingGeometryMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetIntermixIntersectingGeometryMaxValue();
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetIntermixIntersectingGeometry__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetIntermixIntersectingGeometry();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__IntermixIntersectingGeometryOn__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->IntermixIntersectingGeometryOn();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__IntermixIntersectingGeometryOff__0(void* self) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->IntermixIntersectingGeometryOff();
}

extern "C" int32_t vtkUnstructuredGridVolumeZSweepMapper__GetMaxPixelListSize__0(void* self) {
  (void)self;
  return static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetMaxPixelListSize();
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetMaxPixelListSize__0(void* self, int32_t size) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetMaxPixelListSize(size);
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__SetRayIntegrator__0(void* self, void* ri) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->SetRayIntegrator(static_cast<vtkUnstructuredGridVolumeRayIntegrator*>(ri));
}

extern "C" void* vtkUnstructuredGridVolumeZSweepMapper__GetRayIntegrator__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->GetRayIntegrator());
}

extern "C" void vtkUnstructuredGridVolumeZSweepMapper__Render__0(void* self, void* ren, void* vol) {
  (void)self;
  static_cast<vtkUnstructuredGridVolumeZSweepMapper*>(self)->Render(static_cast<vtkRenderer*>(ren), static_cast<vtkVolume*>(vol));
}

