// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkVolumeProperty.h"
#include "vtkColorTransferFunction.h"
#include "vtkContourValues.h"
#include "vtkImageData.h"
#include "vtkImplicitFunction.h"
#include "vtkObjectBase.h"
#include "vtkPiecewiseFunction.h"
#include <string>

extern "C" void* vtkVolumeProperty__vtk_wrap_new() { return static_cast<void*>(vtkVolumeProperty::New()); }

extern "C" int32_t vtkVolumeProperty__IsTypeOf__0(const char* type_) {
  return vtkVolumeProperty::IsTypeOf(type_);
}

extern "C" int32_t vtkVolumeProperty__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->IsA(type_);
}

extern "C" void* vtkVolumeProperty__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkVolumeProperty::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkVolumeProperty__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkVolumeProperty::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkVolumeProperty__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" void vtkVolumeProperty__DeepCopy__0(void* self, void* p) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->DeepCopy(static_cast<vtkVolumeProperty*>(p));
}

extern "C" unsigned long vtkVolumeProperty__GetMTime__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetMTime();
}

extern "C" void vtkVolumeProperty__SetIndependentComponents__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetIndependentComponents(_arg);
}

extern "C" int32_t vtkVolumeProperty__GetIndependentComponentsMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetIndependentComponentsMinValue();
}

extern "C" int32_t vtkVolumeProperty__GetIndependentComponentsMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetIndependentComponentsMaxValue();
}

extern "C" int32_t vtkVolumeProperty__GetIndependentComponents__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetIndependentComponents();
}

extern "C" void vtkVolumeProperty__IndependentComponentsOn__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->IndependentComponentsOn();
}

extern "C" void vtkVolumeProperty__IndependentComponentsOff__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->IndependentComponentsOff();
}

extern "C" void vtkVolumeProperty__SetInterpolationType__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetInterpolationType(_arg);
}

extern "C" int32_t vtkVolumeProperty__GetInterpolationTypeMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetInterpolationTypeMinValue();
}

extern "C" int32_t vtkVolumeProperty__GetInterpolationTypeMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetInterpolationTypeMaxValue();
}

extern "C" int32_t vtkVolumeProperty__GetInterpolationType__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetInterpolationType();
}

extern "C" void vtkVolumeProperty__SetInterpolationTypeToNearest__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetInterpolationTypeToNearest();
}

extern "C" void vtkVolumeProperty__SetInterpolationTypeToLinear__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetInterpolationTypeToLinear();
}

extern "C" const char* vtkVolumeProperty__GetInterpolationTypeAsString__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetInterpolationTypeAsString();
}

extern "C" void vtkVolumeProperty__SetComponentWeight__0(void* self, int32_t index, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetComponentWeight(index, value);
}

extern "C" double vtkVolumeProperty__GetComponentWeight__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetComponentWeight(index);
}

extern "C" void vtkVolumeProperty__SetColor__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetColor(index, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void vtkVolumeProperty__SetColor__1(void* self, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetColor(static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void vtkVolumeProperty__SetColor__2(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetColor(index, static_cast<vtkColorTransferFunction*>(function));
}

extern "C" void vtkVolumeProperty__SetColor__3(void* self, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetColor(static_cast<vtkColorTransferFunction*>(function));
}

extern "C" int32_t vtkVolumeProperty__GetColorChannels__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetColorChannels(index);
}

extern "C" int32_t vtkVolumeProperty__GetColorChannels__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetColorChannels();
}

extern "C" void* vtkVolumeProperty__GetGrayTransferFunction__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetGrayTransferFunction(index));
}

extern "C" void* vtkVolumeProperty__GetGrayTransferFunction__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetGrayTransferFunction());
}

extern "C" void vtkVolumeProperty__SetGrayTransferFunction__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetGrayTransferFunction(index, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" int32_t vtkVolumeProperty__GetNumberOfGrayTransferFunctions__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetNumberOfGrayTransferFunctions();
}

extern "C" void* vtkVolumeProperty__GetRGBTransferFunction__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetRGBTransferFunction(index));
}

extern "C" void* vtkVolumeProperty__GetRGBTransferFunction__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetRGBTransferFunction());
}

extern "C" void vtkVolumeProperty__SetRGBTransferFunction__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetRGBTransferFunction(index, static_cast<vtkColorTransferFunction*>(function));
}

extern "C" int32_t vtkVolumeProperty__GetNumberOfRGBTransferFunctions__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetNumberOfRGBTransferFunctions();
}

extern "C" void vtkVolumeProperty__SetScalarOpacity__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetScalarOpacity(index, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void vtkVolumeProperty__SetScalarOpacity__1(void* self, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetScalarOpacity(static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void* vtkVolumeProperty__GetScalarOpacity__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetScalarOpacity(index));
}

extern "C" void* vtkVolumeProperty__GetScalarOpacity__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetScalarOpacity());
}

extern "C" void vtkVolumeProperty__SetScalarOpacityFunction__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetScalarOpacityFunction(index, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void* vtkVolumeProperty__GetScalarOpacityFunction__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetScalarOpacityFunction(index));
}

extern "C" int32_t vtkVolumeProperty__GetNumberOfScalarOpacityFunctions__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetNumberOfScalarOpacityFunctions();
}

extern "C" void vtkVolumeProperty__SetScalarOpacityUnitDistance__0(void* self, int32_t index, double distance) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetScalarOpacityUnitDistance(index, distance);
}

extern "C" void vtkVolumeProperty__SetScalarOpacityUnitDistance__1(void* self, double distance) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetScalarOpacityUnitDistance(distance);
}

extern "C" double vtkVolumeProperty__GetScalarOpacityUnitDistance__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetScalarOpacityUnitDistance(index);
}

extern "C" double vtkVolumeProperty__GetScalarOpacityUnitDistance__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetScalarOpacityUnitDistance();
}

extern "C" void vtkVolumeProperty__SetGradientOpacity__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetGradientOpacity(index, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void vtkVolumeProperty__SetGradientOpacity__1(void* self, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetGradientOpacity(static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void vtkVolumeProperty__SetGradientOpacityFunction__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetGradientOpacityFunction(index, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void* vtkVolumeProperty__GetGradientOpacityFunction__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetGradientOpacityFunction(index));
}

extern "C" int32_t vtkVolumeProperty__GetNumberOfGradientOpacityFunctions__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetNumberOfGradientOpacityFunctions();
}

extern "C" void vtkVolumeProperty__SetTransferFunction2D__0(void* self, int32_t index, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetTransferFunction2D(index, static_cast<vtkImageData*>(function));
}

extern "C" void vtkVolumeProperty__SetTransferFunction2D__1(void* self, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetTransferFunction2D(static_cast<vtkImageData*>(function));
}

extern "C" void* vtkVolumeProperty__GetTransferFunction2D__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetTransferFunction2D(index));
}

extern "C" void* vtkVolumeProperty__GetTransferFunction2D__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetTransferFunction2D());
}

extern "C" int32_t vtkVolumeProperty__GetNumberOfTransferFunction2Ds__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetNumberOfTransferFunction2Ds();
}

extern "C" void vtkVolumeProperty__SetTransferFunctionMode__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetTransferFunctionMode(_arg);
}

extern "C" int32_t vtkVolumeProperty__GetTransferFunctionModeMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetTransferFunctionModeMinValue();
}

extern "C" int32_t vtkVolumeProperty__GetTransferFunctionModeMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetTransferFunctionModeMaxValue();
}

extern "C" int32_t vtkVolumeProperty__GetTransferFunctionMode__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetTransferFunctionMode();
}

extern "C" void vtkVolumeProperty__SetTransferFunctionModeTo1D__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetTransferFunctionModeTo1D();
}

extern "C" void vtkVolumeProperty__SetTransferFunctionModeTo2D__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetTransferFunctionModeTo2D();
}

extern "C" void* vtkVolumeProperty__GetGradientOpacity__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetGradientOpacity(index));
}

extern "C" void* vtkVolumeProperty__GetGradientOpacity__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetGradientOpacity());
}

extern "C" void vtkVolumeProperty__SetDisableGradientOpacity__0(void* self, int32_t index, int32_t value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetDisableGradientOpacity(index, value);
}

extern "C" void vtkVolumeProperty__SetDisableGradientOpacity__1(void* self, int32_t value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetDisableGradientOpacity(value);
}

extern "C" void vtkVolumeProperty__DisableGradientOpacityOn__0(void* self, int32_t index) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->DisableGradientOpacityOn(index);
}

extern "C" void vtkVolumeProperty__DisableGradientOpacityOn__1(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->DisableGradientOpacityOn();
}

extern "C" void vtkVolumeProperty__DisableGradientOpacityOff__0(void* self, int32_t index) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->DisableGradientOpacityOff(index);
}

extern "C" void vtkVolumeProperty__DisableGradientOpacityOff__1(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->DisableGradientOpacityOff();
}

extern "C" int32_t vtkVolumeProperty__GetDisableGradientOpacity__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetDisableGradientOpacity(index);
}

extern "C" int32_t vtkVolumeProperty__GetDisableGradientOpacity__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetDisableGradientOpacity();
}

extern "C" void* vtkVolumeProperty__GetStoredGradientOpacity__0(void* self, int32_t index) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetStoredGradientOpacity(index));
}

extern "C" void* vtkVolumeProperty__GetStoredGradientOpacity__1(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetStoredGradientOpacity());
}

extern "C" bool vtkVolumeProperty__HasGradientOpacity__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->HasGradientOpacity(index);
}

extern "C" bool vtkVolumeProperty__HasLabelGradientOpacity__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->HasLabelGradientOpacity();
}

extern "C" void vtkVolumeProperty__SetShade__0(void* self, int32_t index, int32_t value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetShade(index, value);
}

extern "C" void vtkVolumeProperty__SetShade__1(void* self, int32_t value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetShade(value);
}

extern "C" int32_t vtkVolumeProperty__GetShade__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetShade(index);
}

extern "C" int32_t vtkVolumeProperty__GetShade__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetShade();
}

extern "C" void vtkVolumeProperty__ShadeOn__0(void* self, int32_t index) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->ShadeOn(index);
}

extern "C" void vtkVolumeProperty__ShadeOn__1(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->ShadeOn();
}

extern "C" void vtkVolumeProperty__ShadeOff__0(void* self, int32_t index) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->ShadeOff(index);
}

extern "C" void vtkVolumeProperty__ShadeOff__1(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->ShadeOff();
}

extern "C" void vtkVolumeProperty__SetAmbient__0(void* self, int32_t index, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetAmbient(index, value);
}

extern "C" void vtkVolumeProperty__SetAmbient__1(void* self, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetAmbient(value);
}

extern "C" double vtkVolumeProperty__GetAmbient__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetAmbient(index);
}

extern "C" double vtkVolumeProperty__GetAmbient__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetAmbient();
}

extern "C" void vtkVolumeProperty__SetDiffuse__0(void* self, int32_t index, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetDiffuse(index, value);
}

extern "C" void vtkVolumeProperty__SetDiffuse__1(void* self, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetDiffuse(value);
}

extern "C" double vtkVolumeProperty__GetDiffuse__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetDiffuse(index);
}

extern "C" double vtkVolumeProperty__GetDiffuse__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetDiffuse();
}

extern "C" void vtkVolumeProperty__SetSpecular__0(void* self, int32_t index, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetSpecular(index, value);
}

extern "C" void vtkVolumeProperty__SetSpecular__1(void* self, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetSpecular(value);
}

extern "C" double vtkVolumeProperty__GetSpecular__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetSpecular(index);
}

extern "C" double vtkVolumeProperty__GetSpecular__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetSpecular();
}

extern "C" void vtkVolumeProperty__SetSpecularPower__0(void* self, int32_t index, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetSpecularPower(index, value);
}

extern "C" void vtkVolumeProperty__SetSpecularPower__1(void* self, double value) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetSpecularPower(value);
}

extern "C" double vtkVolumeProperty__GetSpecularPower__0(void* self, int32_t index) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetSpecularPower(index);
}

extern "C" double vtkVolumeProperty__GetSpecularPower__1(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetSpecularPower();
}

extern "C" void* vtkVolumeProperty__GetIsoSurfaceValues__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetIsoSurfaceValues());
}

extern "C" void vtkVolumeProperty__SetSliceFunction__0(void* self, void* _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetSliceFunction(static_cast<vtkImplicitFunction*>(_arg));
}

extern "C" void* vtkVolumeProperty__GetSliceFunction__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetSliceFunction());
}

extern "C" void vtkVolumeProperty__SetScatteringAnisotropy__0(void* self, float _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetScatteringAnisotropy(_arg);
}

extern "C" float vtkVolumeProperty__GetScatteringAnisotropyMinValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetScatteringAnisotropyMinValue();
}

extern "C" float vtkVolumeProperty__GetScatteringAnisotropyMaxValue__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetScatteringAnisotropyMaxValue();
}

extern "C" float vtkVolumeProperty__GetScatteringAnisotropy__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetScatteringAnisotropy();
}

extern "C" void vtkVolumeProperty__UpdateMTimes__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->UpdateMTimes();
}

extern "C" void vtkVolumeProperty__SetUseClippedVoxelIntensity__0(void* self, int32_t _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetUseClippedVoxelIntensity(_arg);
}

extern "C" int32_t vtkVolumeProperty__GetUseClippedVoxelIntensity__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetUseClippedVoxelIntensity();
}

extern "C" void vtkVolumeProperty__UseClippedVoxelIntensityOn__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->UseClippedVoxelIntensityOn();
}

extern "C" void vtkVolumeProperty__UseClippedVoxelIntensityOff__0(void* self) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->UseClippedVoxelIntensityOff();
}

extern "C" void vtkVolumeProperty__SetClippedVoxelIntensity__0(void* self, double _arg) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetClippedVoxelIntensity(_arg);
}

extern "C" double vtkVolumeProperty__GetClippedVoxelIntensity__0(void* self) {
  (void)self;
  return static_cast<vtkVolumeProperty*>(self)->GetClippedVoxelIntensity();
}

extern "C" void vtkVolumeProperty__SetLabelColor__0(void* self, int32_t label, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetLabelColor(label, static_cast<vtkColorTransferFunction*>(function));
}

extern "C" void* vtkVolumeProperty__GetLabelColor__0(void* self, int32_t label) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetLabelColor(label));
}

extern "C" void vtkVolumeProperty__SetLabelScalarOpacity__0(void* self, int32_t label, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetLabelScalarOpacity(label, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void* vtkVolumeProperty__GetLabelScalarOpacity__0(void* self, int32_t label) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetLabelScalarOpacity(label));
}

extern "C" void vtkVolumeProperty__SetLabelGradientOpacity__0(void* self, int32_t label, void* function) {
  (void)self;
  static_cast<vtkVolumeProperty*>(self)->SetLabelGradientOpacity(label, static_cast<vtkPiecewiseFunction*>(function));
}

extern "C" void* vtkVolumeProperty__GetLabelGradientOpacity__0(void* self, int32_t label) {
  (void)self;
  return static_cast<void*>(static_cast<vtkVolumeProperty*>(self)->GetLabelGradientOpacity(label));
}

