// Generated by vtk-wrap-gen. Do not edit.
#include "vtk_wrap_shim.h"
#include "vtkViewDependentErrorMetric.h"
#include "vtkObjectBase.h"
#include "vtkViewport.h"
#include <string>

extern "C" void* vtkViewDependentErrorMetric__vtk_wrap_new() { return static_cast<void*>(vtkViewDependentErrorMetric::New()); }

extern "C" int32_t vtkViewDependentErrorMetric__IsTypeOf__0(const char* type_) {
  return vtkViewDependentErrorMetric::IsTypeOf(type_);
}

extern "C" int32_t vtkViewDependentErrorMetric__IsA__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkViewDependentErrorMetric*>(self)->IsA(type_);
}

extern "C" void* vtkViewDependentErrorMetric__SafeDownCast__0(void* o) {
  return static_cast<void*>(vtkViewDependentErrorMetric::SafeDownCast(static_cast<vtkObjectBase*>(o)));
}

extern "C" int64_t vtkViewDependentErrorMetric__GetNumberOfGenerationsFromBaseType__0(const char* type_) {
  return vtkViewDependentErrorMetric::GetNumberOfGenerationsFromBaseType(type_);
}

extern "C" int64_t vtkViewDependentErrorMetric__GetNumberOfGenerationsFromBase__0(void* self, const char* type_) {
  (void)self;
  return static_cast<vtkViewDependentErrorMetric*>(self)->GetNumberOfGenerationsFromBase(type_);
}

extern "C" double vtkViewDependentErrorMetric__GetPixelTolerance__0(void* self) {
  (void)self;
  return static_cast<vtkViewDependentErrorMetric*>(self)->GetPixelTolerance();
}

extern "C" void vtkViewDependentErrorMetric__SetPixelTolerance__0(void* self, double value) {
  (void)self;
  static_cast<vtkViewDependentErrorMetric*>(self)->SetPixelTolerance(value);
}

extern "C" void* vtkViewDependentErrorMetric__GetViewport__0(void* self) {
  (void)self;
  return static_cast<void*>(static_cast<vtkViewDependentErrorMetric*>(self)->GetViewport());
}

extern "C" void vtkViewDependentErrorMetric__SetViewport__0(void* self, void* viewport) {
  (void)self;
  static_cast<vtkViewDependentErrorMetric*>(self)->SetViewport(static_cast<vtkViewport*>(viewport));
}

